package codegen

import (
	"fmt"
	"quill/ast"
	"strings"
)

func (g *Generator) genEmbedLiteral(e *ast.EmbedLiteral) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("new Discord.EmbedBuilder().setTitle(\"%s\")", escapeJS(e.Title)))
	for _, f := range e.Fields {
		switch f.Type {
		case "color":
			hex, ok := embedColorMap[f.Value]
			if !ok {
				hex = "0x" + f.Value // allow raw hex
			}
			out.WriteString(fmt.Sprintf(".setColor(%s)", hex))
		case "field":
			out.WriteString(fmt.Sprintf(".addFields({ name: \"%s\", value: \"%s\" })", escapeJS(f.Name), escapeJS(f.Value)))
		case "footer":
			out.WriteString(fmt.Sprintf(".setFooter({ text: \"%s\" })", escapeJS(f.Value)))
		case "description":
			out.WriteString(fmt.Sprintf(".setDescription(\"%s\")", escapeJS(f.Value)))
		case "thumbnail":
			out.WriteString(fmt.Sprintf(".setThumbnail(\"%s\")", escapeJS(f.Value)))
		case "image":
			out.WriteString(fmt.Sprintf(".setImage(\"%s\")", escapeJS(f.Value)))
		}
	}
	return out.String()
}

// hasCommandStatements checks if the program has any CommandStatement nodes.
func (g *Generator) hasCommandStatements(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		if _, ok := stmt.(*ast.CommandStatement); ok {
			return true
		}
	}
	return false
}

// collectCommands extracts all CommandStatements from the program.
func (g *Generator) collectCommands(program *ast.Program) []*ast.CommandStatement {
	var cmds []*ast.CommandStatement
	for _, stmt := range program.Statements {
		if cmd, ok := stmt.(*ast.CommandStatement); ok {
			cmds = append(cmds, cmd)
		}
	}
	return cmds
}

// genCommandRegistration generates the slash command registration and dispatch code.
func (g *Generator) genCommandRegistration(cmds []*ast.CommandStatement) string {
	var out strings.Builder

	clientVar := g.discordClientVar
	if clientVar == "" {
		clientVar = "client"
	}

	// Build commands array
	out.WriteString("const __quill_commands = [\n")
	for _, cmd := range cmds {
		out.WriteString(fmt.Sprintf("  new (require(\"discord.js\").SlashCommandBuilder)().setName(\"%s\").setDescription(\"%s\")", escapeJS(cmd.Name), escapeJS(cmd.Description)))
		for _, param := range cmd.Params {
			out.WriteString(fmt.Sprintf(".addStringOption(opt => opt.setName(\"%s\").setDescription(\"%s\").setRequired(true))", escapeJS(param), escapeJS(param)))
		}
		out.WriteString(",\n")
	}
	out.WriteString("];\n")

	// Ready handler to register commands
	out.WriteString(fmt.Sprintf("%s.on(\"ready\", async () => {\n", clientVar))
	out.WriteString("  const { REST, Routes } = require(\"discord.js\");\n")
	out.WriteString(fmt.Sprintf("  const rest = new REST({ version: \"10\" }).setToken(%s.token);\n", clientVar))
	out.WriteString("  try {\n")
	out.WriteString(fmt.Sprintf("    await rest.put(Routes.applicationCommands(%s.user.id), { body: __quill_commands.map(c => c.toJSON()) });\n", clientVar))
	out.WriteString("    console.log(\"Slash commands registered.\");\n")
	out.WriteString("  } catch(e) { console.error(\"Failed to register commands:\", e); }\n")
	out.WriteString("});\n")

	// Interaction handler
	out.WriteString(fmt.Sprintf("%s.on(\"interactionCreate\", async (interaction) => {\n", clientVar))
	out.WriteString("  if (!interaction.isChatInputCommand()) return;\n")
	for i, cmd := range cmds {
		keyword := "if"
		if i > 0 {
			keyword = "else if"
		}
		out.WriteString(fmt.Sprintf("  %s (interaction.commandName === \"%s\") {\n", keyword, escapeJS(cmd.Name)))
		// Extract params
		for _, param := range cmd.Params {
			out.WriteString(fmt.Sprintf("    const %s = interaction.options.getString(\"%s\");\n", param, escapeJS(param)))
		}
		// Generate body
		g.indent += 2
		for _, stmt := range cmd.Body {
			out.WriteString(g.genStmt(stmt))
			out.WriteString("\n")
		}
		g.indent -= 2
		out.WriteString("  }\n")
	}
	out.WriteString("});\n")

	return out.String()
}

// generateWorker produces Cloudflare Worker compatible ES module output.
func (g *Generator) generateWorker(program *ast.Program) string {
	var out strings.Builder
	out.WriteString("// Generated by Quill — Cloudflare Worker\n")

	// Generate use statements as ES module imports
	for _, stmt := range program.Statements {
		if u, ok := stmt.(*ast.UseStatement); ok {
			varName := strings.ReplaceAll(u.Path, "-", "_")
			varName = strings.ReplaceAll(varName, "/", "_")
			varName = strings.ReplaceAll(varName, "@", "")
			varName = strings.ReplaceAll(varName, ".", "_")
			if u.Alias != "" {
				varName = u.Alias
			}
			out.WriteString(fmt.Sprintf("import %s from \"%s\";\n", varName, u.Path))
		}
		if f, ok := stmt.(*ast.FromUseStatement); ok {
			namesParts := make([]string, len(f.Names))
			for i, n := range f.Names {
				if i < len(f.Aliases) && f.Aliases[i] != "" {
					namesParts[i] = n + " as " + f.Aliases[i]
				} else {
					namesParts[i] = n
				}
			}
			names := strings.Join(namesParts, ", ")
			out.WriteString(fmt.Sprintf("import { %s } from \"%s\";\n", names, f.Path))
		}
	}

	// Generate non-import, non-worker statements (variable declarations, functions, etc.)
	for _, stmt := range program.Statements {
		switch stmt.(type) {
		case *ast.UseStatement, *ast.FromUseStatement, *ast.WorkerHandler:
			continue
		default:
			out.WriteString(g.genStmt(stmt))
			out.WriteString("\n")
		}
	}

	// Generate the worker handler
	for _, stmt := range program.Statements {
		if w, ok := stmt.(*ast.WorkerHandler); ok {
			out.WriteString(g.genStmt(w))
			out.WriteString("\n")
		}
	}

	return out.String()
}

// hasWorkerHandler checks if the program contains a WorkerHandler statement.
func (g *Generator) hasWorkerHandler(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		if _, ok := stmt.(*ast.WorkerHandler); ok {
			return true
		}
	}
	return false
}

// genWorkerHandler generates Cloudflare Worker export default { async fetch() {} } code.
func (g *Generator) genWorkerHandler(s *ast.WorkerHandler, prefix string) string {
	var out strings.Builder
	params := strings.Join(s.Params, ", ")
	out.WriteString(fmt.Sprintf("%sexport default {\n", prefix))
	out.WriteString(fmt.Sprintf("%s  async fetch(%s) {\n", prefix, params))
	g.indent += 2
	out.WriteString(g.genBlock(s.Body))
	g.indent -= 2
	out.WriteString(fmt.Sprintf("%s  }\n", prefix))
	out.WriteString(fmt.Sprintf("%s};", prefix))
	return out.String()
}

// genWorkerRespond generates return new Response(...) for worker context.
func (g *Generator) genWorkerRespond(s *ast.RespondStatement, prefix string) string {
	expr := g.genExpr(s.Value)
	statusPart := ""
	if s.StatusCode > 0 {
		statusPart = fmt.Sprintf(", { status: %d }", s.StatusCode)
	}

	switch s.ContentType {
	case "json":
		headers := `{ headers: { "Content-Type": "application/json" }`
		if s.StatusCode > 0 {
			headers = fmt.Sprintf(`{ headers: { "Content-Type": "application/json" }, status: %d`, s.StatusCode)
		}
		return fmt.Sprintf("%sreturn new Response(JSON.stringify(%s), %s });", prefix, expr, headers)
	case "html":
		headers := `{ headers: { "Content-Type": "text/html" }`
		if s.StatusCode > 0 {
			headers = fmt.Sprintf(`{ headers: { "Content-Type": "text/html" }, status: %d`, s.StatusCode)
		}
		return fmt.Sprintf("%sreturn new Response(%s, %s });", prefix, expr, headers)
	default:
		if s.StatusCode > 0 {
			return fmt.Sprintf("%sreturn new Response(%s%s);", prefix, expr, statusPart)
		}
		return fmt.Sprintf("%sreturn new Response(%s);", prefix, expr)
	}
}

