package codegen

import (
	"fmt"
	"os"
	"quill/ast"
	"quill/lexer"
	"quill/parser"
	"quill/stdlib"
	"strings"
)

type Generator struct {
	indent   int
	declared map[string]bool
}

func New() *Generator {
	return &Generator{
		declared: make(map[string]bool),
	}
}

func (g *Generator) Generate(program *ast.Program) string {
	var out strings.Builder

	out.WriteString("// Generated by Quill\n")
	out.WriteString(stdlib.Runtime)
	out.WriteString("\n")

	for _, stmt := range program.Statements {
		out.WriteString(g.genStmt(stmt))
		out.WriteString("\n")
	}

	return out.String()
}

func (g *Generator) genStmt(stmt ast.Statement) string {
	prefix := strings.Repeat("  ", g.indent)

	switch s := stmt.(type) {
	case *ast.AssignStatement:
		value := g.genExpr(s.Value)
		if g.declared[s.Name] {
			return fmt.Sprintf("%s%s = %s;", prefix, s.Name, value)
		}
		g.declared[s.Name] = true
		return fmt.Sprintf("%slet %s = %s;", prefix, s.Name, value)

	case *ast.SayStatement:
		return fmt.Sprintf("%sconsole.log(%s);", prefix, g.genExpr(s.Value))

	case *ast.IfStatement:
		return g.genIf(s, prefix)

	case *ast.ForEachStatement:
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf("%sfor (const %s of %s) {\n%s%s}", prefix, s.Variable, g.genExpr(s.Iterable), body, prefix)

	case *ast.WhileStatement:
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf("%swhile (%s) {\n%s%s}", prefix, g.genExpr(s.Condition), body, prefix)

	case *ast.FuncDefinition:
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		params := strings.Join(s.Params, ", ")
		return fmt.Sprintf("%sfunction %s(%s) {\n%s%s}", prefix, s.Name, params, body, prefix)

	case *ast.ReturnStatement:
		return fmt.Sprintf("%sreturn %s;", prefix, g.genExpr(s.Value))

	case *ast.ExprStatement:
		return fmt.Sprintf("%s%s;", prefix, g.genExpr(s.Expr))

	case *ast.UseStatement:
		imported, err := os.ReadFile(s.Path)
		if err != nil {
			return fmt.Sprintf("%s// Error: could not import %q", prefix, s.Path)
		}
		l := lexer.New(string(imported))
		tokens, _ := l.Tokenize()
		pr := parser.New(tokens)
		prog, _ := pr.Parse()
		importGen := New()
		importGen.indent = g.indent
		code := importGen.GenerateBody(prog)
		return fmt.Sprintf("%s// imported from %q\n%s", prefix, s.Path, code)

	case *ast.TestBlock:
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf(`%s(() => {
%s  try {
%s%s    __test_passed++;
%s    console.log("  \u2713 %s");
%s  } catch(e) {
%s    __test_failed++;
%s    console.log("  \u2717 %s:", e.message);
%s  }
%s})();`, prefix, prefix, prefix, body, prefix, s.Name, prefix, prefix, prefix, s.Name, prefix, prefix)

	case *ast.ExpectStatement:
		exprStr := g.genExpr(s.Expr)
		return fmt.Sprintf(`%sif (!(%s)) throw new Error("Expected %s to be true");`, prefix, exprStr, escapeJS(exprStr))

	default:
		return prefix + "/* unknown statement */"
	}
}

func (g *Generator) genIf(s *ast.IfStatement, prefix string) string {
	var out strings.Builder

	g.indent++
	body := g.genBlock(s.Body)
	g.indent--

	out.WriteString(fmt.Sprintf("%sif (%s) {\n%s%s}", prefix, g.genExpr(s.Condition), body, prefix))

	for _, elif := range s.ElseIfs {
		g.indent++
		elifBody := g.genBlock(elif.Body)
		g.indent--
		out.WriteString(fmt.Sprintf(" else if (%s) {\n%s%s}", g.genExpr(elif.Condition), elifBody, prefix))
	}

	if len(s.Else) > 0 {
		g.indent++
		elseBody := g.genBlock(s.Else)
		g.indent--
		out.WriteString(fmt.Sprintf(" else {\n%s%s}", elseBody, prefix))
	}

	return out.String()
}

func (g *Generator) genBlock(stmts []ast.Statement) string {
	var out strings.Builder
	for _, stmt := range stmts {
		out.WriteString(g.genStmt(stmt))
		out.WriteString("\n")
	}
	return out.String()
}

func (g *Generator) genExpr(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.StringLiteral:
		if strings.Contains(e.Value, "{") {
			// Convert {var} to ${var} for JS template literals
			converted := e.Value
			converted = strings.ReplaceAll(converted, "`", "\\`")
			converted = convertInterpolation(converted)
			return "`" + converted + "`"
		}
		// Escape any backticks and return as regular string
		escaped := strings.ReplaceAll(e.Value, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
		return `"` + escaped + `"`

	case *ast.NumberLiteral:
		if e.Value == float64(int64(e.Value)) {
			return fmt.Sprintf("%d", int64(e.Value))
		}
		return fmt.Sprintf("%g", e.Value)

	case *ast.BoolLiteral:
		if e.Value {
			return "true"
		}
		return "false"

	case *ast.Identifier:
		return e.Name

	case *ast.ListLiteral:
		elems := make([]string, len(e.Elements))
		for i, el := range e.Elements {
			elems[i] = g.genExpr(el)
		}
		return "[" + strings.Join(elems, ", ") + "]"

	case *ast.BinaryExpr:
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), e.Operator, g.genExpr(e.Right))

	case *ast.ComparisonExpr:
		if e.Operator == "contains" {
			return fmt.Sprintf("__contains(%s, %s)", g.genExpr(e.Left), g.genExpr(e.Right))
		}
		op := e.Operator
		if op == "==" {
			op = "==="
		}
		if op == "!=" {
			op = "!=="
		}
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), op, g.genExpr(e.Right))

	case *ast.LogicalExpr:
		op := "&&"
		if e.Operator == "or" {
			op = "||"
		}
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), op, g.genExpr(e.Right))

	case *ast.NotExpr:
		return fmt.Sprintf("(!%s)", g.genExpr(e.Operand))

	case *ast.UnaryMinusExpr:
		return fmt.Sprintf("(-%s)", g.genExpr(e.Operand))

	case *ast.CallExpr:
		args := make([]string, len(e.Args))
		for i, a := range e.Args {
			args[i] = g.genExpr(a)
		}
		return fmt.Sprintf("%s(%s)", g.genExpr(e.Function), strings.Join(args, ", "))

	case *ast.DotExpr:
		return fmt.Sprintf("%s.%s", g.genExpr(e.Object), e.Field)

	case *ast.IndexExpr:
		return fmt.Sprintf("%s[%s]", g.genExpr(e.Object), g.genExpr(e.Index))

	default:
		return "undefined"
	}
}

func (g *Generator) GenerateBody(program *ast.Program) string {
	var out strings.Builder
	for _, stmt := range program.Statements {
		out.WriteString(g.genStmt(stmt))
		out.WriteString("\n")
	}
	return out.String()
}

func escapeJS(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

// convertInterpolation converts {expr} to ${expr} for JS template literals.
func convertInterpolation(s string) string {
	var out strings.Builder
	i := 0
	for i < len(s) {
		if s[i] == '{' {
			// Check if it's already ${
			if i > 0 && s[i-1] == '$' {
				out.WriteByte(s[i])
			} else {
				out.WriteString("${")
			}
			i++
		} else {
			out.WriteByte(s[i])
			i++
		}
	}
	return out.String()
}
