package codegen

import (
	"fmt"
	"os"
	"quill/ast"
	"quill/lexer"
	"quill/parser"
	"quill/stdlib"
	"strings"
)

type Generator struct {
	indent    int
	declared  map[string]bool
	browser   bool
	SourceMap *SourceMap
	genLine   int // current generated line number (0-based)
}

func New() *Generator {
	return &Generator{
		declared: make(map[string]bool),
	}
}

func NewBrowser() *Generator {
	return &Generator{
		declared: make(map[string]bool),
		browser:  true,
	}
}

func (g *Generator) Generate(program *ast.Program) string {
	var out strings.Builder

	// Generate user code first to check for await
	var userCode strings.Builder
	for _, stmt := range program.Statements {
		userCode.WriteString(g.genStmt(stmt))
		userCode.WriteString("\n")
	}
	userCodeStr := userCode.String()

	out.WriteString("// Generated by Quill\n")
	if g.browser {
		out.WriteString(stdlib.BrowserRuntime)
	} else {
		out.WriteString(stdlib.Runtime)
	}
	out.WriteString("\n")

	// Include framework runtime if any component statements are present
	if g.hasComponents(program) {
		out.WriteString(stdlib.FrameworkRuntime)
		out.WriteString("\n")
	}

	// Count the preamble lines so source map offsets are correct
	preamble := out.String()
	preambleLines := strings.Count(preamble, "\n")

	if strings.Contains(userCodeStr, "await ") {
		g.genLine = preambleLines // (async () => {
		out.WriteString("(async () => {\n")
		preambleLines++ // account for the async wrapper line
		for _, line := range strings.Split(userCodeStr, "\n") {
			if line != "" {
				out.WriteString("  " + line + "\n")
			}
		}
		out.WriteString("})();\n")
	} else {
		g.genLine = preambleLines
		out.WriteString(userCodeStr)
	}

	// Offset all source map segments by the preamble lines
	if g.SourceMap != nil {
		for i := range g.SourceMap.segments {
			g.SourceMap.segments[i].genLine += preambleLines
		}
	}

	return out.String()
}

// GenerateWithSourceMap generates JavaScript and a source map JSON string.
func (g *Generator) GenerateWithSourceMap(program *ast.Program, sourceFile, outputFile string) (string, string) {
	g.SourceMap = NewSourceMap(sourceFile, outputFile)

	js := g.Generate(program)

	return js, g.SourceMap.ToJSON()
}

// trackLine counts newlines in output and adds source mappings for statements.
func (g *Generator) addStmtMapping(srcLine int) {
	if g.SourceMap != nil && srcLine > 0 {
		g.SourceMap.AddMapping(g.genLine, 0, srcLine-1, 0)
	}
}

func (g *Generator) genStmt(stmt ast.Statement) string {
	prefix := strings.Repeat("  ", g.indent)

	switch s := stmt.(type) {
	case *ast.AssignStatement:
		g.addStmtMapping(s.Line)
		value := g.genExpr(s.Value)
		if g.declared[s.Name] {
			return fmt.Sprintf("%s%s = %s;", prefix, s.Name, value)
		}
		g.declared[s.Name] = true
		return fmt.Sprintf("%slet %s = %s;", prefix, s.Name, value)

	case *ast.SayStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%sconsole.log(%s);", prefix, g.genExpr(s.Value))

	case *ast.IfStatement:
		g.addStmtMapping(s.Line)
		return g.genIf(s, prefix)

	case *ast.ForEachStatement:
		g.addStmtMapping(s.Line)
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf("%sfor (const %s of %s) {\n%s%s}", prefix, s.Variable, g.genExpr(s.Iterable), body, prefix)

	case *ast.WhileStatement:
		g.addStmtMapping(s.Line)
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf("%swhile (%s) {\n%s%s}", prefix, g.genExpr(s.Condition), body, prefix)

	case *ast.FuncDefinition:
		g.addStmtMapping(s.Line)
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		params := strings.Join(s.Params, ", ")
		return fmt.Sprintf("%sfunction %s(%s) {\n%s%s}", prefix, s.Name, params, body, prefix)

	case *ast.ReturnStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%sreturn %s;", prefix, g.genExpr(s.Value))

	case *ast.ExprStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%s%s;", prefix, g.genExpr(s.Expr))

	case *ast.DotAssignStatement:
		return fmt.Sprintf("%s%s.%s = %s;", prefix, s.Object, s.Field, g.genExpr(s.Value))

	case *ast.DescribeStatement:
		var dout strings.Builder
		if s.Extends != "" {
			dout.WriteString(fmt.Sprintf("%sclass %s extends %s {\n", prefix, s.Name, s.Extends))
		} else {
			dout.WriteString(fmt.Sprintf("%sclass %s {\n", prefix, s.Name))
		}
		g.indent++
		innerPrefix := strings.Repeat("  ", g.indent)
		// Constructor
		dout.WriteString(fmt.Sprintf("%sconstructor() {\n", innerPrefix))
		if s.Extends != "" {
			g.indent++
			superPrefix := strings.Repeat("  ", g.indent)
			dout.WriteString(fmt.Sprintf("%ssuper();\n", superPrefix))
			g.indent--
		}
		g.indent++
		propPrefix := strings.Repeat("  ", g.indent)
		for _, prop := range s.Properties {
			dout.WriteString(fmt.Sprintf("%sthis.%s = %s;\n", propPrefix, prop.Name, g.genExpr(prop.Value)))
		}
		g.indent--
		dout.WriteString(fmt.Sprintf("%s}\n", innerPrefix))
		// Methods
		for _, method := range s.Methods {
			params := strings.Join(method.Params, ", ")
			dout.WriteString(fmt.Sprintf("%s%s(%s) {\n", innerPrefix, method.Name, params))
			g.indent++
			for _, stmt := range method.Body {
				dout.WriteString(g.genStmt(stmt))
				dout.WriteString("\n")
			}
			g.indent--
			dout.WriteString(fmt.Sprintf("%s}\n", innerPrefix))
		}
		g.indent--
		dout.WriteString(fmt.Sprintf("%s}", prefix))
		return dout.String()

	case *ast.UseStatement:
		if strings.HasSuffix(s.Path, ".quill") {
			imported, err := os.ReadFile(s.Path)
			if err != nil {
				return fmt.Sprintf("%s// Error: could not import %q", prefix, s.Path)
			}
			l := lexer.New(string(imported))
			tokens, _ := l.Tokenize()
			pr := parser.New(tokens)
			prog, _ := pr.Parse()
			importGen := New()
			importGen.indent = g.indent
			code := importGen.GenerateBody(prog)
			return fmt.Sprintf("%s// imported from %q\n%s", prefix, s.Path, code)
		}
		// NPM package - use require
		varName := strings.ReplaceAll(s.Path, "-", "_")
		varName = strings.ReplaceAll(varName, "/", "_")
		varName = strings.ReplaceAll(varName, "@", "")
		if s.Alias != "" {
			varName = s.Alias
		}
		return fmt.Sprintf("%sconst %s = require(\"%s\");", prefix, varName, s.Path)

	case *ast.TestBlock:
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf(`%s(() => {
%s  try {
%s%s    __test_passed++;
%s    console.log("  \u2713 %s");
%s  } catch(e) {
%s    __test_failed++;
%s    console.log("  \u2717 %s:", e.message);
%s  }
%s})();`, prefix, prefix, prefix, body, prefix, s.Name, prefix, prefix, prefix, s.Name, prefix, prefix)

	case *ast.ExpectStatement:
		exprStr := g.genExpr(s.Expr)
		return fmt.Sprintf(`%sif (!(%s)) throw new Error("Expected %s to be true");`, prefix, exprStr, escapeJS(exprStr))

	case *ast.TryCatchStatement:
		g.indent++
		tryBody := g.genBlock(s.TryBody)
		g.indent--
		g.indent++
		catchBody := g.genBlock(s.CatchBody)
		g.indent--
		errorVar := s.ErrorVar
		if errorVar == "" {
			errorVar = "error"
		}
		return fmt.Sprintf("%stry {\n%s%s} catch (%s) {\n%s%s}", prefix, tryBody, prefix, errorVar, catchBody, prefix)

	case *ast.BreakStatement:
		return fmt.Sprintf("%sbreak;", prefix)

	case *ast.ContinueStatement:
		return fmt.Sprintf("%scontinue;", prefix)

	case *ast.MatchStatement:
		return g.genMatch(s, prefix)

	case *ast.DefineStatement:
		return g.genDefine(s, prefix)

	case *ast.TypedAssignStatement:
		value := g.genExpr(s.Value)
		if g.declared[s.Name] {
			return fmt.Sprintf("%s%s = %s;", prefix, s.Name, value)
		}
		g.declared[s.Name] = true
		return fmt.Sprintf("%slet %s = %s;", prefix, s.Name, value)

	case *ast.FromUseStatement:
		names := strings.Join(s.Names, ", ")
		if strings.HasSuffix(s.Path, ".quill") {
			imported, err := os.ReadFile(s.Path)
			if err != nil {
				return fmt.Sprintf("%s// Error: could not import %q", prefix, s.Path)
			}
			l := lexer.New(string(imported))
			tokens, _ := l.Tokenize()
			pr := parser.New(tokens)
			prog, _ := pr.Parse()
			importGen := New()
			importGen.indent = g.indent
			code := importGen.GenerateBody(prog)
			return fmt.Sprintf("%s// imported from %q\n%s", prefix, s.Path, code)
		}
		return fmt.Sprintf("%sconst { %s } = require(\"%s\");", prefix, names, s.Path)

	case *ast.ComponentStatement:
		return g.genComponent(s, prefix)

	case *ast.MountStatement:
		return g.genMount(s, prefix)

	default:
		return prefix + "/* unknown statement */"
	}
}

func (g *Generator) genIf(s *ast.IfStatement, prefix string) string {
	var out strings.Builder

	g.indent++
	body := g.genBlock(s.Body)
	g.indent--

	out.WriteString(fmt.Sprintf("%sif (%s) {\n%s%s}", prefix, g.genExpr(s.Condition), body, prefix))

	for _, elif := range s.ElseIfs {
		g.indent++
		elifBody := g.genBlock(elif.Body)
		g.indent--
		out.WriteString(fmt.Sprintf(" else if (%s) {\n%s%s}", g.genExpr(elif.Condition), elifBody, prefix))
	}

	if len(s.Else) > 0 {
		g.indent++
		elseBody := g.genBlock(s.Else)
		g.indent--
		out.WriteString(fmt.Sprintf(" else {\n%s%s}", elseBody, prefix))
	}

	return out.String()
}

func (g *Generator) genMatch(s *ast.MatchStatement, prefix string) string {
	var out strings.Builder
	matchVar := "__match_val"
	out.WriteString(fmt.Sprintf("%s{\n", prefix))
	g.indent++
	innerPrefix := strings.Repeat("  ", g.indent)
	out.WriteString(fmt.Sprintf("%sconst %s = %s;\n", innerPrefix, matchVar, g.genExpr(s.Value)))

	for i, c := range s.Cases {
		g.indent++
		body := g.genBlock(c.Body)
		g.indent--

		if c.Pattern == nil {
			// otherwise case
			if i == 0 {
				out.WriteString(fmt.Sprintf("%sif (true) {\n%s%s}", innerPrefix, body, innerPrefix))
			} else {
				out.WriteString(fmt.Sprintf(" else {\n%s%s}", body, innerPrefix))
			}
		} else {
			condition := fmt.Sprintf("(%s === %s)", matchVar, g.genExpr(c.Pattern))
			if c.Guard != nil {
				condition = fmt.Sprintf("(%s === %s && %s)", matchVar, g.genExpr(c.Pattern), g.genExpr(c.Guard))
			}

			if i == 0 {
				out.WriteString(fmt.Sprintf("%sif %s {\n%s%s}", innerPrefix, condition, body, innerPrefix))
			} else {
				out.WriteString(fmt.Sprintf(" else if %s {\n%s%s}", condition, body, innerPrefix))
			}
		}
	}
	out.WriteString("\n")
	g.indent--
	out.WriteString(fmt.Sprintf("%s}", prefix))
	return out.String()
}

func (g *Generator) genDefine(s *ast.DefineStatement, prefix string) string {
	var out strings.Builder

	// Generate as a frozen object with variant constructors
	out.WriteString(fmt.Sprintf("%sconst %s = Object.freeze({\n", prefix, s.Name))
	g.indent++
	innerPrefix := strings.Repeat("  ", g.indent)

	for i, variant := range s.Variants {
		if len(variant.Fields) == 0 {
			// Simple enum variant: Color.Red = { type: "Color", variant: "Red", toString() }
			out.WriteString(fmt.Sprintf("%s%s: Object.freeze({ type: \"%s\", variant: \"%s\", toString() { return \"%s.%s\"; } })", innerPrefix, variant.Name, s.Name, variant.Name, s.Name, variant.Name))
		} else {
			// Algebraic variant with fields: Result.Ok(value) = { type: "Result", variant: "Ok", value }
			params := strings.Join(variant.Fields, ", ")
			fieldAssignments := make([]string, len(variant.Fields))
			for j, field := range variant.Fields {
				fieldAssignments[j] = fmt.Sprintf("%s: %s", field, field)
			}
			out.WriteString(fmt.Sprintf("%s%s: (%s) => Object.freeze({ type: \"%s\", variant: \"%s\", %s, toString() { return \"%s.%s(\" + [%s].join(\", \") + \")\"; } })",
				innerPrefix, variant.Name, params, s.Name, variant.Name, strings.Join(fieldAssignments, ", "), s.Name, variant.Name, params))
		}
		if i < len(s.Variants)-1 {
			out.WriteString(",")
		}
		out.WriteString("\n")
	}

	g.indent--
	out.WriteString(fmt.Sprintf("%s});\n", prefix))

	// Add helper: is<Variant> functions
	for _, variant := range s.Variants {
		out.WriteString(fmt.Sprintf("%sconst is%s = (v) => v && v.variant === \"%s\";\n", prefix, variant.Name, variant.Name))
	}

	return out.String()
}

func (g *Generator) genBlock(stmts []ast.Statement) string {
	var out strings.Builder
	for _, stmt := range stmts {
		code := g.genStmt(stmt)
		out.WriteString(code)
		out.WriteString("\n")
		g.genLine += strings.Count(code, "\n") + 1
	}
	return out.String()
}

func (g *Generator) genExpr(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.StringLiteral:
		if hasInterpolation(e.Value) {
			// Convert {var} to ${var} for JS template literals
			converted := e.Value
			converted = strings.ReplaceAll(converted, "`", "\\`")
			// Convert my.field to this.field inside interpolations
			converted = strings.ReplaceAll(converted, "{my.", "{this.")
			converted = convertInterpolation(converted)
			return "`" + converted + "`"
		}
		// Escape any backticks and return as regular string
		escaped := strings.ReplaceAll(e.Value, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
		return `"` + escaped + `"`

	case *ast.NumberLiteral:
		if e.Value == float64(int64(e.Value)) {
			return fmt.Sprintf("%d", int64(e.Value))
		}
		return fmt.Sprintf("%g", e.Value)

	case *ast.BoolLiteral:
		if e.Value {
			return "true"
		}
		return "false"

	case *ast.Identifier:
		return e.Name

	case *ast.ListLiteral:
		elems := make([]string, len(e.Elements))
		for i, el := range e.Elements {
			elems[i] = g.genExpr(el)
		}
		return "[" + strings.Join(elems, ", ") + "]"

	case *ast.BinaryExpr:
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), e.Operator, g.genExpr(e.Right))

	case *ast.ComparisonExpr:
		if e.Operator == "contains" {
			return fmt.Sprintf("__contains(%s, %s)", g.genExpr(e.Left), g.genExpr(e.Right))
		}
		op := e.Operator
		if op == "==" {
			op = "==="
		}
		if op == "!=" {
			op = "!=="
		}
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), op, g.genExpr(e.Right))

	case *ast.LogicalExpr:
		op := "&&"
		if e.Operator == "or" {
			op = "||"
		}
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), op, g.genExpr(e.Right))

	case *ast.NotExpr:
		return fmt.Sprintf("(!%s)", g.genExpr(e.Operand))

	case *ast.UnaryMinusExpr:
		return fmt.Sprintf("(-%s)", g.genExpr(e.Operand))

	case *ast.CallExpr:
		args := make([]string, len(e.Args))
		for i, a := range e.Args {
			args[i] = g.genExpr(a)
		}
		return fmt.Sprintf("%s(%s)", g.genExpr(e.Function), strings.Join(args, ", "))

	case *ast.DotExpr:
		return fmt.Sprintf("%s.%s", g.genExpr(e.Object), e.Field)

	case *ast.IndexExpr:
		return fmt.Sprintf("%s[%s]", g.genExpr(e.Object), g.genExpr(e.Index))

	case *ast.NewExpr:
		args := make([]string, len(e.Args))
		for i, a := range e.Args {
			args[i] = g.genExpr(a)
		}
		return fmt.Sprintf("new %s(%s)", e.ClassName, strings.Join(args, ", "))

	case *ast.AwaitExpr:
		return fmt.Sprintf("await %s", g.genExpr(e.Expr))

	case *ast.NothingLiteral:
		return "null"

	case *ast.ObjectLiteral:
		if len(e.Keys) == 0 {
			return "{}"
		}
		pairs := make([]string, len(e.Keys))
		for i, key := range e.Keys {
			pairs[i] = fmt.Sprintf("%s: %s", key, g.genExpr(e.Values[i]))
		}
		return "{ " + strings.Join(pairs, ", ") + " }"

	case *ast.LambdaExpr:
		params := strings.Join(e.Params, ", ")
		body := g.genExpr(e.Body)
		if len(e.Params) == 1 {
			return fmt.Sprintf("(%s) => %s", params, body)
		}
		return fmt.Sprintf("(%s) => %s", params, body)

	case *ast.SpreadExpr:
		return fmt.Sprintf("...%s", g.genExpr(e.Expr))

	case *ast.PipeExpr:
		// x | fn  becomes  fn(x)
		// x | fn(a, b)  becomes  fn(x, a, b)
		leftCode := g.genExpr(e.Left)
		switch right := e.Right.(type) {
		case *ast.CallExpr:
			// Insert left as first argument
			args := []string{leftCode}
			for _, a := range right.Args {
				args = append(args, g.genExpr(a))
			}
			return fmt.Sprintf("%s(%s)", g.genExpr(right.Function), strings.Join(args, ", "))
		case *ast.Identifier:
			return fmt.Sprintf("%s(%s)", right.Name, leftCode)
		default:
			return fmt.Sprintf("%s(%s)", g.genExpr(e.Right), leftCode)
		}

	default:
		return "undefined"
	}
}

func (g *Generator) GenerateBody(program *ast.Program) string {
	var out strings.Builder
	for _, stmt := range program.Statements {
		out.WriteString(g.genStmt(stmt))
		out.WriteString("\n")
	}
	return out.String()
}

func escapeJS(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

// convertInterpolation converts {expr} to ${expr} for JS template literals.
// Only converts {identifier} or {expr.field} patterns, not { css } blocks.
func convertInterpolation(s string) string {
	var out strings.Builder
	i := 0
	for i < len(s) {
		if s[i] == '{' {
			// Check if it's already ${
			if i > 0 && s[i-1] == '$' {
				out.WriteByte(s[i])
				i++
				continue
			}
			// Look ahead to see if content looks like an interpolation expression
			// (starts with a letter/underscore, contains only valid identifier chars, dots, parens, etc.)
			j := i + 1
			if j < len(s) && isInterpolationStart(s[j]) {
				// Find the closing brace
				for j < len(s) && s[j] != '}' {
					j++
				}
				if j < len(s) {
					content := s[i+1 : j]
					if isInterpolationExpr(content) {
						out.WriteString("${")
						out.WriteString(content)
						out.WriteByte('}')
						i = j + 1
						continue
					}
				}
			}
			// Not an interpolation — keep the brace as-is but escape for template literal
			out.WriteString("\\{")
			i++
		} else {
			out.WriteByte(s[i])
			i++
		}
	}
	return out.String()
}

// hasInterpolation returns true if the string contains at least one {identifier} interpolation.
func hasInterpolation(s string) bool {
	i := 0
	for i < len(s) {
		if s[i] == '{' {
			j := i + 1
			if j < len(s) && isInterpolationStart(s[j]) {
				for j < len(s) && s[j] != '}' {
					j++
				}
				if j < len(s) {
					content := s[i+1 : j]
					if isInterpolationExpr(content) {
						return true
					}
				}
			}
		}
		i++
	}
	return false
}

// isInterpolationStart returns true if the character can start a Quill interpolation.
func isInterpolationStart(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'
}

// isInterpolationExpr returns true if the string looks like a valid interpolation expression
// (identifier, dot access, function call, etc.) rather than CSS or other content.
func isInterpolationExpr(s string) bool {
	if len(s) == 0 {
		return false
	}
	// Must start with a letter or underscore
	if !isInterpolationStart(s[0]) {
		return false
	}
	// Should only contain valid identifier characters, dots, parens, commas, spaces
	for _, c := range s {
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') ||
			c == '_' || c == '.' || c == '(' || c == ')' || c == ',' || c == ' ') {
			return false
		}
	}
	return true
}

// hasComponents checks if the program contains any ComponentStatement nodes.
func (g *Generator) hasComponents(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		if _, ok := stmt.(*ast.ComponentStatement); ok {
			return true
		}
		if _, ok := stmt.(*ast.MountStatement); ok {
			return true
		}
	}
	return false
}
