package codegen

import (
	"fmt"
	"os"
	"quill/ast"
	"quill/lexer"
	"quill/parser"
	"quill/stdlib"
	"strings"
)

type Generator struct {
	indent               int
	declared             map[string]bool
	browser              bool
	SourceMap            *SourceMap
	genLine              int      // current generated line number (0-based)
	needsResultRuntime   bool     // inject Result type runtime helpers
	taggedTemplatesUsed  []string // track which tagged template tags are used
}

func New() *Generator {
	return &Generator{
		declared: make(map[string]bool),
	}
}

func NewBrowser() *Generator {
	return &Generator{
		declared: make(map[string]bool),
		browser:  true,
	}
}

func (g *Generator) Generate(program *ast.Program) string {
	var out strings.Builder

	// Generate user code first to check for await
	var userCode strings.Builder
	for _, stmt := range program.Statements {
		userCode.WriteString(g.genStmt(stmt))
		userCode.WriteString("\n")
	}
	userCodeStr := userCode.String()

	out.WriteString("// Generated by Quill\n")
	if g.browser {
		out.WriteString(stdlib.BrowserRuntime)
	} else {
		out.WriteString(stdlib.Runtime)
	}
	out.WriteString("\n")

	// Include framework runtime if any component statements are present
	if g.hasComponents(program) {
		out.WriteString(stdlib.FrameworkRuntime)
		out.WriteString("\n")
	}

	// Include channel runtime if concurrency features are used
	if g.hasConcurrency(program) {
		out.WriteString(channelRuntime)
		out.WriteString("\n")
	}

	// Include iterator runtime if generator/iterator features are used
	if g.hasGenerators(program) || g.needsIteratorRuntime(userCodeStr) {
		out.WriteString(stdlib.GetIteratorRuntime())
		out.WriteString("\n")
	}

	// Include stdlib runtimes based on usage detection in user code
	if g.usesIdentifier(userCodeStr, "Auth") {
		out.WriteString(stdlib.GetAuthRuntime())
		out.WriteString("\n")
	}
	if g.usesIdentifier(userCodeStr, "DB") {
		out.WriteString(stdlib.GetOrmRuntime())
		out.WriteString("\n")
	}
	if g.usesIdentifier(userCodeStr, "Validate") {
		out.WriteString(stdlib.GetValidateRuntime())
		out.WriteString("\n")
	}
	if g.usesIdentifier(userCodeStr, "Log") {
		out.WriteString(stdlib.GetLoggingRuntime())
		out.WriteString("\n")
	}

	// Include Discord bot runtime if discord-related code is detected
	if g.usesIdentifier(userCodeStr, "createBot") {
		out.WriteString(stdlib.DiscordRuntime)
		out.WriteString("\n")
	}

	// Include Result runtime if error propagation features are used
	if g.needsResultRuntime || strings.Contains(userCodeStr, "Success(") || strings.Contains(userCodeStr, "__propagate(") || strings.Contains(userCodeStr, "__tryResult(") {
		out.WriteString(resultRuntime)
		out.WriteString("\n")
	}

	// Include tagged template runtime functions
	g.injectTagRuntimes(&out)

	// Include decorator runtime if decorators are used
	if g.hasDecorators(program) {
		out.WriteString(decoratorRuntime)
		out.WriteString("\n")
	}

	// Count the preamble lines so source map offsets are correct
	preamble := out.String()
	preambleLines := strings.Count(preamble, "\n")

	needsAsync := strings.Contains(userCodeStr, "await ") || g.hasAsyncConstructs(program)
	if needsAsync {
		g.genLine = preambleLines // (async () => {
		out.WriteString("(async () => {\n")
		preambleLines++ // account for the async wrapper line
		for _, line := range strings.Split(userCodeStr, "\n") {
			if line != "" {
				out.WriteString("  " + line + "\n")
			}
		}
		out.WriteString("})();\n")
	} else {
		g.genLine = preambleLines
		out.WriteString(userCodeStr)
	}

	// Offset all source map segments by the preamble lines
	if g.SourceMap != nil {
		for i := range g.SourceMap.segments {
			g.SourceMap.segments[i].genLine += preambleLines
		}
	}

	return out.String()
}

// GenerateWithSourceMap generates JavaScript and a source map JSON string.
func (g *Generator) GenerateWithSourceMap(program *ast.Program, sourceFile, outputFile string) (string, string) {
	g.SourceMap = NewSourceMap(sourceFile, outputFile)

	js := g.Generate(program)

	return js, g.SourceMap.ToJSON()
}

// trackLine counts newlines in output and adds source mappings for statements.
func (g *Generator) addStmtMapping(srcLine int) {
	if g.SourceMap != nil && srcLine > 0 {
		g.SourceMap.AddMapping(g.genLine, 0, srcLine-1, 0)
	}
}

func (g *Generator) genStmt(stmt ast.Statement) string {
	prefix := strings.Repeat("  ", g.indent)

	switch s := stmt.(type) {
	case *ast.AssignStatement:
		g.addStmtMapping(s.Line)
		value := g.genExpr(s.Value)
		if g.declared[s.Name] {
			return fmt.Sprintf("%s%s = %s;", prefix, s.Name, value)
		}
		g.declared[s.Name] = true
		return fmt.Sprintf("%slet %s = %s;", prefix, s.Name, value)

	case *ast.SayStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%sconsole.log(%s);", prefix, g.genExpr(s.Value))

	case *ast.IfStatement:
		g.addStmtMapping(s.Line)
		return g.genIf(s, prefix)

	case *ast.ForEachStatement:
		g.addStmtMapping(s.Line)
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		varPart := s.Variable
		if s.DestructurePattern != nil {
			varPart = g.genPattern(s.DestructurePattern)
		}
		awaitPart := ""
		if s.IsAsync {
			awaitPart = "await "
		}
		return fmt.Sprintf("%sfor %s(const %s of %s) {\n%s%s}", prefix, awaitPart, varPart, g.genExpr(s.Iterable), body, prefix)

	case *ast.WhileStatement:
		g.addStmtMapping(s.Line)
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf("%swhile (%s) {\n%s%s}", prefix, g.genExpr(s.Condition), body, prefix)

	case *ast.FuncDefinition:
		g.addStmtMapping(s.Line)
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		params := strings.Join(s.Params, ", ")
		if g.bodyContainsYield(s.Body) {
			return fmt.Sprintf("%sfunction* %s(%s) {\n%s%s}", prefix, s.Name, params, body, prefix)
		}
		return fmt.Sprintf("%sfunction %s(%s) {\n%s%s}", prefix, s.Name, params, body, prefix)

	case *ast.YieldStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%syield %s;", prefix, g.genExpr(s.Value))

	case *ast.LoopStatement:
		g.addStmtMapping(s.Line)
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf("%swhile (true) {\n%s%s}", prefix, body, prefix)

	case *ast.ReturnStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%sreturn %s;", prefix, g.genExpr(s.Value))

	case *ast.ExprStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%s%s;", prefix, g.genExpr(s.Expr))

	case *ast.DotAssignStatement:
		return fmt.Sprintf("%s%s.%s = %s;", prefix, s.Object, s.Field, g.genExpr(s.Value))

	case *ast.DescribeStatement:
		var dout strings.Builder
		if s.Extends != "" {
			dout.WriteString(fmt.Sprintf("%sclass %s extends %s {\n", prefix, s.Name, s.Extends))
		} else {
			dout.WriteString(fmt.Sprintf("%sclass %s {\n", prefix, s.Name))
		}
		g.indent++
		innerPrefix := strings.Repeat("  ", g.indent)

		// Emit private field declarations (JS requires # fields to be declared)
		for i, prop := range s.Properties {
			vis := ""
			if i < len(s.PropertyVisibilities) {
				vis = s.PropertyVisibilities[i]
			}
			if vis == "private" {
				dout.WriteString(fmt.Sprintf("%s#%s;\n", innerPrefix, prop.Name))
			}
		}

		// Constructor
		dout.WriteString(fmt.Sprintf("%sconstructor() {\n", innerPrefix))
		if s.Extends != "" {
			g.indent++
			superPrefix := strings.Repeat("  ", g.indent)
			dout.WriteString(fmt.Sprintf("%ssuper();\n", superPrefix))
			g.indent--
		}
		g.indent++
		propPrefix := strings.Repeat("  ", g.indent)
		for i, prop := range s.Properties {
			vis := ""
			if i < len(s.PropertyVisibilities) {
				vis = s.PropertyVisibilities[i]
			}
			if vis == "private" {
				dout.WriteString(fmt.Sprintf("%sthis.#%s = %s;\n", propPrefix, prop.Name, g.genExpr(prop.Value)))
			} else {
				dout.WriteString(fmt.Sprintf("%sthis.%s = %s;\n", propPrefix, prop.Name, g.genExpr(prop.Value)))
			}
		}
		g.indent--
		dout.WriteString(fmt.Sprintf("%s}\n", innerPrefix))
		// Methods
		for i, method := range s.Methods {
			vis := ""
			if i < len(s.MethodVisibilities) {
				vis = s.MethodVisibilities[i]
			}
			params := strings.Join(method.Params, ", ")
			if vis == "private" {
				dout.WriteString(fmt.Sprintf("%s#%s(%s) {\n", innerPrefix, method.Name, params))
			} else {
				dout.WriteString(fmt.Sprintf("%s%s(%s) {\n", innerPrefix, method.Name, params))
			}
			g.indent++
			for _, stmt := range method.Body {
				dout.WriteString(g.genStmt(stmt))
				dout.WriteString("\n")
			}
			g.indent--
			dout.WriteString(fmt.Sprintf("%s}\n", innerPrefix))
		}
		g.indent--
		dout.WriteString(fmt.Sprintf("%s}", prefix))
		return dout.String()

	case *ast.UseStatement:
		if strings.HasSuffix(s.Path, ".quill") {
			imported, err := os.ReadFile(s.Path)
			if err != nil {
				return fmt.Sprintf("%s// Error: could not import %q", prefix, s.Path)
			}
			l := lexer.New(string(imported))
			tokens, _ := l.Tokenize()
			pr := parser.New(tokens)
			prog, _ := pr.Parse()
			importGen := New()
			importGen.indent = g.indent
			code := importGen.GenerateBody(prog)
			return fmt.Sprintf("%s// imported from %q\n%s", prefix, s.Path, code)
		}
		// NPM package - use require
		varName := strings.ReplaceAll(s.Path, "-", "_")
		varName = strings.ReplaceAll(varName, "/", "_")
		varName = strings.ReplaceAll(varName, "@", "")
		if s.Alias != "" {
			varName = s.Alias
		}
		return fmt.Sprintf("%sconst %s = require(\"%s\");", prefix, varName, s.Path)

	case *ast.TestBlock:
		g.indent++
		body := g.genBlock(s.Body)
		g.indent--
		return fmt.Sprintf(`%s(() => {
%s  try {
%s%s    __test_passed++;
%s    console.log("  \u2713 %s");
%s  } catch(e) {
%s    __test_failed++;
%s    console.log("  \u2717 %s:", e.message);
%s  }
%s})();`, prefix, prefix, prefix, body, prefix, s.Name, prefix, prefix, prefix, s.Name, prefix, prefix)

	case *ast.MockStatement:
		var mout strings.Builder
		mout.WriteString(fmt.Sprintf("%sconst __mock_%s_calls = [];\n", prefix, s.FuncName))
		mout.WriteString(fmt.Sprintf("%sconst __original_%s = typeof %s !== 'undefined' ? %s : undefined;\n", prefix, s.FuncName, s.FuncName, s.FuncName))
		params := strings.Join(s.Params, ", ")
		mout.WriteString(fmt.Sprintf("%svar %s = function(%s) {\n", prefix, s.FuncName, params))
		args := s.Params
		argsArray := "[]"
		if len(args) > 0 {
			argsArray = "[" + strings.Join(args, ", ") + "]"
		}
		mout.WriteString(fmt.Sprintf("%s  __mock_%s_calls.push({args: %s});\n", prefix, s.FuncName, argsArray))
		g.indent += 2
		for _, stmt := range s.Body {
			mout.WriteString(g.genStmt(stmt))
			mout.WriteString("\n")
		}
		g.indent -= 2
		mout.WriteString(fmt.Sprintf("%s};\n", prefix))
		return mout.String()

	case *ast.ExpectStatement:
		if ma, ok := s.Expr.(*ast.MockAssertionExpr); ok {
			return fmt.Sprintf(`%sif (__mock_%s_calls.length !== %d) throw new Error("Expected %s to be called %d time(s), was called " + __mock_%s_calls.length + " time(s)");`,
				prefix, ma.FuncName, ma.Count, ma.FuncName, ma.Count, ma.FuncName)
		}
		exprStr := g.genExpr(s.Expr)
		return fmt.Sprintf(`%sif (!(%s)) throw new Error("Expected %s to be true");`, prefix, exprStr, escapeJS(exprStr))

	case *ast.TryCatchStatement:
		g.indent++
		tryBody := g.genBlock(s.TryBody)
		g.indent--
		g.indent++
		catchBody := g.genBlock(s.CatchBody)
		g.indent--
		errorVar := s.ErrorVar
		if errorVar == "" {
			errorVar = "error"
		}
		return fmt.Sprintf("%stry {\n%s%s} catch (%s) {\n%s%s}", prefix, tryBody, prefix, errorVar, catchBody, prefix)

	case *ast.BreakStatement:
		return fmt.Sprintf("%sbreak;", prefix)

	case *ast.ContinueStatement:
		return fmt.Sprintf("%scontinue;", prefix)

	case *ast.MatchStatement:
		return g.genMatch(s, prefix)

	case *ast.DefineStatement:
		return g.genDefine(s, prefix)

	case *ast.TypedAssignStatement:
		value := g.genExpr(s.Value)
		if g.declared[s.Name] {
			return fmt.Sprintf("%s%s = %s;", prefix, s.Name, value)
		}
		g.declared[s.Name] = true
		return fmt.Sprintf("%slet %s = %s;", prefix, s.Name, value)

	case *ast.FromUseStatement:
		names := strings.Join(s.Names, ", ")
		if strings.HasSuffix(s.Path, ".quill") {
			imported, err := os.ReadFile(s.Path)
			if err != nil {
				return fmt.Sprintf("%s// Error: could not import %q", prefix, s.Path)
			}
			l := lexer.New(string(imported))
			tokens, _ := l.Tokenize()
			pr := parser.New(tokens)
			prog, _ := pr.Parse()
			importGen := New()
			importGen.indent = g.indent
			code := importGen.GenerateBody(prog)
			return fmt.Sprintf("%s// imported from %q\n%s", prefix, s.Path, code)
		}
		return fmt.Sprintf("%sconst { %s } = require(\"%s\");", prefix, names, s.Path)

	case *ast.ComponentStatement:
		return g.genComponent(s, prefix)

	case *ast.MountStatement:
		return g.genMount(s, prefix)

	case *ast.CancelStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%s__abort_%s.abort();", prefix, s.Target)

	case *ast.SpawnStatement:
		g.addStmtMapping(s.Line)
		return g.genSpawn(s, prefix)

	case *ast.ParallelBlock:
		g.addStmtMapping(s.Line)
		return g.genParallel(s, prefix)

	case *ast.RaceBlock:
		g.addStmtMapping(s.Line)
		return g.genRaceBlock(s, prefix)

	case *ast.ChannelStatement:
		g.addStmtMapping(s.Line)
		return g.genChannelStmt(s, prefix)

	case *ast.SendStatement:
		g.addStmtMapping(s.Line)
		return fmt.Sprintf("%sawait %s.send(%s);", prefix, s.Channel, g.genExpr(s.Value))

	case *ast.SelectStatement:
		g.addStmtMapping(s.Line)
		return g.genSelectStmt(s, prefix)

	case *ast.TraitDeclaration:
		return g.genTrait(s, prefix)

	case *ast.DestructureStatement:
		return g.genDestructure(s, prefix)

	case *ast.RespondStatement:
		g.addStmtMapping(s.Line)
		statusCode := s.StatusCode
		if statusCode == 0 {
			statusCode = 200
		}
		return fmt.Sprintf("%sres.writeHead(%d, {'Content-Type': 'application/json'}); res.end(JSON.stringify(%s));", prefix, statusCode, g.genExpr(s.Value))

	case *ast.ServerBlockStatement:
		return prefix + "/* server block — use 'quill run' for full-stack mode */"

	case *ast.DatabaseBlockStatement:
		return prefix + "/* database block — use 'quill run' for full-stack mode */"

	case *ast.AuthBlockStatement:
		return prefix + "/* auth block — use 'quill run' for full-stack mode */"

	case *ast.TypeAliasStatement:
		return g.genTypeAlias(s, prefix)

	case *ast.DecoratedFuncDefinition:
		return g.genDecoratedFunc(s, prefix)

	case *ast.DecoratedRouteDefinition:
		return g.genDecoratedRoute(s, prefix)

	case *ast.BroadcastStatement:
		return fmt.Sprintf("%sfor (const __c of __ws_clients) { if (__c !== client && __c.readyState === 1) { __c.send(%s); } }", prefix, g.genExpr(s.Value))

	case *ast.WebSocketBlock:
		return g.genWebSocket(s, prefix)

	case *ast.OnStatement:
		var out strings.Builder
		params := strings.Join(s.Params, ", ")
		out.WriteString(fmt.Sprintf("%s%s.on(\"%s\", ", prefix, g.genExpr(s.Object), s.Event))
		if len(s.Params) > 0 {
			out.WriteString(fmt.Sprintf("(%s) => {\n", params))
		} else {
			out.WriteString("() => {\n")
		}
		g.indent++
		out.WriteString(g.genBlock(s.Body))
		g.indent--
		out.WriteString(fmt.Sprintf("%s});", prefix))
		return out.String()

	default:
		return prefix + "/* unknown statement */"
	}
}

func (g *Generator) genIf(s *ast.IfStatement, prefix string) string {
	var out strings.Builder

	g.indent++
	body := g.genBlock(s.Body)
	g.indent--

	out.WriteString(fmt.Sprintf("%sif (%s) {\n%s%s}", prefix, g.genExpr(s.Condition), body, prefix))

	for _, elif := range s.ElseIfs {
		g.indent++
		elifBody := g.genBlock(elif.Body)
		g.indent--
		out.WriteString(fmt.Sprintf(" else if (%s) {\n%s%s}", g.genExpr(elif.Condition), elifBody, prefix))
	}

	if len(s.Else) > 0 {
		g.indent++
		elseBody := g.genBlock(s.Else)
		g.indent--
		out.WriteString(fmt.Sprintf(" else {\n%s%s}", elseBody, prefix))
	}

	return out.String()
}

func (g *Generator) genMatch(s *ast.MatchStatement, prefix string) string {
	var out strings.Builder
	matchVar := "__match_val"
	out.WriteString(fmt.Sprintf("%s{\n", prefix))
	g.indent++
	innerPrefix := strings.Repeat("  ", g.indent)
	out.WriteString(fmt.Sprintf("%sconst %s = %s;\n", innerPrefix, matchVar, g.genExpr(s.Value)))

	for i, c := range s.Cases {
		// Build body with possible binding prefix
		var bodyStr string
		if c.TypePattern != "" && c.Binding != "" {
			// Inject binding variable at the top of the body
			g.indent++
			bindPrefix := strings.Repeat("  ", g.indent)
			bodyStr = fmt.Sprintf("%slet %s = %s;\n", bindPrefix, c.Binding, matchVar)
			bodyStr += g.genBlock(c.Body)
			g.indent--
		} else {
			g.indent++
			bodyStr = g.genBlock(c.Body)
			g.indent--
		}

		if c.TypePattern != "" {
			// Type-based pattern matching
			condition := g.genTypeCondition(c.TypePattern, matchVar)
			if c.Guard != nil {
				condition = fmt.Sprintf("(%s && %s)", condition, g.genExpr(c.Guard))
			}
			if i == 0 {
				out.WriteString(fmt.Sprintf("%sif %s {\n%s%s}", innerPrefix, condition, bodyStr, innerPrefix))
			} else {
				out.WriteString(fmt.Sprintf(" else if %s {\n%s%s}", condition, bodyStr, innerPrefix))
			}
		} else if objPat, ok := c.Pattern.(*ast.ObjectMatchPattern); ok {
			// Object destructuring pattern
			var conditions []string
			var bindings []string
			for _, f := range objPat.Fields {
				if f.Value != nil {
					conditions = append(conditions, fmt.Sprintf("%s.%s === %s", matchVar, f.Key, g.genExpr(f.Value)))
				} else {
					// Just bind the field
					bindings = append(bindings, f.Key)
				}
			}
			condition := "true"
			if len(conditions) > 0 {
				condition = strings.Join(conditions, " && ")
			}
			if c.Guard != nil {
				condition = fmt.Sprintf("(%s && %s)", condition, g.genExpr(c.Guard))
			}

			// Inject bindings at the top of the body
			g.indent++
			bindPrefix := strings.Repeat("  ", g.indent)
			var bindStr string
			for _, b := range bindings {
				bindStr += fmt.Sprintf("%sconst %s = %s.%s;\n", bindPrefix, b, matchVar, b)
			}
			bodyStr = bindStr + bodyStr
			g.indent--

			if i == 0 {
				out.WriteString(fmt.Sprintf("%sif (%s) {\n%s%s}", innerPrefix, condition, bodyStr, innerPrefix))
			} else {
				out.WriteString(fmt.Sprintf(" else if (%s) {\n%s%s}", condition, bodyStr, innerPrefix))
			}
		} else if c.Pattern == nil {
			// otherwise case
			if i == 0 {
				out.WriteString(fmt.Sprintf("%sif (true) {\n%s%s}", innerPrefix, bodyStr, innerPrefix))
			} else {
				out.WriteString(fmt.Sprintf(" else {\n%s%s}", bodyStr, innerPrefix))
			}
		} else {
			// Value-based pattern
			condition := fmt.Sprintf("(%s === %s)", matchVar, g.genExpr(c.Pattern))
			if c.Guard != nil {
				condition = fmt.Sprintf("(%s === %s && %s)", matchVar, g.genExpr(c.Pattern), g.genExpr(c.Guard))
			}

			if i == 0 {
				out.WriteString(fmt.Sprintf("%sif %s {\n%s%s}", innerPrefix, condition, bodyStr, innerPrefix))
			} else {
				out.WriteString(fmt.Sprintf(" else if %s {\n%s%s}", condition, bodyStr, innerPrefix))
			}
		}
	}
	out.WriteString("\n")
	g.indent--
	out.WriteString(fmt.Sprintf("%s}", prefix))
	return out.String()
}

func (g *Generator) genDefine(s *ast.DefineStatement, prefix string) string {
	var out strings.Builder

	// Check if any variant has an associated value (enum with values + methods)
	hasValues := false
	for _, v := range s.Variants {
		if v.Value != nil {
			hasValues = true
			break
		}
	}

	if hasValues && len(s.Methods) > 0 {
		// Generate class-based enum with methods
		enumClassName := s.Name + "Enum"
		out.WriteString(fmt.Sprintf("%sconst %s = (() => {\n", prefix, s.Name))
		g.indent++
		ip := strings.Repeat("  ", g.indent)
		out.WriteString(fmt.Sprintf("%sclass %s {\n", ip, enumClassName))
		g.indent++
		ip2 := strings.Repeat("  ", g.indent)
		out.WriteString(fmt.Sprintf("%sconstructor(name, value) { this.name = name; this.value = value; Object.freeze(this); }\n", ip2))
		for _, method := range s.Methods {
			params := strings.Join(method.Params, ", ")
			out.WriteString(fmt.Sprintf("%s%s(%s) {\n", ip2, method.Name, params))
			g.indent++
			for _, stmt := range method.Body {
				out.WriteString(g.genStmt(stmt))
				out.WriteString("\n")
			}
			g.indent--
			out.WriteString(fmt.Sprintf("%s}\n", ip2))
		}
		g.indent--
		out.WriteString(fmt.Sprintf("%s}\n", ip))
		out.WriteString(fmt.Sprintf("%sreturn Object.freeze({\n", ip))
		g.indent++
		ip3 := strings.Repeat("  ", g.indent)
		for i, variant := range s.Variants {
			valStr := "undefined"
			if variant.Value != nil {
				valStr = g.genExpr(variant.Value)
			}
			out.WriteString(fmt.Sprintf("%s%s: new %s(\"%s\", %s)", ip3, variant.Name, enumClassName, variant.Name, valStr))
			if i < len(s.Variants)-1 {
				out.WriteString(",")
			}
			out.WriteString("\n")
		}
		g.indent--
		out.WriteString(fmt.Sprintf("%s});\n", ip))
		g.indent--
		out.WriteString(fmt.Sprintf("%s})();\n", prefix))
	} else if hasValues {
		// Enum with values but no methods
		out.WriteString(fmt.Sprintf("%sconst %s = Object.freeze({\n", prefix, s.Name))
		g.indent++
		innerPrefix := strings.Repeat("  ", g.indent)
		for i, variant := range s.Variants {
			valStr := "undefined"
			if variant.Value != nil {
				valStr = g.genExpr(variant.Value)
			}
			out.WriteString(fmt.Sprintf("%s%s: Object.freeze({ type: \"%s\", variant: \"%s\", name: \"%s\", value: %s, toString() { return \"%s.%s\"; } })",
				innerPrefix, variant.Name, s.Name, variant.Name, variant.Name, valStr, s.Name, variant.Name))
			if i < len(s.Variants)-1 {
				out.WriteString(",")
			}
			out.WriteString("\n")
		}
		g.indent--
		out.WriteString(fmt.Sprintf("%s});\n", prefix))
	} else {
		// Original behavior: frozen object with variant constructors
		out.WriteString(fmt.Sprintf("%sconst %s = Object.freeze({\n", prefix, s.Name))
		g.indent++
		innerPrefix := strings.Repeat("  ", g.indent)

		for i, variant := range s.Variants {
			if len(variant.Fields) == 0 {
				out.WriteString(fmt.Sprintf("%s%s: Object.freeze({ type: \"%s\", variant: \"%s\", toString() { return \"%s.%s\"; } })", innerPrefix, variant.Name, s.Name, variant.Name, s.Name, variant.Name))
			} else {
				params := strings.Join(variant.Fields, ", ")
				fieldAssignments := make([]string, len(variant.Fields))
				for j, field := range variant.Fields {
					fieldAssignments[j] = fmt.Sprintf("%s: %s", field, field)
				}
				out.WriteString(fmt.Sprintf("%s%s: (%s) => Object.freeze({ type: \"%s\", variant: \"%s\", %s, toString() { return \"%s.%s(\" + [%s].join(\", \") + \")\"; } })",
					innerPrefix, variant.Name, params, s.Name, variant.Name, strings.Join(fieldAssignments, ", "), s.Name, variant.Name, params))
			}
			if i < len(s.Variants)-1 {
				out.WriteString(",")
			}
			out.WriteString("\n")
		}

		g.indent--
		out.WriteString(fmt.Sprintf("%s});\n", prefix))
	}

	// Add helper: is<Variant> functions
	for _, variant := range s.Variants {
		out.WriteString(fmt.Sprintf("%sconst is%s = (v) => v && v.variant === \"%s\";\n", prefix, variant.Name, variant.Name))
	}

	return out.String()
}

func (g *Generator) genBlock(stmts []ast.Statement) string {
	var out strings.Builder
	for _, stmt := range stmts {
		code := g.genStmt(stmt)
		out.WriteString(code)
		out.WriteString("\n")
		g.genLine += strings.Count(code, "\n") + 1
	}
	return out.String()
}

func (g *Generator) genExpr(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.StringLiteral:
		if hasInterpolation(e.Value) {
			// Convert {var} to ${var} for JS template literals
			converted := e.Value
			converted = strings.ReplaceAll(converted, "`", "\\`")
			// Convert my.field to this.field inside interpolations
			converted = strings.ReplaceAll(converted, "{my.", "{this.")
			converted = convertInterpolation(converted)
			return "`" + converted + "`"
		}
		// Escape any backticks and return as regular string
		escaped := strings.ReplaceAll(e.Value, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
		return `"` + escaped + `"`

	case *ast.NumberLiteral:
		if e.Value == float64(int64(e.Value)) {
			return fmt.Sprintf("%d", int64(e.Value))
		}
		return fmt.Sprintf("%g", e.Value)

	case *ast.BoolLiteral:
		if e.Value {
			return "true"
		}
		return "false"

	case *ast.Identifier:
		return e.Name

	case *ast.ListLiteral:
		elems := make([]string, len(e.Elements))
		for i, el := range e.Elements {
			elems[i] = g.genExpr(el)
		}
		return "[" + strings.Join(elems, ", ") + "]"

	case *ast.BinaryExpr:
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), e.Operator, g.genExpr(e.Right))

	case *ast.ComparisonExpr:
		if e.Operator == "contains" {
			return fmt.Sprintf("__contains(%s, %s)", g.genExpr(e.Left), g.genExpr(e.Right))
		}
		op := e.Operator
		if op == "==" {
			op = "==="
		}
		if op == "!=" {
			op = "!=="
		}
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), op, g.genExpr(e.Right))

	case *ast.LogicalExpr:
		op := "&&"
		if e.Operator == "or" {
			op = "||"
		}
		return fmt.Sprintf("(%s %s %s)", g.genExpr(e.Left), op, g.genExpr(e.Right))

	case *ast.NotExpr:
		return fmt.Sprintf("(!%s)", g.genExpr(e.Operand))

	case *ast.UnaryMinusExpr:
		return fmt.Sprintf("(-%s)", g.genExpr(e.Operand))

	case *ast.CallExpr:
		args := make([]string, len(e.Args))
		for i, a := range e.Args {
			args[i] = g.genExpr(a)
		}
		return fmt.Sprintf("%s(%s)", g.genExpr(e.Function), strings.Join(args, ", "))

	case *ast.DotExpr:
		return fmt.Sprintf("%s.%s", g.genExpr(e.Object), e.Field)

	case *ast.IndexExpr:
		return fmt.Sprintf("%s[%s]", g.genExpr(e.Object), g.genExpr(e.Index))

	case *ast.NewExpr:
		args := make([]string, len(e.Args))
		for i, a := range e.Args {
			args[i] = g.genExpr(a)
		}
		return fmt.Sprintf("new %s(%s)", e.ClassName, strings.Join(args, ", "))

	case *ast.AwaitExpr:
		return fmt.Sprintf("await %s", g.genExpr(e.Expr))

	case *ast.AwaitExpression:
		// "await all" or "await first" — handled contextually by parallel/race
		if ident, ok := e.Target.(*ast.Identifier); ok {
			if ident.Name == "all" || ident.Name == "first" {
				return fmt.Sprintf("await %s", ident.Name)
			}
		}
		return fmt.Sprintf("await __task_%s", g.genExpr(e.Target))

	case *ast.ReceiveExpression:
		return fmt.Sprintf("await %s.receive()", e.Channel)

	case *ast.NothingLiteral:
		return "null"

	case *ast.ObjectLiteral:
		if len(e.Keys) == 0 && len(e.ComputedProperties) == 0 {
			return "{}"
		}
		var pairs []string
		for i, key := range e.Keys {
			pairs = append(pairs, fmt.Sprintf("%s: %s", key, g.genExpr(e.Values[i])))
		}
		for _, cp := range e.ComputedProperties {
			pairs = append(pairs, fmt.Sprintf("[%s]: %s", g.genExpr(cp.KeyExpr), g.genExpr(cp.Value)))
		}
		return "{ " + strings.Join(pairs, ", ") + " }"

	case *ast.LambdaExpr:
		params := strings.Join(e.Params, ", ")
		body := g.genExpr(e.Body)
		if len(e.Params) == 1 {
			return fmt.Sprintf("(%s) => %s", params, body)
		}
		return fmt.Sprintf("(%s) => %s", params, body)

	case *ast.SpreadExpr:
		return fmt.Sprintf("...%s", g.genExpr(e.Expr))

	case *ast.TypeCheckExpr:
		exprCode := g.genExpr(e.Expr)
		switch e.TypeName {
		case "text":
			return fmt.Sprintf("(typeof %s === \"string\")", exprCode)
		case "number":
			return fmt.Sprintf("(typeof %s === \"number\")", exprCode)
		case "boolean":
			return fmt.Sprintf("(typeof %s === \"boolean\")", exprCode)
		case "nothing":
			return fmt.Sprintf("(%s === null || %s === undefined)", exprCode, exprCode)
		default:
			return fmt.Sprintf("(typeof %s === \"%s\")", exprCode, e.TypeName)
		}

	case *ast.PropagateExpr:
		inner := g.genExpr(e.Expr)
		g.needsResultRuntime = true
		return fmt.Sprintf("__propagate(%s)", inner)

	case *ast.TryExpression:
		inner := g.genExpr(e.Expr)
		g.needsResultRuntime = true
		return fmt.Sprintf("__tryResult(%s)", inner)

	case *ast.ObjectMatchPattern:
		// This should not be reached directly in genExpr, handled in genMatch
		return "/* object match pattern */"

	case *ast.PipeExpr:
		// x | fn  becomes  fn(x)
		// x | fn(a, b)  becomes  fn(x, a, b)
		leftCode := g.genExpr(e.Left)
		switch right := e.Right.(type) {
		case *ast.CallExpr:
			// Insert left as first argument
			args := []string{leftCode}
			for _, a := range right.Args {
				args = append(args, g.genExpr(a))
			}
			return fmt.Sprintf("%s(%s)", g.genExpr(right.Function), strings.Join(args, ", "))
		case *ast.Identifier:
			return fmt.Sprintf("%s(%s)", right.Name, leftCode)
		default:
			return fmt.Sprintf("%s(%s)", g.genExpr(e.Right), leftCode)
		}

	case *ast.TaggedTemplateExpr:
		// Convert Quill {x} to JS ${x} in the template
		converted := e.Template
		converted = strings.ReplaceAll(converted, "{", "${")
		g.taggedTemplatesUsed = append(g.taggedTemplatesUsed, e.Tag)
		return fmt.Sprintf("%s`%s`", e.Tag, converted)

	case *ast.MockAssertionExpr:
		// This is handled at the ExpectStatement level, but provide a fallback
		return fmt.Sprintf("__mock_%s_calls.length === %d", e.FuncName, e.Count)

	default:
		return "undefined"
	}
}

// --- Tagged template runtimes ---

func (g *Generator) injectTagRuntimes(out *strings.Builder) {
	injected := map[string]bool{}
	for _, tag := range g.taggedTemplatesUsed {
		if injected[tag] {
			continue
		}
		injected[tag] = true
		switch tag {
		case "query":
			out.WriteString(`function query(strings, ...values) {
  let text = strings[0];
  const params = [];
  for (let i = 0; i < values.length; i++) {
    params.push(values[i]);
    text += '$' + (i + 1) + strings[i + 1];
  }
  return { text, values: params };
}
`)
		case "html":
			out.WriteString(`function html(strings, ...values) {
  return strings.reduce((r, s, i) => r + (values[i-1] || '') + s);
}
`)
		case "css":
			out.WriteString(`function css(strings, ...values) {
  return strings.reduce((r, s, i) => r + (values[i-1] || '') + s);
}
`)
		}
	}
}

// --- Trait code generation ---

func (g *Generator) genTrait(s *ast.TraitDeclaration, prefix string) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("%s// Trait: %s\n", prefix, s.Name))
	for _, m := range s.Methods {
		params := make([]string, len(m.Params))
		for i, p := range m.Params {
			if p.TypeHint != "" {
				params[i] = fmt.Sprintf("%s: %s", p.Name, p.TypeHint)
			} else {
				params[i] = p.Name
			}
		}
		ret := ""
		if m.ReturnType != "" {
			ret = " -> " + m.ReturnType
		}
		out.WriteString(fmt.Sprintf("%s//   %s(%s)%s\n", prefix, m.Name, strings.Join(params, ", "), ret))
	}
	// Generate runtime __implements checker
	out.WriteString(fmt.Sprintf("%sfunction __implements_%s(obj) {\n", prefix, s.Name))
	for _, m := range s.Methods {
		out.WriteString(fmt.Sprintf("%s  if (typeof obj.%s !== 'function') return false;\n", prefix, m.Name))
	}
	out.WriteString(fmt.Sprintf("%s  return true;\n", prefix))
	out.WriteString(fmt.Sprintf("%s}\n", prefix))
	return out.String()
}

// --- Destructuring code generation ---

func (g *Generator) genDestructure(s *ast.DestructureStatement, prefix string) string {
	patternCode := g.genPattern(s.Pattern)
	valueCode := g.genExpr(s.Value)
	return fmt.Sprintf("%sconst %s = %s;", prefix, patternCode, valueCode)
}

func (g *Generator) genPattern(p ast.DestructurePattern) string {
	switch pat := p.(type) {
	case *ast.ObjectPattern:
		parts := []string{}
		for _, f := range pat.Fields {
			if f.Nested != nil {
				parts = append(parts, fmt.Sprintf("%s: %s", f.Key, g.genPattern(f.Nested)))
			} else {
				parts = append(parts, f.Key)
			}
		}
		if pat.Rest != "" {
			parts = append(parts, "..."+pat.Rest)
		}
		return "{" + strings.Join(parts, ", ") + "}"
	case *ast.ArrayPattern:
		parts := []string{}
		for _, e := range pat.Elements {
			if e.Nested != nil {
				parts = append(parts, g.genPattern(e.Nested))
			} else {
				parts = append(parts, e.Name)
			}
		}
		if pat.Rest != "" {
			parts = append(parts, "..."+pat.Rest)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	default:
		return "/* unknown pattern */"
	}
}

// --- Concurrency code generation ---

func (g *Generator) genSpawn(s *ast.SpawnStatement, prefix string) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("%sconst __abort_%s = new AbortController();\n", prefix, s.Name))
	g.indent++
	body := g.genBlock(s.Body)
	g.indent--
	out.WriteString(fmt.Sprintf("%sconst __task_%s = (async (signal) => {\n%s%s})(__abort_%s.signal);", prefix, s.Name, body, prefix, s.Name))
	return out.String()
}

func (g *Generator) genParallel(s *ast.ParallelBlock, prefix string) string {
	var out strings.Builder
	// Collect variable names and their value expressions
	var names []string
	var exprs []string
	for _, task := range s.Tasks {
		if assign, ok := task.(*ast.AssignStatement); ok {
			names = append(names, assign.Name)
			exprs = append(exprs, g.genExpr(assign.Value))
			g.declared[assign.Name] = true
		}
	}
	promiseMethod := "Promise.all"
	if s.IsSettled {
		promiseMethod = "Promise.allSettled"
	}
	out.WriteString(fmt.Sprintf("%slet [%s] = await %s([\n", prefix, strings.Join(names, ", "), promiseMethod))
	for i, expr := range exprs {
		comma := ","
		if i == len(exprs)-1 {
			comma = ""
		}
		out.WriteString(fmt.Sprintf("%s  %s%s\n", prefix, expr, comma))
	}
	out.WriteString(fmt.Sprintf("%s]);", prefix))
	return out.String()
}

func (g *Generator) genRaceBlock(s *ast.RaceBlock, prefix string) string {
	var out strings.Builder
	var exprs []string
	for _, task := range s.Tasks {
		if assign, ok := task.(*ast.AssignStatement); ok {
			exprs = append(exprs, g.genExpr(assign.Value))
			g.declared[assign.Name] = true
		}
	}
	out.WriteString(fmt.Sprintf("%slet __race_result = await Promise.race([\n", prefix))
	for i, expr := range exprs {
		comma := ","
		if i == len(exprs)-1 {
			comma = ""
		}
		out.WriteString(fmt.Sprintf("%s  %s%s\n", prefix, expr, comma))
	}
	out.WriteString(fmt.Sprintf("%s]);", prefix))
	return out.String()
}

func (g *Generator) genChannelStmt(s *ast.ChannelStatement, prefix string) string {
	if s.BufferSize != nil {
		return fmt.Sprintf("%slet %s = new __QuillChannel(%s);", prefix, s.Name, g.genExpr(s.BufferSize))
	}
	return fmt.Sprintf("%slet %s = new __QuillChannel();", prefix, s.Name)
}

func (g *Generator) genSelectStmt(s *ast.SelectStatement, prefix string) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("%sawait Promise.race([\n", prefix))
	for _, c := range s.Cases {
		g.indent++
		body := g.genBlock(c.Body)
		g.indent--
		out.WriteString(fmt.Sprintf("%s  %s.receive().then(val => {\n%s%s  }),\n", prefix, c.Channel, body, prefix))
	}
	if s.AfterMs != nil {
		g.indent++
		afterBody := g.genBlock(s.AfterBody)
		g.indent--
		out.WriteString(fmt.Sprintf("%s  new Promise(resolve => setTimeout(() => {\n%s%s    resolve();\n%s  }, %s)),\n",
			prefix, afterBody, prefix, prefix, g.genExpr(s.AfterMs)))
	}
	out.WriteString(fmt.Sprintf("%s]);", prefix))
	return out.String()
}

// channelRuntime is the __QuillChannel class injected when channel/send/receive/select is used.
const channelRuntime = `class __QuillChannel {
  constructor(bufferSize = 0) {
    this.buffer = [];
    this.bufferSize = bufferSize;
    this.waiting = [];
    this.senders = [];
  }
  send(value) {
    return new Promise(resolve => {
      if (this.waiting.length > 0) {
        this.waiting.shift()(value);
        resolve();
      } else if (this.buffer.length < this.bufferSize) {
        this.buffer.push(value);
        resolve();
      } else {
        this.senders.push({ value, resolve });
      }
    });
  }
  receive() {
    return new Promise(resolve => {
      if (this.buffer.length > 0) {
        resolve(this.buffer.shift());
        if (this.senders.length > 0) {
          let s = this.senders.shift();
          this.buffer.push(s.value);
          s.resolve();
        }
      } else if (this.senders.length > 0) {
        let s = this.senders.shift();
        resolve(s.value);
        s.resolve();
      } else {
        this.waiting.push(resolve);
      }
    });
  }
}
`

// resultRuntime provides Success/Error Result type helpers and propagation.
const resultRuntime = `function Success(value) { return { __isOk: true, value }; }
function __QuillError(message) { return { __isErr: true, message }; }
function __propagate(val) {
  if (val instanceof Error || val?.__isErr) return val;
  return val?.__isOk ? val.value : val;
}
function __tryResult(fn) {
  try { const r = fn; if (r?.__isErr) return r; return r; } catch(e) { return __QuillError(e.message); }
}
`

// hasAsyncConstructs checks if the program uses any concurrency constructs that need async IIFE.
func (g *Generator) hasAsyncConstructs(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		switch stmt.(type) {
		case *ast.SpawnStatement, *ast.ParallelBlock, *ast.RaceBlock,
			*ast.ChannelStatement, *ast.SendStatement, *ast.SelectStatement,
			*ast.CancelStatement:
			return true
		}
	}
	return false
}

// hasConcurrency checks if the program uses channel/send/receive/select features.
func (g *Generator) hasConcurrency(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		switch stmt.(type) {
		case *ast.ChannelStatement, *ast.SendStatement, *ast.SelectStatement:
			return true
		}
	}
	return false
}

func (g *Generator) GenerateBody(program *ast.Program) string {
	var out strings.Builder
	for _, stmt := range program.Statements {
		out.WriteString(g.genStmt(stmt))
		out.WriteString("\n")
	}
	return out.String()
}

func escapeJS(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

// convertInterpolation converts {expr} to ${expr} for JS template literals.
// Only converts {identifier} or {expr.field} patterns, not { css } blocks.
func convertInterpolation(s string) string {
	var out strings.Builder
	i := 0
	for i < len(s) {
		if s[i] == '{' {
			// Check if it's already ${
			if i > 0 && s[i-1] == '$' {
				out.WriteByte(s[i])
				i++
				continue
			}
			// Look ahead to see if content looks like an interpolation expression
			// (starts with a letter/underscore, contains only valid identifier chars, dots, parens, etc.)
			j := i + 1
			if j < len(s) && isInterpolationStart(s[j]) {
				// Find the closing brace
				for j < len(s) && s[j] != '}' {
					j++
				}
				if j < len(s) {
					content := s[i+1 : j]
					if isInterpolationExpr(content) {
						out.WriteString("${")
						out.WriteString(content)
						out.WriteByte('}')
						i = j + 1
						continue
					}
				}
			}
			// Not an interpolation — keep the brace as-is but escape for template literal
			out.WriteString("\\{")
			i++
		} else {
			out.WriteByte(s[i])
			i++
		}
	}
	return out.String()
}

// hasInterpolation returns true if the string contains at least one {identifier} interpolation.
func hasInterpolation(s string) bool {
	i := 0
	for i < len(s) {
		if s[i] == '{' {
			j := i + 1
			if j < len(s) && isInterpolationStart(s[j]) {
				for j < len(s) && s[j] != '}' {
					j++
				}
				if j < len(s) {
					content := s[i+1 : j]
					if isInterpolationExpr(content) {
						return true
					}
				}
			}
		}
		i++
	}
	return false
}

// isInterpolationStart returns true if the character can start a Quill interpolation.
func isInterpolationStart(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'
}

// isInterpolationExpr returns true if the string looks like a valid interpolation expression
// (identifier, dot access, function call, etc.) rather than CSS or other content.
func isInterpolationExpr(s string) bool {
	if len(s) == 0 {
		return false
	}
	// Must start with a letter or underscore
	if !isInterpolationStart(s[0]) {
		return false
	}
	// Should only contain valid identifier characters, dots, parens, commas, spaces
	for _, c := range s {
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') ||
			c == '_' || c == '.' || c == '(' || c == ')' || c == ',' || c == ' ') {
			return false
		}
	}
	return true
}

// usesIdentifier checks if the generated user code references a given identifier
// followed by a dot (e.g., "Auth.", "DB.", "Validate.", "Log.").
func (g *Generator) usesIdentifier(code string, name string) bool {
	return strings.Contains(code, name+".")
}

// hasComponents checks if the program contains any ComponentStatement nodes.
func (g *Generator) hasComponents(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		if _, ok := stmt.(*ast.ComponentStatement); ok {
			return true
		}
		if _, ok := stmt.(*ast.MountStatement); ok {
			return true
		}
	}
	return false
}

// bodyContainsYield checks if a function body contains any yield statements (including nested in loops).
func (g *Generator) bodyContainsYield(stmts []ast.Statement) bool {
	for _, stmt := range stmts {
		switch s := stmt.(type) {
		case *ast.YieldStatement:
			return true
		case *ast.LoopStatement:
			if g.bodyContainsYield(s.Body) {
				return true
			}
		case *ast.IfStatement:
			if g.bodyContainsYield(s.Body) {
				return true
			}
			for _, elif := range s.ElseIfs {
				if g.bodyContainsYield(elif.Body) {
					return true
				}
			}
			if g.bodyContainsYield(s.Else) {
				return true
			}
		case *ast.WhileStatement:
			if g.bodyContainsYield(s.Body) {
				return true
			}
		case *ast.ForEachStatement:
			if g.bodyContainsYield(s.Body) {
				return true
			}
		}
	}
	return false
}

// genTypeCondition generates a JavaScript type check condition for pattern matching.
func (g *Generator) genTypeCondition(typeName string, matchVar string) string {
	switch typeName {
	case "text":
		return fmt.Sprintf("(typeof %s === \"string\")", matchVar)
	case "number":
		return fmt.Sprintf("(typeof %s === \"number\")", matchVar)
	case "boolean":
		return fmt.Sprintf("(typeof %s === \"boolean\")", matchVar)
	case "list":
		return fmt.Sprintf("(Array.isArray(%s))", matchVar)
	case "nothing":
		return fmt.Sprintf("(%s == null)", matchVar)
	default:
		return fmt.Sprintf("(typeof %s === \"%s\")", matchVar, typeName)
	}
}

// hasGenerators checks if the program uses generator/iterator features.
func (g *Generator) hasGenerators(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		if g.stmtUsesGenerators(stmt) {
			return true
		}
	}
	return false
}

// needsIteratorRuntime checks if generated code uses lazy iterator features.
func (g *Generator) needsIteratorRuntime(code string) bool {
	keywords := []string{"__quill_lazy", "__quill_range", "__QuillLazy", "collect()", ".filter(", ".take(", ".skip("}
	for _, kw := range keywords {
		if strings.Contains(code, kw) {
			return true
		}
	}
	return false
}

func (g *Generator) stmtUsesGenerators(stmt ast.Statement) bool {
	switch s := stmt.(type) {
	case *ast.YieldStatement:
		return true
	case *ast.LoopStatement:
		return true
	case *ast.FuncDefinition:
		if g.bodyContainsYield(s.Body) {
			return true
		}
	}
	return false
}

// --- Type Alias Code Generation ---

func (g *Generator) genTypeAlias(s *ast.TypeAliasStatement, prefix string) string {
	args := ""
	if len(s.Args) > 0 {
		args = ", [" + strings.Join(s.Args, ", ") + "]"
	}
	return fmt.Sprintf("%s// type %s = %s<%s%s> (erased at runtime)", prefix, s.Name, s.Utility, s.BaseType, args)
}

// --- Decorator Code Generation ---

const decoratorRuntime = `function authenticated(req) {
  return req.headers && req.headers.authorization;
}
function rateLimit(max) {
  const counts = new Map();
  return function(req) {
    const ip = req.socket && req.socket.remoteAddress || 'unknown';
    const count = (counts.get(ip) || 0) + 1;
    counts.set(ip, count);
    return count <= max;
  };
}
function log(fn) {
  return function(...args) {
    console.log('[' + fn.name + '] called with', args);
    const result = fn.apply(this, args);
    console.log('[' + fn.name + '] returned', result);
    return result;
  };
}
`

func (g *Generator) genDecoratedFunc(s *ast.DecoratedFuncDefinition, prefix string) string {
	var out strings.Builder
	// Generate the function itself as a let-bound function expression
	params := strings.Join(s.Func.Params, ", ")
	g.indent++
	body := g.genBlock(s.Func.Body)
	g.indent--
	out.WriteString(fmt.Sprintf("%slet %s = function(%s) {\n%s%s};\n", prefix, s.Func.Name, params, body, prefix))
	g.declared[s.Func.Name] = true
	// Apply decorators in reverse order (innermost first)
	for i := len(s.Decorators) - 1; i >= 0; i-- {
		dec := s.Decorators[i]
		if len(dec.Args) > 0 {
			args := make([]string, len(dec.Args))
			for j, a := range dec.Args {
				args[j] = g.genExpr(a)
			}
			out.WriteString(fmt.Sprintf("%s%s = %s(%s)(%s);\n", prefix, s.Func.Name, dec.Name, strings.Join(args, ", "), s.Func.Name))
		} else {
			out.WriteString(fmt.Sprintf("%s%s = %s(%s);\n", prefix, s.Func.Name, dec.Name, s.Func.Name))
		}
	}
	return out.String()
}

func (g *Generator) genDecoratedRoute(s *ast.DecoratedRouteDefinition, prefix string) string {
	var out strings.Builder
	// Comment showing decorators
	decNames := make([]string, len(s.Decorators))
	for i, d := range s.Decorators {
		decNames[i] = "@" + d.Name
	}
	out.WriteString(fmt.Sprintf("%s// %s\n", prefix, strings.Join(decNames, " ")))
	out.WriteString(fmt.Sprintf("%sif (method === '%s' && url.pathname === '%s') {\n", prefix, s.Route.Method, s.Route.Path))
	g.indent++
	innerPrefix := strings.Repeat("  ", g.indent)
	// Generate middleware checks
	for _, dec := range s.Decorators {
		if len(dec.Args) > 0 {
			args := make([]string, len(dec.Args))
			for j, a := range dec.Args {
				args[j] = g.genExpr(a)
			}
			out.WriteString(fmt.Sprintf("%sif (!%s(%s)(req)) { res.writeHead(429); res.end('Too Many Requests'); return; }\n", innerPrefix, dec.Name, strings.Join(args, ", ")))
		} else {
			out.WriteString(fmt.Sprintf("%sif (!%s(req)) { res.writeHead(401); res.end('Unauthorized'); return; }\n", innerPrefix, dec.Name))
		}
	}
	// Handler body
	for _, stmt := range s.Route.Body {
		out.WriteString(g.genStmt(stmt))
		out.WriteString("\n")
	}
	g.indent--
	out.WriteString(fmt.Sprintf("%s}", prefix))
	return out.String()
}

// hasDecorators checks if the program uses any decorator features.
func (g *Generator) hasDecorators(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		switch stmt.(type) {
		case *ast.DecoratedFuncDefinition, *ast.DecoratedRouteDefinition:
			return true
		}
	}
	return false
}

// --- WebSocket Code Generation ---

func (g *Generator) genWebSocket(s *ast.WebSocketBlock, prefix string) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("%sconst WebSocket = require('ws');\n", prefix))
	out.WriteString(fmt.Sprintf("%sconst __wss = new WebSocket.Server({ noServer: true });\n", prefix))
	out.WriteString(fmt.Sprintf("%sconst __ws_clients = new Set();\n", prefix))
	out.WriteString(fmt.Sprintf("%sserver.on('upgrade', (request, socket, head) => {\n", prefix))
	g.indent++
	innerPrefix := strings.Repeat("  ", g.indent)
	out.WriteString(fmt.Sprintf("%sif (request.url === '%s') {\n", innerPrefix, s.Path))
	g.indent++
	innerPrefix2 := strings.Repeat("  ", g.indent)
	out.WriteString(fmt.Sprintf("%s__wss.handleUpgrade(request, socket, head, (ws) => {\n", innerPrefix2))
	out.WriteString(fmt.Sprintf("%s  __wss.emit('connection', ws, request);\n", innerPrefix2))
	out.WriteString(fmt.Sprintf("%s});\n", innerPrefix2))
	g.indent--
	out.WriteString(fmt.Sprintf("%s}\n", innerPrefix))
	g.indent--
	out.WriteString(fmt.Sprintf("%s});\n", prefix))

	// Connection handler
	out.WriteString(fmt.Sprintf("%s__wss.on('connection', (%s) => {\n", prefix, s.ConnectVar))
	g.indent++
	innerPrefix = strings.Repeat("  ", g.indent)
	out.WriteString(fmt.Sprintf("%s__ws_clients.add(%s);\n", innerPrefix, s.ConnectVar))

	// OnConnect body
	if len(s.OnConnect) > 0 {
		for _, stmt := range s.OnConnect {
			out.WriteString(g.genStmt(stmt))
			out.WriteString("\n")
		}
	}

	// OnMessage handler
	if len(s.OnMessage) > 0 {
		out.WriteString(fmt.Sprintf("%s%s.on('message', (%s) => {\n", innerPrefix, s.ConnectVar, s.DataVar))
		g.indent++
		for _, stmt := range s.OnMessage {
			out.WriteString(g.genStmt(stmt))
			out.WriteString("\n")
		}
		g.indent--
		out.WriteString(fmt.Sprintf("%s});\n", innerPrefix))
	}

	// OnClose handler
	if len(s.OnClose) > 0 {
		out.WriteString(fmt.Sprintf("%s%s.on('close', () => {\n", innerPrefix, s.ConnectVar))
		g.indent++
		closePrefix := strings.Repeat("  ", g.indent)
		out.WriteString(fmt.Sprintf("%s__ws_clients.delete(%s);\n", closePrefix, s.ConnectVar))
		for _, stmt := range s.OnClose {
			out.WriteString(g.genStmt(stmt))
			out.WriteString("\n")
		}
		g.indent--
		out.WriteString(fmt.Sprintf("%s});\n", innerPrefix))
	}

	g.indent--
	out.WriteString(fmt.Sprintf("%s});\n", prefix))
	return out.String()
}

// hasWebSockets checks if the program uses WebSocket features.
func (g *Generator) hasWebSockets(program *ast.Program) bool {
	for _, stmt := range program.Statements {
		if srv, ok := stmt.(*ast.ServerBlockStatement); ok {
			if len(srv.WebSockets) > 0 {
				return true
			}
		}
		if _, ok := stmt.(*ast.WebSocketBlock); ok {
			return true
		}
	}
	return false
}
