package codegen

import (
	"fmt"
	"quill/ast"
	"strings"
)

// isNamespaceImportPackage returns true for packages that use named/namespace exports
// and need `import * as X from` rather than `import X from`.
func isNamespaceImportPackage(pkg string) bool {
	// Expo SDK packages use namespace exports
	if strings.HasPrefix(pkg, "expo-") {
		return true
	}
	// React Navigation packages use named exports
	if strings.HasPrefix(pkg, "@react-navigation/") {
		return true
	}
	// Other known namespace-export packages
	switch pkg {
	case "react-native-maps", "react-native-reanimated", "react-native-gesture-handler":
		return true
	}
	// Local file imports always use default
	if strings.HasPrefix(pkg, "./") || strings.HasPrefix(pkg, "../") {
		return false
	}
	return false
}

// NewExpo creates a Generator configured for React Native / Expo output.
func NewExpo() *Generator {
	return &Generator{
		declared:      make(map[string]bool),
		importedFiles: make(map[string]bool),
		expoMode:      true,
	}
}

// generateExpo generates a complete React Native / Expo source file from the AST.
func (g *Generator) generateExpo(program *ast.Program) string {
	var out strings.Builder

	// Collect all components, navigation blocks, and top-level statements
	var components []*ast.ComponentStatement
	var navBlocks []*ast.NavigationBlock
	var topLevel []ast.Statement
	rnComponents := map[string]bool{}

	for _, stmt := range program.Statements {
		switch s := stmt.(type) {
		case *ast.ComponentStatement:
			components = append(components, s)
		case *ast.NavigationBlock:
			navBlocks = append(navBlocks, s)
		case *ast.ContextDeclaration:
			// Will be handled in top-level code generation
			_ = s
			topLevel = append(topLevel, stmt)
		default:
			topLevel = append(topLevel, stmt)
		}
	}

	// Scan render bodies to find which RN components are used
	for _, comp := range components {
		g.collectRNComponents(comp.RenderBody, rnComponents)
	}

	// --- Scan components for hook and API usage ---
	hasEffects := false
	hasContexts := false
	hasMemos := false
	hasCallbacks := false
	usesAlert := false
	usesAsyncStorage := false

	for _, comp := range components {
		if len(comp.Effects) > 0 {
			hasEffects = true
		}
		if len(comp.Contexts) > 0 {
			hasContexts = true
		}
		if len(comp.Memos) > 0 {
			hasMemos = true
		}
		if len(comp.Callbacks) > 0 {
			hasCallbacks = true
		}
		// Scan methods, effects, and callbacks for alert/store/load calls (recursively)
		allBodies := [][]ast.Statement{}
		for _, m := range comp.Methods {
			allBodies = append(allBodies, m.Body)
		}
		for _, e := range comp.Effects {
			allBodies = append(allBodies, e.Body)
		}
		for _, cb := range comp.Callbacks {
			allBodies = append(allBodies, cb.Body)
		}
		for _, body := range allBodies {
			calls := scanStatementsForCalls(body)
			if calls["alert"] {
				usesAlert = true
			}
			if calls["store"] || calls["removeStore"] || calls["load"] {
				usesAsyncStorage = true
			}
		}
	}

	// Add Alert to RN components if alert() is used
	if usesAlert {
		rnComponents["Alert"] = true
	}

	// Scan top-level function bodies for RN component names used in React.createElement
	for _, stmt := range topLevel {
		if fn, ok := stmt.(*ast.FuncDefinition); ok {
			fnCode := g.genBlock(fn.Body)
			knownRN := []string{"View", "Text", "Pressable", "ScrollView", "TextInput", "Image",
				"TouchableOpacity", "FlatList", "SectionList", "Modal", "ActivityIndicator",
				"Switch", "SafeAreaView", "KeyboardAvoidingView", "StatusBar", "Animated"}
			for _, name := range knownRN {
				if strings.Contains(fnCode, name) {
					rnComponents[name] = true
				}
			}
		}
	}

	// Check if any component uses state
	hasState := false
	for _, comp := range components {
		if len(comp.States) > 0 {
			hasState = true
			break
		}
	}

	// --- Imports ---
	out.WriteString("// Generated by Quill (Expo mode)\n")
	var hooks []string
	if hasState {
		hooks = append(hooks, "useState")
	}
	if hasEffects {
		hooks = append(hooks, "useEffect")
	}
	if hasContexts {
		hooks = append(hooks, "useContext")
	}
	if hasMemos {
		hooks = append(hooks, "useMemo")
	}
	if hasCallbacks {
		hooks = append(hooks, "useCallback")
	}
	if len(hooks) > 0 {
		out.WriteString(fmt.Sprintf("import React, { %s } from 'react';\n", strings.Join(hooks, ", ")))
	} else {
		out.WriteString("import React from 'react';\n")
	}

	// Import React Native components
	rnImports := g.buildRNImports(rnComponents)
	if len(rnImports) > 0 {
		out.WriteString(fmt.Sprintf("import { %s } from 'react-native';\n", strings.Join(rnImports, ", ")))
	}

	// Import AsyncStorage if store/load/removeStore is used
	if usesAsyncStorage {
		out.WriteString("import AsyncStorage from '@react-native-async-storage/async-storage';\n")
	}

	// Check if uuid() is used anywhere and add polyfill
	usesUUID := false
	fullCode := out.String()
	for _, comp := range components {
		for _, m := range comp.Methods {
			for _, stmt := range m.Body {
				if stmtStr := g.genExpoStmt(stmt, nil); strings.Contains(stmtStr, "uuid()") {
					usesUUID = true
				}
			}
		}
	}
	if !usesUUID {
		// Also check top-level functions
		for _, stmt := range topLevel {
			if fn, ok := stmt.(*ast.FuncDefinition); ok {
				fnCode := g.genBlock(fn.Body)
				if strings.Contains(fnCode, "uuid()") {
					usesUUID = true
				}
			}
		}
	}
	_ = fullCode

	// Import navigation if needed
	if len(navBlocks) > 0 {
		out.WriteString("import { NavigationContainer } from '@react-navigation/native';\n")
		for _, nav := range navBlocks {
			switch nav.Type {
			case "tab":
				out.WriteString("import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';\n")
			case "drawer":
				out.WriteString("import { createDrawerNavigator } from '@react-navigation/drawer';\n")
			default:
				out.WriteString("import { createNativeStackNavigator } from '@react-navigation/native-stack';\n")
			}
		}
	}

	out.WriteString("\n")

	// Add uuid polyfill if uuid() is used
	if usesUUID {
		out.WriteString("function uuid() {\n  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {\n    const r = Math.random() * 16 | 0;\n    const v = c === 'x' ? r : (r & 0x3 | 0x8);\n    return v.toString(16);\n  });\n}\n\n")
	}

	// Generate top-level non-component code
	for _, stmt := range topLevel {
		// Handle ContextDeclaration inline
		if ctx, ok := stmt.(*ast.ContextDeclaration); ok {
			out.WriteString(fmt.Sprintf("export const %s = React.createContext(%s);\n", ctx.Name, g.genExpr(ctx.DefaultValue)))
			continue
		}
		// Handle UseStatement with ESM import syntax
		if useStmt, ok := stmt.(*ast.UseStatement); ok {
			importPath := strings.TrimSuffix(useStmt.Path, ".quill")
			if useStmt.Alias != "" {
				// Determine import style based on package
				if isNamespaceImportPackage(importPath) {
					out.WriteString(fmt.Sprintf("import * as %s from '%s';\n", useStmt.Alias, importPath))
				} else {
					out.WriteString(fmt.Sprintf("import %s from '%s';\n", useStmt.Alias, importPath))
				}
			} else {
				out.WriteString(fmt.Sprintf("import '%s';\n", importPath))
			}
			continue
		}
		// Handle FromUseStatement with ESM destructured imports
		if fromStmt, ok := stmt.(*ast.FromUseStatement); ok {
			importPath := strings.TrimSuffix(fromStmt.Path, ".quill")
			namesParts := make([]string, len(fromStmt.Names))
			for i, n := range fromStmt.Names {
				if i < len(fromStmt.Aliases) && fromStmt.Aliases[i] != "" {
					namesParts[i] = n + " as " + fromStmt.Aliases[i]
				} else {
					namesParts[i] = n
				}
			}
			names := strings.Join(namesParts, ", ")
			out.WriteString(fmt.Sprintf("import { %s } from '%s';\n", names, importPath))
			continue
		}
		// Reset declared map for each top-level function (each is its own JS scope)
		if _, isFuncDef := stmt.(*ast.FuncDefinition); isFuncDef {
			savedDeclared := g.declared
			g.declared = make(map[string]bool)
			defer func() {}() // no-op, just ensuring we can use savedDeclared
			code := g.genStmt(stmt)
			g.declared = savedDeclared
			if strings.TrimSpace(code) != "" {
				trimmed := strings.TrimSpace(code)
				if strings.HasPrefix(trimmed, "function ") || strings.HasPrefix(trimmed, "async function ") {
					out.WriteString("export " + code)
				} else {
					out.WriteString(code)
				}
				out.WriteString("\n")
			}
			continue
		}
		code := g.genStmt(stmt)
		if strings.TrimSpace(code) != "" {
			// Add export to top-level functions and constants
			trimmed := strings.TrimSpace(code)
			if strings.HasPrefix(trimmed, "function ") || strings.HasPrefix(trimmed, "async function ") {
				out.WriteString("export " + code)
			} else if strings.HasPrefix(trimmed, "const ") || strings.HasPrefix(trimmed, "let ") {
				out.WriteString("export " + code)
			} else {
				out.WriteString(code)
			}
			out.WriteString("\n")
		}
	}

	// --- Collect all styles from all components for merged StyleSheet ---
	allStyles := make(map[string][]ast.NativeStyleProp)
	for _, comp := range components {
		if comp.NativeStyles != nil {
			for name, props := range comp.NativeStyles.Styles {
				allStyles[name] = props
			}
		}
	}

	// Populate expoStyleKeys for styles. prefix logic
	g.expoStyleKeys = make(map[string]bool)
	for name := range allStyles {
		g.expoStyleKeys[name] = true
	}

	// --- Generate each component ---
	// If there's a navigation block, none of the components get export default (nav does)
	// If there's only one component, it gets export default
	// If there are multiple components, all get named exports (consumers use named imports)
	for _, comp := range components {
		isDefault := false
		if len(navBlocks) == 0 && len(components) == 1 {
			isDefault = true
		}
		// Pass nil for NativeStyles , we emit one merged block at the end
		savedStyles := comp.NativeStyles
		comp.NativeStyles = nil
		out.WriteString(g.genExpoComponentWithExport(comp, isDefault))
		comp.NativeStyles = savedStyles
		out.WriteString("\n")
	}

	// --- Generate navigation setup ---
	for _, nav := range navBlocks {
		out.WriteString(g.genExpoNavigation(nav))
		out.WriteString("\n")
	}

	// --- Emit merged StyleSheet.create() ---
	if len(allStyles) > 0 {
		out.WriteString(g.genExpoStylesNamed(&ast.NativeStyleBlock{Styles: allStyles}, "styles"))
	}

	return out.String()
}

// genExpoComponent generates a React functional component with hooks (default export).
func (g *Generator) genExpoComponent(s *ast.ComponentStatement) string {
	return g.genExpoComponentWithExport(s, true)
}

// genExpoComponentWithExport generates a React functional component with configurable export.
func (g *Generator) genExpoComponentWithExport(s *ast.ComponentStatement, isDefault bool) string {
	var out strings.Builder

	// Reset declared map for each component (each is a separate JS function scope)
	savedDeclared := g.declared
	g.declared = make(map[string]bool)

	// Restore at the end
	defer func() { g.declared = savedDeclared }()

	// Track state variable names for setter rewriting
	stateVars := map[string]bool{}
	for _, st := range s.States {
		stateVars[st.Name] = true
	}

	// Build props
	propsStr := ""
	if s.HasProps && len(s.Props) > 0 {
		propsStr = "{ " + strings.Join(s.Props, ", ") + " }"
	} else if s.HasProps {
		propsStr = "props"
	}

	if isDefault {
		out.WriteString(fmt.Sprintf("export default function %s(%s) {\n", s.Name, propsStr))
	} else {
		out.WriteString(fmt.Sprintf("export function %s(%s) {\n", s.Name, propsStr))
	}

	// --- Context hooks (must come before useState so state initializers can reference context) ---
	for _, ctx := range s.Contexts {
		out.WriteString(fmt.Sprintf("  const %s = useContext(%s);\n", ctx.Alias, ctx.ContextName))
	}

	// --- State declarations as useState hooks ---
	for _, st := range s.States {
		setter := "set" + strings.ToUpper(st.Name[:1]) + st.Name[1:]
		out.WriteString(fmt.Sprintf("  const [%s, %s] = useState(%s);\n", st.Name, setter, g.genExpr(st.Value)))
	}

	if len(s.States) > 0 || len(s.Contexts) > 0 {
		out.WriteString("\n")
	}

	// --- Methods (must come before memos/callbacks to avoid TDZ errors) ---
	for _, method := range s.Methods {
		params := strings.Join(method.Params, ", ")
		asyncKw := ""
		if g.bodyContainsAwait(method.Body) {
			asyncKw = "async "
		}
		out.WriteString(fmt.Sprintf("  const %s = %s(%s) => {\n", method.Name, asyncKw, params))
		savedMethDeclared := g.declared
		g.declared = make(map[string]bool)
		g.indent = 2
		for _, stmt := range method.Body {
			out.WriteString(g.genExpoStmt(stmt, stateVars))
			out.WriteString("\n")
		}
		g.indent = 0
		g.declared = savedMethDeclared
		out.WriteString("  };\n\n")
	}

	// --- Memo hooks ---
	for _, m := range s.Memos {
		deps := "[]"
		if len(m.Dependencies) > 0 {
			deps = "[" + strings.Join(m.Dependencies, ", ") + "]"
		}
		valExpr := g.genExpr(m.Value)
		// Wrap object literals in parens so JS doesn't treat { as a block
		if _, isObj := m.Value.(*ast.ObjectLiteral); isObj {
			out.WriteString(fmt.Sprintf("  const %s = useMemo(() => (%s), %s);\n", m.Name, valExpr, deps))
		} else {
			out.WriteString(fmt.Sprintf("  const %s = useMemo(() => %s, %s);\n", m.Name, valExpr, deps))
		}
	}

	// --- Callback hooks ---
	for _, cb := range s.Callbacks {
		deps := "[]"
		if len(cb.Dependencies) > 0 {
			deps = "[" + strings.Join(cb.Dependencies, ", ") + "]"
		}
		params := strings.Join(cb.Params, ", ")
		savedCbDeclared := g.declared
		g.declared = make(map[string]bool)
		g.indent = 2
		var cbLines []string
		for _, stmt := range cb.Body {
			cbLines = append(cbLines, g.genExpoStmt(stmt, stateVars))
		}
		body := strings.Join(cbLines, "\n") + "\n"
		g.indent = 0
		g.declared = savedCbDeclared
		asyncKw := ""
		if g.bodyContainsAwait(cb.Body) {
			asyncKw = "async "
		}
		out.WriteString(fmt.Sprintf("  const %s = useCallback(%s(%s) => {\n%s  }, %s);\n", cb.Name, asyncKw, params, body, deps))
	}

	if len(s.Contexts) > 0 || len(s.Methods) > 0 || len(s.Memos) > 0 || len(s.Callbacks) > 0 {
		out.WriteString("\n")
	}

	// --- Effects ---
	for _, effect := range s.Effects {
		out.WriteString("  useEffect(() => {\n")
		savedEffDeclared := g.declared
		g.declared = make(map[string]bool)
		g.indent = 2
		for _, stmt := range effect.Body {
			out.WriteString(g.genExpoStmt(stmt, stateVars))
			out.WriteString("\n")
		}
		g.indent = 0
		g.declared = savedEffDeclared
		if len(effect.Dependencies) > 0 {
			out.WriteString(fmt.Sprintf("  }, [%s]);\n", strings.Join(effect.Dependencies, ", ")))
		} else {
			out.WriteString("  }, []);\n")
		}
		out.WriteString("\n")
	}

	// --- Pre-render statements (variables computed before return) ---
	if len(s.PreRenderStatements) > 0 {
		for _, stmt := range s.PreRenderStatements {
			out.WriteString(g.genExpoStmt(stmt, stateVars))
			out.WriteString("\n")
		}
		out.WriteString("\n")
	}

	// --- Hoist assignments and statement-only conditionals from render tree ---
	renderNodes := make([]ast.RenderNode, len(s.RenderBody))
	for i := range s.RenderBody {
		renderNodes[i] = ast.RenderNode{Element: &s.RenderBody[i]}
	}
	hoisted := collectAssignmentsToHoist(renderNodes)
	if len(hoisted) > 0 {
		for _, assign := range hoisted {
			out.WriteString(g.genExpoElement(assign, 0, stateVars))
		}
		// Remove hoisted assignments from the render tree
		// Don't process children of conditional/iterator elements , their assignments weren't hoisted
		for i := range s.RenderBody {
			if s.RenderBody[i].Condition != nil || s.RenderBody[i].Iterator != nil {
				continue
			}
			s.RenderBody[i].Children = removeHoistedAssignments(s.RenderBody[i].Children)
		}
	}

	// Hoist statement-only conditionals (conditionals with only assignments, no render elements)
	// These should be emitted as regular JS if-statements, not JSX conditionals
	var remainingBody []ast.RenderElement
	for i := range s.RenderBody {
		el := &s.RenderBody[i]
		if isStatementOnlyConditional(el) {
			out.WriteString(g.emitStatementOnlyConditional(el, stateVars))
		} else {
			// Check top-level children for statement-only conditionals too
			var remainingChildren []ast.RenderNode
			for _, child := range el.Children {
				if child.Element != nil && isStatementOnlyConditional(child.Element) {
					out.WriteString(g.emitStatementOnlyConditional(child.Element, stateVars))
				} else {
					remainingChildren = append(remainingChildren, child)
				}
			}
			el.Children = remainingChildren
			remainingBody = append(remainingBody, *el)
		}
	}
	s.RenderBody = remainingBody

	// --- Render ---
	out.WriteString("  return (\n")
	needsFragment := len(s.RenderBody) > 1 ||
		(len(s.RenderBody) == 1 && (s.RenderBody[0].Condition != nil || s.RenderBody[0].Iterator != nil))
	if needsFragment {
		out.WriteString("    <>\n")
		for i := range s.RenderBody {
			out.WriteString(g.genExpoElement(&s.RenderBody[i], 3, stateVars))
		}
		out.WriteString("    </>\n")
	} else if len(s.RenderBody) == 1 {
		out.WriteString(g.genExpoElement(&s.RenderBody[0], 2, stateVars))
	} else {
		out.WriteString("    <View />\n")
	}
	out.WriteString("  );\n")
	out.WriteString("}\n")

	// --- StyleSheet ---
	if s.NativeStyles != nil {
		out.WriteString("\n")
		out.WriteString(g.genExpoStyles(s.NativeStyles))
	}

	return out.String()
}

// genExpoStmt generates a statement, rewriting state variable assignments to setter calls.
func (g *Generator) genExpoStmt(stmt ast.Statement, stateVars map[string]bool) string {
	prefix := strings.Repeat("  ", g.indent)
	switch s := stmt.(type) {
	case *ast.AssignStatement:
		if stateVars[s.Name] {
			setter := "set" + strings.ToUpper(s.Name[:1]) + s.Name[1:]
			return fmt.Sprintf("%s%s(%s);", prefix, setter, g.genExpr(s.Value))
		}
		// Handle load() pattern
		if call, ok := s.Value.(*ast.CallExpr); ok {
			if ident, ok := call.Function.(*ast.Identifier); ok && ident.Name == "load" {
				if len(call.Args) >= 1 {
					return fmt.Sprintf("%sconst %s = JSON.parse(await AsyncStorage.getItem(%s));", prefix, s.Name, g.genExpr(call.Args[0]))
				}
			}
		}
		// Handle await load() pattern (wrapped in AwaitExpr)
		if awaitExpr, ok := s.Value.(*ast.AwaitExpr); ok {
			if call, ok := awaitExpr.Expr.(*ast.CallExpr); ok {
				if ident, ok := call.Function.(*ast.Identifier); ok && ident.Name == "load" {
					if len(call.Args) >= 1 {
						return fmt.Sprintf("%sconst %s = JSON.parse(await AsyncStorage.getItem(%s));", prefix, s.Name, g.genExpr(call.Args[0]))
					}
				}
			}
		}
		// Use genExpoExpr for the value to handle style key replacements
		value := g.genExpoExpr(s.Value)
		if g.declared[s.Name] {
			return fmt.Sprintf("%s%s = %s;", prefix, s.Name, value)
		}
		g.declared[s.Name] = true
		return fmt.Sprintf("%slet %s = %s;", prefix, s.Name, value)
	case *ast.ExprStatement:
		if call, ok := s.Expr.(*ast.CallExpr); ok {
			if ident, ok := call.Function.(*ast.Identifier); ok {
				switch ident.Name {
				case "alert":
					args := make([]string, len(call.Args))
					for i, a := range call.Args {
						args[i] = g.genExpr(a)
					}
					return fmt.Sprintf("%sAlert.alert(%s);", prefix, strings.Join(args, ", "))
				case "store":
					if len(call.Args) >= 2 {
						return fmt.Sprintf("%sawait AsyncStorage.setItem(%s, JSON.stringify(%s));", prefix, g.genExpr(call.Args[0]), g.genExpr(call.Args[1]))
					}
				case "removeStore":
					if len(call.Args) >= 1 {
						return fmt.Sprintf("%sawait AsyncStorage.removeItem(%s);", prefix, g.genExpr(call.Args[0]))
					}
				}
			}
		}
		return g.genStmt(stmt)
	case *ast.TryCatchStatement:
		// Handle try/catch with state-setter rewriting in body
		g.indent++
		var tryLines []string
		for _, stmt := range s.TryBody {
			tryLines = append(tryLines, g.genExpoStmt(stmt, stateVars))
		}
		tryBody := strings.Join(tryLines, "\n") + "\n"
		g.indent--
		g.indent++
		var catchLines []string
		for _, stmt := range s.CatchBody {
			catchLines = append(catchLines, g.genExpoStmt(stmt, stateVars))
		}
		catchBody := strings.Join(catchLines, "\n") + "\n"
		g.indent--
		errorVar := s.ErrorVar
		if errorVar == "" {
			errorVar = "error"
		}
		return fmt.Sprintf("%stry {\n%s%s} catch (%s) {\n%s%s}", prefix, tryBody, prefix, errorVar, catchBody, prefix)
	case *ast.IfStatement:
		// Handle if/else with state-setter rewriting in body
		g.indent++
		var ifLines []string
		for _, stmt := range s.Body {
			ifLines = append(ifLines, g.genExpoStmt(stmt, stateVars))
		}
		ifBody := strings.Join(ifLines, "\n") + "\n"
		g.indent--
		result := fmt.Sprintf("%sif (%s) {\n%s%s}", prefix, g.genExpr(s.Condition), ifBody, prefix)
		for _, elif := range s.ElseIfs {
			g.indent++
			var elifLines []string
			for _, stmt := range elif.Body {
				elifLines = append(elifLines, g.genExpoStmt(stmt, stateVars))
			}
			elifBody := strings.Join(elifLines, "\n") + "\n"
			g.indent--
			result += fmt.Sprintf(" else if (%s) {\n%s%s}", g.genExpr(elif.Condition), elifBody, prefix)
		}
		if len(s.Else) > 0 {
			g.indent++
			var elseLines []string
			for _, stmt := range s.Else {
				elseLines = append(elseLines, g.genExpoStmt(stmt, stateVars))
			}
			elseBody := strings.Join(elseLines, "\n") + "\n"
			g.indent--
			result += fmt.Sprintf(" else {\n%s%s}", elseBody, prefix)
		}
		return result
	case *ast.FuncDefinition:
		// Handle function definitions with state-setter rewriting in body
		params := strings.Join(s.Params, ", ")
		g.indent++
		var bodyLines []string
		for _, stmt := range s.Body {
			bodyLines = append(bodyLines, g.genExpoStmt(stmt, stateVars))
		}
		body := strings.Join(bodyLines, "\n") + "\n"
		g.indent--
		if g.bodyContainsAwait(s.Body) {
			return fmt.Sprintf("%sasync function %s(%s) {\n%s%s}", prefix, s.Name, params, body, prefix)
		}
		return fmt.Sprintf("%sfunction %s(%s) {\n%s%s}", prefix, s.Name, params, body, prefix)
	case *ast.ForEachStatement:
		// Handle for-each with state-setter rewriting in body
		// Save declared state to avoid leaking block-scoped vars across iterations
		savedDeclared := make(map[string]bool)
		for k, v := range g.declared {
			savedDeclared[k] = v
		}
		g.indent++
		var bodyLines []string
		for _, stmt := range s.Body {
			bodyLines = append(bodyLines, g.genExpoStmt(stmt, stateVars))
		}
		body := strings.Join(bodyLines, "\n") + "\n"
		g.indent--
		// Restore declared state
		g.declared = savedDeclared
		varPart := s.Variable
		if s.DestructurePattern != nil {
			varPart = g.genPattern(s.DestructurePattern)
		}
		awaitPart := ""
		if s.IsAsync {
			awaitPart = "await "
		}
		return fmt.Sprintf("%sfor %s(const %s of %s) {\n%s%s}", prefix, awaitPart, varPart, g.genExpr(s.Iterable), body, prefix)
	case *ast.WhileStatement:
		// Save declared state to avoid leaking block-scoped vars
		savedDeclared := make(map[string]bool)
		for k, v := range g.declared {
			savedDeclared[k] = v
		}
		g.indent++
		var bodyLines []string
		for _, stmt := range s.Body {
			bodyLines = append(bodyLines, g.genExpoStmt(stmt, stateVars))
		}
		body := strings.Join(bodyLines, "\n") + "\n"
		g.indent--
		// Restore declared state
		g.declared = savedDeclared
		return fmt.Sprintf("%swhile (%s) {\n%s%s}", prefix, g.genExpr(s.Condition), body, prefix)
	case *ast.LoopStatement:
		g.indent++
		var bodyLines []string
		for _, stmt := range s.Body {
			bodyLines = append(bodyLines, g.genExpoStmt(stmt, stateVars))
		}
		body := strings.Join(bodyLines, "\n") + "\n"
		g.indent--
		return fmt.Sprintf("%swhile (true) {\n%s%s}", prefix, body, prefix)
	case *ast.NavigateStatement:
		if s.Params != nil {
			return fmt.Sprintf("%snavigation.navigate(\"%s\", %s);", prefix, s.Screen, g.genExpr(s.Params))
		}
		return fmt.Sprintf("%snavigation.navigate(\"%s\");", prefix, s.Screen)
	case *ast.SayStatement:
		return fmt.Sprintf("%sconsole.log(%s);", prefix, g.genExpr(s.Value))
	case *ast.ReturnStatement:
		if s.Value != nil {
			return fmt.Sprintf("%sreturn %s;", prefix, g.genExpoExpr(s.Value))
		}
		return fmt.Sprintf("%sreturn;", prefix)
	default:
		return g.genStmt(stmt)
	}
}

// genExpoExpr generates an expression, replacing bare identifiers matching stylesheet keys with styles.name.
func (g *Generator) genExpoExpr(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.Identifier:
		if g.expoStyleKeys[e.Name] {
			return "styles." + e.Name
		}
		return g.genExpr(expr)
	case *ast.ListLiteral:
		elems := make([]string, len(e.Elements))
		for i, el := range e.Elements {
			elems[i] = g.genExpoExpr(el)
		}
		return "[" + strings.Join(elems, ", ") + "]"
	default:
		return g.genExpr(expr)
	}
}

// scanStatementsForCalls recursively scans statements for function calls and returns the set of called function names.
func scanStatementsForCalls(stmts []ast.Statement) map[string]bool {
	calls := map[string]bool{}
	for _, stmt := range stmts {
		scanStmtForCalls(stmt, calls)
	}
	return calls
}

func scanStmtForCalls(stmt ast.Statement, calls map[string]bool) {
	switch s := stmt.(type) {
	case *ast.ExprStatement:
		scanExprForCalls(s.Expr, calls)
	case *ast.AssignStatement:
		scanExprForCalls(s.Value, calls)
	case *ast.IfStatement:
		scanStatementsForCalls2(s.Body, calls)
		scanStatementsForCalls2(s.Else, calls)
		for _, elif := range s.ElseIfs {
			scanStatementsForCalls2(elif.Body, calls)
		}
	case *ast.ForEachStatement:
		scanStatementsForCalls2(s.Body, calls)
	case *ast.WhileStatement:
		scanStatementsForCalls2(s.Body, calls)
	case *ast.TryCatchStatement:
		scanStatementsForCalls2(s.TryBody, calls)
		scanStatementsForCalls2(s.CatchBody, calls)
	case *ast.FuncDefinition:
		scanStatementsForCalls2(s.Body, calls)
	case *ast.ReturnStatement:
		if s.Value != nil {
			scanExprForCalls(s.Value, calls)
		}
	}
}

func scanStatementsForCalls2(stmts []ast.Statement, calls map[string]bool) {
	for _, stmt := range stmts {
		scanStmtForCalls(stmt, calls)
	}
}

func scanExprForCalls(expr ast.Expression, calls map[string]bool) {
	if expr == nil {
		return
	}
	switch e := expr.(type) {
	case *ast.CallExpr:
		if ident, ok := e.Function.(*ast.Identifier); ok {
			calls[ident.Name] = true
		}
		for _, arg := range e.Args {
			scanExprForCalls(arg, calls)
		}
	case *ast.AwaitExpr:
		scanExprForCalls(e.Expr, calls)
	case *ast.BinaryExpr:
		scanExprForCalls(e.Left, calls)
		scanExprForCalls(e.Right, calls)
	case *ast.LogicalExpr:
		scanExprForCalls(e.Left, calls)
		scanExprForCalls(e.Right, calls)
	case *ast.ComparisonExpr:
		scanExprForCalls(e.Left, calls)
		scanExprForCalls(e.Right, calls)
	}
}

// collectAssignmentsToHoist extracts __assignment elements from the render tree
// that are direct children of regular elements (not inside conditionals/iterators).
// Only hoists assignments from non-conditional, non-iterator contexts.
func collectAssignmentsToHoist(els []ast.RenderNode) []*ast.RenderElement {
	var result []*ast.RenderElement
	for _, child := range els {
		if child.Element == nil {
			continue
		}
		el := child.Element
		// Don't descend into iterators or conditionals , those handle their own assignments
		if el.Iterator != nil || el.Condition != nil {
			continue
		}
		if el.Tag == "__assignment" {
			result = append(result, el)
		} else if el.Tag != "__fragment" {
			// Only recurse into regular elements (not fragments which might be conditional wrappers)
			result = append(result, collectAssignmentsToHoist(el.Children)...)
		}
	}
	return result
}

// removeHoistedAssignments removes __assignment elements that were hoisted,
// using the same logic as collectAssignmentsToHoist to ensure consistency.
func removeHoistedAssignments(children []ast.RenderNode) []ast.RenderNode {
	var result []ast.RenderNode
	for _, child := range children {
		if child.Element != nil {
			el := child.Element
			// Don't touch conditional or iterator subtrees , their assignments weren't hoisted
			if el.Iterator != nil || el.Condition != nil {
				result = append(result, child)
				continue
			}
			if el.Tag == "__assignment" {
				// This assignment was hoisted , skip it
				continue
			}
			if el.Tag != "__fragment" {
				// Recurse into regular elements (not fragments)
				el.Children = removeHoistedAssignments(el.Children)
			}
		}
		result = append(result, child)
	}
	return result
}

// hasAssignmentChildren checks if any direct children are __assignment elements.
func hasAssignmentChildren(el *ast.RenderElement) bool {
	for _, child := range el.Children {
		if child.Element != nil && child.Element.Tag == "__assignment" {
			return true
		}
	}
	return false
}

// hasDeepAssignmentChildren checks if any direct children are __assignment elements,
// only for regular elements (not __fragment, not conditional/iterator roots).
func hasDeepAssignmentChildren(el *ast.RenderElement) bool {
	if el.Tag == "__fragment" || el.Condition != nil || el.Iterator != nil {
		return false
	}
	for _, child := range el.Children {
		if child.Element != nil && child.Element.Tag == "__assignment" {
			return true
		}
	}
	return false
}

// hasAnyNestedAssignments recursively checks if any element in the tree has __assignment children.
// Used to determine if an iterator needs block body for nested assignments.
func hasAnyNestedAssignments(els []ast.RenderNode) bool {
	for _, child := range els {
		if child.Element == nil {
			continue
		}
		el := child.Element
		if el.Tag == "__assignment" {
			return true
		}
		if hasAnyNestedAssignments(el.Children) {
			return true
		}
		if hasAnyNestedAssignments(el.ElseChildren) {
			return true
		}
	}
	return false
}

// collectAllAssignments recursively collects __assignment elements from the tree,
// skipping conditional/iterator subtrees (their assignments are handled by IIFE/block body).
func collectAllAssignments(els []ast.RenderNode) []*ast.RenderElement {
	var result []*ast.RenderElement
	for _, child := range els {
		if child.Element == nil {
			continue
		}
		el := child.Element
		if el.Condition != nil || el.Iterator != nil {
			// Don't extract from conditional/iterator subtrees
			continue
		}
		if el.Tag == "__assignment" {
			result = append(result, el)
		} else {
			result = append(result, collectAllAssignments(el.Children)...)
		}
	}
	return result
}

// removeAllAssignments recursively removes __assignment elements from the tree,
// skipping conditional/iterator subtrees.
func removeAllAssignments(els []ast.RenderNode) []ast.RenderNode {
	var result []ast.RenderNode
	for _, child := range els {
		if child.Element == nil {
			result = append(result, child)
			continue
		}
		el := child.Element
		if el.Condition != nil || el.Iterator != nil {
			result = append(result, child)
			continue
		}
		if el.Tag == "__assignment" {
			continue // remove it
		}
		el.Children = removeAllAssignments(el.Children)
		result = append(result, child)
	}
	return result
}

// isStatementOnlyConditional checks if a conditional element contains ONLY __assignment children
// (no render elements). Such conditionals should be emitted as regular JS if-statements,
// not as JSX conditionals.
func isStatementOnlyConditional(el *ast.RenderElement) bool {
	if el.Condition == nil {
		return false
	}
	if len(el.Children) == 0 {
		return false
	}
	for _, child := range el.Children {
		if child.Element == nil || child.Element.Tag != "__assignment" {
			return false
		}
	}
	// Also check else children , if they have non-assignment elements, this is not statement-only
	for _, child := range el.ElseChildren {
		if child.Element == nil || child.Element.Tag != "__assignment" {
			return false
		}
	}
	return true
}

// emitStatementOnlyConditional generates a regular JS if/else statement for a conditional
// that only contains assignments (no render elements).
func (g *Generator) emitStatementOnlyConditional(el *ast.RenderElement, stateVars map[string]bool) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("if (%s) {\n", g.genExpr(el.Condition)))
	for _, child := range el.Children {
		if child.Element != nil && child.Element.Tag == "__assignment" {
			out.WriteString(g.genExpoElement(child.Element, 1, stateVars))
		}
	}
	if len(el.ElseChildren) > 0 {
		out.WriteString("} else {\n")
		for _, child := range el.ElseChildren {
			if child.Element != nil && child.Element.Tag == "__assignment" {
				out.WriteString(g.genExpoElement(child.Element, 1, stateVars))
			}
		}
	}
	out.WriteString("}\n")
	return out.String()
}

// genExpoElement generates JSX for a render element.
func (g *Generator) genExpoElement(el *ast.RenderElement, depth int, stateVars map[string]bool) string {
	indent := strings.Repeat("  ", depth)
	tag := mapRNTag(el.Tag)
	var out strings.Builder

	// Save/restore g.declared scope for iterators to prevent variable leaking across .map() callbacks
	if el.Iterator != nil {
		savedDeclared := make(map[string]bool)
		for k, v := range g.declared {
			savedDeclared[k] = v
		}
		defer func() { g.declared = savedDeclared }()
	}

	// Special handling for __assignment
	if el.Tag == "__assignment" {
		var name, valStr string
		if nameProp, ok := el.Props["__name"]; ok {
			if str, ok := nameProp.(*ast.StringLiteral); ok {
				name = str.Value
			}
		}
		if valProp, ok := el.Props["__value"]; ok {
			valStr = g.genExpoExpr(valProp)
		}
		// Check if it's a state variable
		if stateVars[name] {
			setter := "set" + strings.ToUpper(name[:1]) + name[1:]
			return fmt.Sprintf("%s%s(%s);\n", indent, setter, valStr)
		}
		// If already declared (e.g., in pre-render or outer scope), use reassignment
		if g.declared[name] {
			return fmt.Sprintf("%s%s = %s;\n", indent, name, valStr)
		}
		g.declared[name] = true
		return fmt.Sprintf("%sconst %s = %s;\n", indent, name, valStr)
	}

	// Special handling for __children
	if tag == "__children" || el.Tag == "__children" {
		out.WriteString(fmt.Sprintf("%s{children}\n", indent))
		return out.String()
	}

	// Special handling for __provider
	if tag == "__provider" || el.Tag == "__provider" {
		var contextName string
		if ctxProp, ok := el.Props["__context"]; ok {
			if str, ok := ctxProp.(*ast.StringLiteral); ok {
				contextName = str.Value
			}
		}
		valuePart := ""
		if valExpr, ok := el.Props["value"]; ok {
			valuePart = fmt.Sprintf(" value={%s}", g.genExpr(valExpr))
		}
		out.WriteString(fmt.Sprintf("%s<%s.Provider%s>\n", indent, contextName, valuePart))
		for _, child := range el.Children {
			if child.Element != nil {
				out.WriteString(g.genExpoElement(child.Element, depth+1, stateVars))
			}
		}
		out.WriteString(fmt.Sprintf("%s</%s.Provider>\n", indent, contextName))
		return out.String()
	}

	// Special handling for FlatList
	if tag == "FlatList" {
		return g.genExpoFlatList(el, depth, stateVars)
	}

	// Build props string
	var propParts []string
	for key, val := range el.Props {
		if key == "on" {
			continue
		}
		if key == "__nativeStyle" {
			if ident, ok := val.(*ast.Identifier); ok {
				propParts = append(propParts, fmt.Sprintf("style={styles.%s}", ident.Name))
			}
		} else if key == "__multiStyle" {
			if str, ok := val.(*ast.StringLiteral); ok {
				parts := strings.Split(str.Value, ",")
				var styleParts []string
				for _, p := range parts {
					name := strings.TrimSpace(p)
					if g.expoStyleKeys[name] {
						styleParts = append(styleParts, "styles."+name)
					} else {
						styleParts = append(styleParts, name)
					}
				}
				propParts = append(propParts, fmt.Sprintf("style={[%s]}", strings.Join(styleParts, ", ")))
			}
		} else if key == "__inlineStyle" {
			propParts = append(propParts, fmt.Sprintf("style={%s}", g.genExpr(val)))
		} else if key == "__pressStyle" {
			// pressStyle [base, pressed] → style={({ pressed }) => [styles.base, pressed && styles.pressed]}
			if str, ok := val.(*ast.StringLiteral); ok {
				parts := strings.Split(str.Value, ",")
				if len(parts) >= 2 {
					baseName := strings.TrimSpace(parts[0])
					pressedName := strings.TrimSpace(parts[1])
					baseRef := baseName
					pressedRef := pressedName
					if g.expoStyleKeys[baseName] {
						baseRef = "styles." + baseName
					}
					if g.expoStyleKeys[pressedName] {
						pressedRef = "styles." + pressedName
					}
					propParts = append(propParts, fmt.Sprintf("style={({ pressed }) => [%s, pressed && %s]}", baseRef, pressedRef))
				} else if len(parts) == 1 {
					name := strings.TrimSpace(parts[0])
					ref := name
					if g.expoStyleKeys[name] {
						ref = "styles." + name
					}
					propParts = append(propParts, fmt.Sprintf("style={%s}", ref))
				}
			}
		} else if key == "style" || strings.HasSuffix(key, "Style") {
			// Only add styles. prefix for known stylesheet keys
			if ident, ok := val.(*ast.Identifier); ok {
				if g.expoStyleKeys[ident.Name] {
					propParts = append(propParts, fmt.Sprintf("%s={styles.%s}", key, ident.Name))
				} else {
					propParts = append(propParts, fmt.Sprintf("%s={%s}", key, ident.Name))
				}
			} else {
				propParts = append(propParts, fmt.Sprintf("%s={%s}", key, g.genExpr(val)))
			}
		} else if strings.HasPrefix(key, "on") {
			// Event handler: onPress, onChangeText, etc.
			// Handlers that receive arguments (onChangeText, onValueChange, etc.) pass through directly
			if key == "onChangeText" || key == "onValueChange" || key == "onEndEditing" || key == "onSubmitEditing" || key == "onScroll" || key == "onLayout" || key == "onSelect" {
				propParts = append(propParts, fmt.Sprintf("%s={%s}", key, g.genExpr(val)))
			} else if _, isIdent := val.(*ast.Identifier); isIdent {
				// Plain function reference , pass directly so it receives arguments from the component
				propParts = append(propParts, fmt.Sprintf("%s={%s}", key, g.genExpr(val)))
			} else {
				propParts = append(propParts, fmt.Sprintf("%s={() => %s()}", key, g.genExpr(val)))
			}
		} else {
			// Check for boolean true props
			if ident, ok := val.(*ast.Identifier); ok && ident.Name == "true" {
				propParts = append(propParts, key)
			} else {
				propParts = append(propParts, fmt.Sprintf("%s={%s}", key, g.genExpr(val)))
			}
		}
	}

	propsStr := ""
	if len(propParts) > 0 {
		propsStr = " " + strings.Join(propParts, " ")
	}

	// Handle conditional rendering
	hasAssignments := hasAssignmentChildren(el)
	// Also check for deeply nested assignments (inside iterator children)
	hasNestedAssignments := el.Iterator != nil && hasAnyNestedAssignments(el.Children)
	condUsesIIFE := el.Condition != nil && hasAssignments
	if el.Condition != nil {
		if condUsesIIFE {
			// Wrap in IIFE to allow const statements: {(() => { stmts; return condition ? (...) : null; })()}
			out.WriteString(fmt.Sprintf("%s{(() => {\n", indent))
			depth++
			indent = strings.Repeat("  ", depth)
			// Emit assignment children as statements
			for _, child := range el.Children {
				if child.Element != nil && child.Element.Tag == "__assignment" {
					out.WriteString(g.genExpoElement(child.Element, depth, stateVars))
				}
			}
			if len(el.ElseChildren) > 0 {
				out.WriteString(fmt.Sprintf("%sreturn %s ? (\n", indent, g.genExpr(el.Condition)))
			} else {
				out.WriteString(fmt.Sprintf("%sif (!(%s)) return null;\n", indent, g.genExpr(el.Condition)))
				out.WriteString(fmt.Sprintf("%sreturn (\n", indent))
			}
			depth++
			indent = strings.Repeat("  ", depth)
		} else if len(el.ElseChildren) > 0 {
			// Ternary: {condition ? (...) : (...)}
			out.WriteString(fmt.Sprintf("%s{%s ? (\n", indent, g.genExpr(el.Condition)))
			depth++
			indent = strings.Repeat("  ", depth)
		} else {
			// Short-circuit: {condition && (...)}
			out.WriteString(fmt.Sprintf("%s{%s && (\n", indent, g.genExpr(el.Condition)))
			depth++
			indent = strings.Repeat("  ", depth)
		}
	}
	useIteratorBlockBody := hasAssignments || hasNestedAssignments
	if el.Iterator != nil {
		if useIteratorBlockBody {
			// Use block body: .map((item, __idx) => { stmts; return (...); })
			out.WriteString(fmt.Sprintf("%s{%s.map((%s, __idx) => {\n", indent, g.genExpr(el.Iterator.Iterable), el.Iterator.Variable))
			depth++
			indent = strings.Repeat("  ", depth)
			// Emit ALL assignment children (recursively) as statements first
			allAssignments := collectAllAssignments(el.Children)
			for _, assign := range allAssignments {
				out.WriteString(g.genExpoElement(assign, depth, stateVars))
			}
			// Remove all hoisted assignments from children
			el.Children = removeAllAssignments(el.Children)
			out.WriteString(fmt.Sprintf("%sreturn (\n", indent))
			depth++
			indent = strings.Repeat("  ", depth)
		} else {
			out.WriteString(fmt.Sprintf("%s{%s.map((%s, __idx) => (\n", indent, g.genExpr(el.Iterator.Iterable), el.Iterator.Variable))
			depth++
			indent = strings.Repeat("  ", depth)
		}
	}

	// For __fragment tags (conditionals, iterators), render children without wrapper
	if tag == "__fragment" || el.Tag == "__fragment" {
		if len(el.Children) == 0 {
			out.WriteString(fmt.Sprintf("%s<></>\n", indent))
		} else {
			// Collect non-assignment children for rendering
			var jsxChildren []ast.RenderNode
			for _, child := range el.Children {
				if child.Element != nil && child.Element.Tag == "__assignment" {
					// Skip assignments if inside an iterator or IIFE conditional (already emitted above)
					if el.Iterator != nil || condUsesIIFE {
						continue
					}
				}
				jsxChildren = append(jsxChildren, child)
			}
			if len(jsxChildren) == 0 {
				out.WriteString(fmt.Sprintf("%s<></>\n", indent))
			} else if len(jsxChildren) == 1 && jsxChildren[0].Element != nil && jsxChildren[0].Element.Condition == nil && jsxChildren[0].Element.Iterator == nil {
				// Single non-conditional, non-iterator child , render directly without fragment wrapper
				// Add key prop if inside an iterator
				child := jsxChildren[0].Element
				if el.Iterator != nil && child.Props != nil {
					child.Props["key"] = &ast.Identifier{Name: "__idx"}
				} else if el.Iterator != nil {
					child.Props = map[string]ast.Expression{"key": &ast.Identifier{Name: "__idx"}}
				}
				out.WriteString(g.genExpoElement(child, depth, stateVars))
			} else {
				// Use React.Fragment with key when inside an iterator
				if el.Iterator != nil {
					out.WriteString(fmt.Sprintf("%s<React.Fragment key={__idx}>\n", indent))
				} else {
					out.WriteString(fmt.Sprintf("%s<>\n", indent))
				}
				for _, child := range jsxChildren {
					if child.Element != nil {
						out.WriteString(g.genExpoElement(child.Element, depth+1, stateVars))
					} else if child.Text != nil {
						childIndent := strings.Repeat("  ", depth+1)
						textContent := g.genExpoTextContent(child.Text)
						out.WriteString(fmt.Sprintf("%s<Text>%s</Text>\n", childIndent, textContent))
					}
				}
				if el.Iterator != nil {
					out.WriteString(fmt.Sprintf("%s</React.Fragment>\n", indent))
				} else {
					out.WriteString(fmt.Sprintf("%s</>\n", indent))
				}
			}
		}
	} else if len(el.Children) == 0 {
		out.WriteString(fmt.Sprintf("%s<%s%s />\n", indent, tag, propsStr))
	} else {
		// Check if it's a single text child
		if len(el.Children) == 1 && el.Children[0].Text != nil && el.Children[0].Element == nil {
			textContent := g.genExpoTextContent(el.Children[0].Text)
			out.WriteString(fmt.Sprintf("%s<%s%s>%s</%s>\n", indent, tag, propsStr, textContent, tag))
		} else {
			out.WriteString(fmt.Sprintf("%s<%s%s>\n", indent, tag, propsStr))
			for _, child := range el.Children {
				if child.Element != nil {
					out.WriteString(g.genExpoElement(child.Element, depth+1, stateVars))
				} else if child.Text != nil {
					childIndent := strings.Repeat("  ", depth+1)
					textContent := g.genExpoTextContent(child.Text)
					// If inside a non-Text element, wrap text in <Text>
					if tag != "Text" {
						out.WriteString(fmt.Sprintf("%s<Text>%s</Text>\n", childIndent, textContent))
					} else {
						out.WriteString(fmt.Sprintf("%s%s\n", childIndent, textContent))
					}
				}
			}
			out.WriteString(fmt.Sprintf("%s</%s>\n", indent, tag))
		}
	}

	// Close iterator
	if el.Iterator != nil {
		if useIteratorBlockBody {
			depth--
			indent = strings.Repeat("  ", depth)
			out.WriteString(fmt.Sprintf("%s);\n", indent)) // close return (
			depth--
			indent = strings.Repeat("  ", depth)
			out.WriteString(fmt.Sprintf("%s})}\n", indent)) // close => { and .map(
		} else {
			depth--
			indent = strings.Repeat("  ", depth)
			out.WriteString(fmt.Sprintf("%s))}\n", indent))
		}
	}

	// Close conditional
	if el.Condition != nil {
		if condUsesIIFE {
			depth--
			indent = strings.Repeat("  ", depth)
			if len(el.ElseChildren) > 0 {
				out.WriteString(fmt.Sprintf("%s) : (\n", indent))
				for _, child := range el.ElseChildren {
					if child.Element != nil {
						out.WriteString(g.genExpoElement(child.Element, depth+1, stateVars))
					} else if child.Text != nil {
						out.WriteString(fmt.Sprintf("%s  %s\n", indent, g.genExpoTextContent(child.Text)))
					}
				}
				out.WriteString(fmt.Sprintf("%s);\n", indent))
			} else {
				out.WriteString(fmt.Sprintf("%s);\n", indent)) // close return (
			}
			depth--
			indent = strings.Repeat("  ", depth)
			out.WriteString(fmt.Sprintf("%s})()}\n", indent)) // close IIFE
		} else {
			depth--
			indent = strings.Repeat("  ", depth)
			if len(el.ElseChildren) > 0 {
				out.WriteString(fmt.Sprintf("%s) : (\n", indent))
				// Need fragment if multiple children, OR if single child is an iterator/conditional
				// (iterators/conditionals use {expr} wrapping which needs JSX context)
				needsElseFragment := len(el.ElseChildren) > 1
				if !needsElseFragment && len(el.ElseChildren) == 1 && el.ElseChildren[0].Element != nil {
					singleChild := el.ElseChildren[0].Element
					if singleChild.Iterator != nil || singleChild.Condition != nil {
						needsElseFragment = true
					}
				}
				if needsElseFragment {
					out.WriteString(fmt.Sprintf("%s  <>\n", indent))
				}
				for _, child := range el.ElseChildren {
					extraDepth := depth + 1
					if needsElseFragment {
						extraDepth = depth + 2
					}
					if child.Element != nil {
						out.WriteString(g.genExpoElement(child.Element, extraDepth, stateVars))
					} else if child.Text != nil {
						childIndent := strings.Repeat("  ", extraDepth)
						out.WriteString(fmt.Sprintf("%s%s\n", childIndent, g.genExpoTextContent(child.Text)))
					}
				}
				if needsElseFragment {
					out.WriteString(fmt.Sprintf("%s  </>\n", indent))
				}
				out.WriteString(fmt.Sprintf("%s)}\n", indent))
			} else {
				out.WriteString(fmt.Sprintf("%s)}\n", indent))
			}
		}
	}

	return out.String()
}

// genExpoTextContent generates text content for JSX, handling interpolation.
func (g *Generator) genExpoTextContent(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.StringLiteral:
		// Check for interpolation {var}
		val := e.Value
		if strings.Contains(val, "{") {
			// Convert {var} to {var} JSX expression, translating Quill keywords
			result := ""
			i := 0
			for i < len(val) {
				if val[i] == '{' {
					end := strings.Index(val[i:], "}")
					if end != -1 {
						exprStr := val[i+1 : i+end]
						result += "{" + quillToJSExpr(exprStr) + "}"
						i = i + end + 1
					} else {
						result += string(val[i])
						i++
					}
				} else {
					result += string(val[i])
					i++
				}
			}
			return result
		}
		return val
	default:
		return "{" + g.genExpr(expr) + "}"
	}
}

// genExpoStyles generates a StyleSheet.create() block with an optional name suffix.
func (g *Generator) genExpoStyles(s *ast.NativeStyleBlock) string {
	return g.genExpoStylesNamed(s, "styles")
}

// genExpoStylesNamed generates a StyleSheet.create() block with a specific variable name.
func (g *Generator) genExpoStylesNamed(s *ast.NativeStyleBlock, varName string) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("const %s = StyleSheet.create({\n", varName))
	for name, props := range s.Styles {
		out.WriteString(fmt.Sprintf("  %s: {\n", name))
		for _, prop := range props {
			out.WriteString(fmt.Sprintf("    %s: %s,\n", prop.Name, prop.Value))
		}
		out.WriteString("  },\n")
	}
	out.WriteString("});\n")
	return out.String()
}

// genExpoNavigation generates the React Navigation setup.
func (g *Generator) genExpoNavigation(nav *ast.NavigationBlock) string {
	var out strings.Builder

	navVar := "Stack"
	createFunc := "createNativeStackNavigator"
	switch nav.Type {
	case "tab":
		navVar = "Tab"
		createFunc = "createBottomTabNavigator"
	case "drawer":
		navVar = "Drawer"
		createFunc = "createDrawerNavigator"
	}

	out.WriteString(fmt.Sprintf("const %s = %s();\n\n", navVar, createFunc))
	out.WriteString("export default function App() {\n")
	out.WriteString("  return (\n")
	out.WriteString("    <NavigationContainer>\n")
	out.WriteString(fmt.Sprintf("      <%s.Navigator>\n", navVar))

	for _, screen := range nav.Screens {
		out.WriteString(fmt.Sprintf("        <%s.Screen name=\"%s\" component={%s} />\n", navVar, screen.Name, screen.Component))
	}

	out.WriteString(fmt.Sprintf("      </%s.Navigator>\n", navVar))
	out.WriteString("    </NavigationContainer>\n")
	out.WriteString("  );\n")
	out.WriteString("}\n")

	return out.String()
}

// genExpoFlatList generates a FlatList with renderItem and keyExtractor.
func (g *Generator) genExpoFlatList(el *ast.RenderElement, depth int, stateVars map[string]bool) string {
	indent := strings.Repeat("  ", depth)
	var out strings.Builder

	var propParts []string
	itemVar := "item"

	for key, val := range el.Props {
		if key == "data" {
			propParts = append(propParts, fmt.Sprintf("data={%s}", g.genExpr(val)))
		} else if key == "keyExtractor" || key == "key" {
			if ident, ok := val.(*ast.Identifier); ok {
				propParts = append(propParts, fmt.Sprintf("keyExtractor={(item) => item.%s}", ident.Name))
			} else {
				propParts = append(propParts, fmt.Sprintf("keyExtractor={(item) => %s}", g.genExpr(val)))
			}
		} else if key == "style" || key == "__nativeStyle" {
			if ident, ok := val.(*ast.Identifier); ok {
				propParts = append(propParts, fmt.Sprintf("style={styles.%s}", ident.Name))
			}
		} else if key != "on" {
			propParts = append(propParts, fmt.Sprintf("%s={%s}", key, g.genExpr(val)))
		}
	}

	// If there's an iterator, use its variable name
	if el.Iterator != nil {
		itemVar = el.Iterator.Variable
	}

	// Generate renderItem from children
	if len(el.Children) > 0 {
		var childJSX strings.Builder
		for _, child := range el.Children {
			if child.Element != nil {
				childJSX.WriteString(g.genExpoElement(child.Element, depth+2, stateVars))
			}
		}
		propParts = append(propParts, fmt.Sprintf("renderItem={({ item: %s }) => (\n%s%s)}", itemVar, childJSX.String(), strings.Repeat("  ", depth+1)))
	}

	// Add default keyExtractor if not specified
	hasKeyExtractor := false
	for _, p := range propParts {
		if strings.HasPrefix(p, "keyExtractor") {
			hasKeyExtractor = true
			break
		}
	}
	if !hasKeyExtractor {
		propParts = append(propParts, "keyExtractor={(item, index) => index.toString()}")
	}

	propsStr := ""
	if len(propParts) > 0 {
		propsStr = "\n"
		for _, p := range propParts {
			propsStr += indent + "  " + p + "\n"
		}
		propsStr += indent
	}

	out.WriteString(fmt.Sprintf("%s<FlatList%s/>\n", indent, propsStr))
	return out.String()
}

// mapRNTag maps Quill tag names to React Native component names.
func mapRNTag(tag string) string {
	// Dot-notation tags (Nav.NavigationContainer, Stack.Screen) pass through as-is
	if strings.Contains(tag, ".") {
		return tag
	}
	switch tag {
	case "view":
		return "View"
	case "text":
		return "Text"
	case "scroll":
		return "ScrollView"
	case "image":
		return "Image"
	case "input":
		return "TextInput"
	case "button":
		return "TouchableOpacity"
	case "touchable":
		return "TouchableOpacity"
	case "flat", "flatlist":
		return "FlatList"
	case "safe", "safearea":
		return "SafeAreaView"
	case "pressable":
		return "Pressable"
	case "modal":
		return "Modal"
	case "switch":
		return "Switch"
	case "activity":
		return "ActivityIndicator"
	default:
		// Capitalize first letter for custom components
		if len(tag) > 0 {
			return strings.ToUpper(tag[:1]) + tag[1:]
		}
		return tag
	}
}

// collectRNComponents scans render elements to find which RN components are used.
func (g *Generator) collectRNComponents(elements []ast.RenderElement, rnComponents map[string]bool) {
	for _, el := range elements {
		mapped := mapRNTag(el.Tag)
		if isBuiltInRN(mapped) {
			rnComponents[mapped] = true
		}
		for _, child := range el.Children {
			if child.Element != nil {
				g.collectRNComponents([]ast.RenderElement{*child.Element}, rnComponents)
			}
		}
		for _, child := range el.ElseChildren {
			if child.Element != nil {
				g.collectRNComponents([]ast.RenderElement{*child.Element}, rnComponents)
			}
		}
	}
}

// buildRNImports returns the sorted list of React Native imports needed.
func (g *Generator) buildRNImports(rnComponents map[string]bool) []string {
	// Always include StyleSheet if any component has native styles
	rnComponents["StyleSheet"] = true

	var imports []string
	for comp := range rnComponents {
		imports = append(imports, comp)
	}
	// Sort for deterministic output
	for i := 0; i < len(imports); i++ {
		for j := i + 1; j < len(imports); j++ {
			if imports[i] > imports[j] {
				imports[i], imports[j] = imports[j], imports[i]
			}
		}
	}
	return imports
}

// isBuiltInRN checks if a component name is a built-in React Native component.
func isBuiltInRN(name string) bool {
	builtins := map[string]bool{
		"View": true, "Text": true, "ScrollView": true, "Image": true,
		"TextInput": true, "TouchableOpacity": true, "FlatList": true,
		"SafeAreaView": true, "Pressable": true, "Modal": true,
		"Switch": true, "ActivityIndicator": true, "StyleSheet": true, "Alert": true,
	}
	return builtins[name]
}
