package codegen

import (
	"fmt"
	"quill/ast"
	"strings"
)

// NewExpo creates a Generator configured for React Native / Expo output.
func NewExpo() *Generator {
	return &Generator{
		declared:      make(map[string]bool),
		importedFiles: make(map[string]bool),
		expoMode:      true,
	}
}

// generateExpo generates a complete React Native / Expo source file from the AST.
func (g *Generator) generateExpo(program *ast.Program) string {
	var out strings.Builder

	// Collect all components, navigation blocks, and top-level statements
	var components []*ast.ComponentStatement
	var navBlocks []*ast.NavigationBlock
	var topLevel []ast.Statement
	rnComponents := map[string]bool{}

	for _, stmt := range program.Statements {
		switch s := stmt.(type) {
		case *ast.ComponentStatement:
			components = append(components, s)
		case *ast.NavigationBlock:
			navBlocks = append(navBlocks, s)
		case *ast.ContextDeclaration:
			// Will be handled in top-level code generation
			_ = s
			topLevel = append(topLevel, stmt)
		default:
			topLevel = append(topLevel, stmt)
		}
	}

	// Scan render bodies to find which RN components are used
	for _, comp := range components {
		g.collectRNComponents(comp.RenderBody, rnComponents)
	}

	// --- Scan components for hook and API usage ---
	hasEffects := false
	hasContexts := false
	hasMemos := false
	hasCallbacks := false
	usesAlert := false
	usesAsyncStorage := false

	for _, comp := range components {
		if len(comp.Effects) > 0 {
			hasEffects = true
		}
		if len(comp.Contexts) > 0 {
			hasContexts = true
		}
		if len(comp.Memos) > 0 {
			hasMemos = true
		}
		if len(comp.Callbacks) > 0 {
			hasCallbacks = true
		}
		// Scan methods, effects, and callbacks for alert/store/load calls
		allBodies := [][]ast.Statement{}
		for _, m := range comp.Methods {
			allBodies = append(allBodies, m.Body)
		}
		for _, e := range comp.Effects {
			allBodies = append(allBodies, e.Body)
		}
		for _, cb := range comp.Callbacks {
			allBodies = append(allBodies, cb.Body)
		}
		for _, body := range allBodies {
			for _, stmt := range body {
				if exprStmt, ok := stmt.(*ast.ExprStatement); ok {
					if call, ok := exprStmt.Expr.(*ast.CallExpr); ok {
						if ident, ok := call.Function.(*ast.Identifier); ok {
							switch ident.Name {
							case "alert":
								usesAlert = true
							case "store", "removeStore", "load":
								usesAsyncStorage = true
							}
						}
					}
				}
				// Check assign statements for load() calls
				if assign, ok := stmt.(*ast.AssignStatement); ok {
					if call, ok := assign.Value.(*ast.CallExpr); ok {
						if ident, ok := call.Function.(*ast.Identifier); ok && ident.Name == "load" {
							usesAsyncStorage = true
						}
					}
					if awaitExpr, ok := assign.Value.(*ast.AwaitExpr); ok {
						if call, ok := awaitExpr.Expr.(*ast.CallExpr); ok {
							if ident, ok := call.Function.(*ast.Identifier); ok && ident.Name == "load" {
								usesAsyncStorage = true
							}
						}
					}
				}
			}
		}
	}

	// Add Alert to RN components if alert() is used
	if usesAlert {
		rnComponents["Alert"] = true
	}

	// --- Imports ---
	out.WriteString("// Generated by Quill (Expo mode)\n")
	out.WriteString("import React, { useState")
	if hasEffects {
		out.WriteString(", useEffect")
	}
	if hasContexts {
		out.WriteString(", useContext")
	}
	if hasMemos {
		out.WriteString(", useMemo")
	}
	if hasCallbacks {
		out.WriteString(", useCallback")
	}
	out.WriteString(" } from 'react';\n")

	// Import React Native components
	rnImports := g.buildRNImports(rnComponents)
	if len(rnImports) > 0 {
		out.WriteString(fmt.Sprintf("import { %s } from 'react-native';\n", strings.Join(rnImports, ", ")))
	}

	// Import AsyncStorage if store/load/removeStore is used
	if usesAsyncStorage {
		out.WriteString("import AsyncStorage from '@react-native-async-storage/async-storage';\n")
	}

	// Import navigation if needed
	if len(navBlocks) > 0 {
		out.WriteString("import { NavigationContainer } from '@react-navigation/native';\n")
		for _, nav := range navBlocks {
			switch nav.Type {
			case "tab":
				out.WriteString("import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';\n")
			case "drawer":
				out.WriteString("import { createDrawerNavigator } from '@react-navigation/drawer';\n")
			default:
				out.WriteString("import { createNativeStackNavigator } from '@react-navigation/native-stack';\n")
			}
		}
	}

	out.WriteString("\n")

	// Generate top-level non-component code
	for _, stmt := range topLevel {
		// Handle ContextDeclaration inline
		if ctx, ok := stmt.(*ast.ContextDeclaration); ok {
			out.WriteString(fmt.Sprintf("const %s = React.createContext(%s);\n", ctx.Name, g.genExpr(ctx.DefaultValue)))
			continue
		}
		// Handle UseStatement with ESM import syntax
		if useStmt, ok := stmt.(*ast.UseStatement); ok {
			if useStmt.Alias != "" {
				out.WriteString(fmt.Sprintf("import * as %s from '%s';\n", useStmt.Alias, useStmt.Path))
			} else {
				out.WriteString(fmt.Sprintf("import '%s';\n", useStmt.Path))
			}
			continue
		}
		// Handle FromUseStatement with ESM destructured imports
		if fromStmt, ok := stmt.(*ast.FromUseStatement); ok {
			names := strings.Join(fromStmt.Names, ", ")
			out.WriteString(fmt.Sprintf("import { %s } from '%s';\n", names, fromStmt.Path))
			continue
		}
		code := g.genStmt(stmt)
		if strings.TrimSpace(code) != "" {
			out.WriteString(code)
			out.WriteString("\n")
		}
	}

	// --- Generate each component ---
	for _, comp := range components {
		out.WriteString(g.genExpoComponent(comp))
		out.WriteString("\n")
	}

	// --- Generate navigation setup ---
	for _, nav := range navBlocks {
		out.WriteString(g.genExpoNavigation(nav))
		out.WriteString("\n")
	}

	return out.String()
}

// genExpoComponent generates a React functional component with hooks.
func (g *Generator) genExpoComponent(s *ast.ComponentStatement) string {
	var out strings.Builder

	// Track state variable names for setter rewriting
	stateVars := map[string]bool{}
	for _, st := range s.States {
		stateVars[st.Name] = true
	}

	// Build props
	propsStr := ""
	if s.HasProps && len(s.Props) > 0 {
		propsStr = "{ " + strings.Join(s.Props, ", ") + " }"
	} else if s.HasProps {
		propsStr = "props"
	}

	out.WriteString(fmt.Sprintf("export default function %s(%s) {\n", s.Name, propsStr))

	// --- State declarations as useState hooks ---
	for _, st := range s.States {
		setter := "set" + strings.ToUpper(st.Name[:1]) + st.Name[1:]
		out.WriteString(fmt.Sprintf("  const [%s, %s] = useState(%s);\n", st.Name, setter, g.genExpr(st.Value)))
	}

	if len(s.States) > 0 {
		out.WriteString("\n")
	}

	// --- Context hooks ---
	for _, ctx := range s.Contexts {
		out.WriteString(fmt.Sprintf("  const %s = useContext(%s);\n", ctx.Alias, ctx.ContextName))
	}

	// --- Memo hooks ---
	for _, m := range s.Memos {
		deps := "[]"
		if len(m.Dependencies) > 0 {
			deps = "[" + strings.Join(m.Dependencies, ", ") + "]"
		}
		out.WriteString(fmt.Sprintf("  const %s = useMemo(() => %s, %s);\n", m.Name, g.genExpr(m.Value), deps))
	}

	// --- Callback hooks ---
	for _, cb := range s.Callbacks {
		deps := "[]"
		if len(cb.Dependencies) > 0 {
			deps = "[" + strings.Join(cb.Dependencies, ", ") + "]"
		}
		params := strings.Join(cb.Params, ", ")
		g.indent = 2
		body := g.genBlock(cb.Body)
		g.indent = 0
		out.WriteString(fmt.Sprintf("  const %s = useCallback((%s) => {\n%s  }, %s);\n", cb.Name, params, body, deps))
	}

	if len(s.Contexts) > 0 || len(s.Memos) > 0 || len(s.Callbacks) > 0 {
		out.WriteString("\n")
	}

	// --- Effects ---
	for _, effect := range s.Effects {
		out.WriteString("  useEffect(() => {\n")
		g.indent = 2
		for _, stmt := range effect.Body {
			out.WriteString(g.genExpoStmt(stmt, stateVars))
			out.WriteString("\n")
		}
		g.indent = 0
		if len(effect.Dependencies) > 0 {
			out.WriteString(fmt.Sprintf("  }, [%s]);\n", strings.Join(effect.Dependencies, ", ")))
		} else {
			out.WriteString("  }, []);\n")
		}
		out.WriteString("\n")
	}

	// --- Methods ---
	for _, method := range s.Methods {
		params := strings.Join(method.Params, ", ")
		out.WriteString(fmt.Sprintf("  const %s = (%s) => {\n", method.Name, params))
		g.indent = 2
		for _, stmt := range method.Body {
			out.WriteString(g.genExpoStmt(stmt, stateVars))
			out.WriteString("\n")
		}
		g.indent = 0
		out.WriteString("  };\n\n")
	}

	// --- Render ---
	out.WriteString("  return (\n")
	if len(s.RenderBody) == 1 {
		out.WriteString(g.genExpoElement(&s.RenderBody[0], 2, stateVars))
	} else if len(s.RenderBody) > 1 {
		out.WriteString("    <>\n")
		for i := range s.RenderBody {
			out.WriteString(g.genExpoElement(&s.RenderBody[i], 3, stateVars))
		}
		out.WriteString("    </>\n")
	} else {
		out.WriteString("    <View />\n")
	}
	out.WriteString("  );\n")
	out.WriteString("}\n")

	// --- StyleSheet ---
	if s.NativeStyles != nil {
		out.WriteString("\n")
		out.WriteString(g.genExpoStyles(s.NativeStyles))
	}

	return out.String()
}

// genExpoStmt generates a statement, rewriting state variable assignments to setter calls.
func (g *Generator) genExpoStmt(stmt ast.Statement, stateVars map[string]bool) string {
	prefix := strings.Repeat("  ", g.indent)
	switch s := stmt.(type) {
	case *ast.AssignStatement:
		if stateVars[s.Name] {
			setter := "set" + strings.ToUpper(s.Name[:1]) + s.Name[1:]
			return fmt.Sprintf("%s%s(%s);", prefix, setter, g.genExpr(s.Value))
		}
		// Handle load() pattern
		if call, ok := s.Value.(*ast.CallExpr); ok {
			if ident, ok := call.Function.(*ast.Identifier); ok && ident.Name == "load" {
				if len(call.Args) >= 1 {
					return fmt.Sprintf("%sconst %s = JSON.parse(await AsyncStorage.getItem(%s));", prefix, s.Name, g.genExpr(call.Args[0]))
				}
			}
		}
		// Handle await load() pattern (wrapped in AwaitExpr)
		if awaitExpr, ok := s.Value.(*ast.AwaitExpr); ok {
			if call, ok := awaitExpr.Expr.(*ast.CallExpr); ok {
				if ident, ok := call.Function.(*ast.Identifier); ok && ident.Name == "load" {
					if len(call.Args) >= 1 {
						return fmt.Sprintf("%sconst %s = JSON.parse(await AsyncStorage.getItem(%s));", prefix, s.Name, g.genExpr(call.Args[0]))
					}
				}
			}
		}
		return g.genStmt(stmt)
	case *ast.ExprStatement:
		if call, ok := s.Expr.(*ast.CallExpr); ok {
			if ident, ok := call.Function.(*ast.Identifier); ok {
				switch ident.Name {
				case "alert":
					args := make([]string, len(call.Args))
					for i, a := range call.Args {
						args[i] = g.genExpr(a)
					}
					return fmt.Sprintf("%sAlert.alert(%s);", prefix, strings.Join(args, ", "))
				case "store":
					if len(call.Args) >= 2 {
						return fmt.Sprintf("%sawait AsyncStorage.setItem(%s, JSON.stringify(%s));", prefix, g.genExpr(call.Args[0]), g.genExpr(call.Args[1]))
					}
				case "removeStore":
					if len(call.Args) >= 1 {
						return fmt.Sprintf("%sawait AsyncStorage.removeItem(%s);", prefix, g.genExpr(call.Args[0]))
					}
				}
			}
		}
		return g.genStmt(stmt)
	case *ast.NavigateStatement:
		if s.Params != nil {
			return fmt.Sprintf("%snavigation.navigate(\"%s\", %s);", prefix, s.Screen, g.genExpr(s.Params))
		}
		return fmt.Sprintf("%snavigation.navigate(\"%s\");", prefix, s.Screen)
	case *ast.SayStatement:
		return fmt.Sprintf("%sconsole.log(%s);", prefix, g.genExpr(s.Value))
	default:
		return g.genStmt(stmt)
	}
}

// genExpoElement generates JSX for a render element.
func (g *Generator) genExpoElement(el *ast.RenderElement, depth int, stateVars map[string]bool) string {
	indent := strings.Repeat("  ", depth)
	tag := mapRNTag(el.Tag)

	// Special handling for FlatList
	if tag == "FlatList" {
		return g.genExpoFlatList(el, depth, stateVars)
	}

	var out strings.Builder

	// Build props string
	var propParts []string
	for key, val := range el.Props {
		if key == "on" {
			continue
		}
		if key == "__nativeStyle" {
			if ident, ok := val.(*ast.Identifier); ok {
				propParts = append(propParts, fmt.Sprintf("style={styles.%s}", ident.Name))
			}
		} else if key == "style" {
			if ident, ok := val.(*ast.Identifier); ok {
				propParts = append(propParts, fmt.Sprintf("style={styles.%s}", ident.Name))
			} else {
				propParts = append(propParts, fmt.Sprintf("style={%s}", g.genExpr(val)))
			}
		} else if strings.HasPrefix(key, "on") {
			// Event handler: onPress, onChangeText, etc.
			propParts = append(propParts, fmt.Sprintf("%s={() => %s()}", key, g.genExpr(val)))
		} else {
			propParts = append(propParts, fmt.Sprintf("%s={%s}", key, g.genExpr(val)))
		}
	}

	propsStr := ""
	if len(propParts) > 0 {
		propsStr = " " + strings.Join(propParts, " ")
	}

	// Handle conditional rendering
	if el.Condition != nil {
		out.WriteString(fmt.Sprintf("%s{%s && (\n", indent, g.genExpr(el.Condition)))
		depth++
		indent = strings.Repeat("  ", depth)
	}

	// Handle iterator
	if el.Iterator != nil {
		out.WriteString(fmt.Sprintf("%s{%s.map((%s, __idx) => (\n", indent, g.genExpr(el.Iterator.Iterable), el.Iterator.Variable))
		depth++
		indent = strings.Repeat("  ", depth)
	}

	if len(el.Children) == 0 {
		out.WriteString(fmt.Sprintf("%s<%s%s />\n", indent, tag, propsStr))
	} else {
		// Check if it's a single text child
		if len(el.Children) == 1 && el.Children[0].Text != nil && el.Children[0].Element == nil {
			textContent := g.genExpoTextContent(el.Children[0].Text)
			out.WriteString(fmt.Sprintf("%s<%s%s>%s</%s>\n", indent, tag, propsStr, textContent, tag))
		} else {
			out.WriteString(fmt.Sprintf("%s<%s%s>\n", indent, tag, propsStr))
			for _, child := range el.Children {
				if child.Element != nil {
					out.WriteString(g.genExpoElement(child.Element, depth+1, stateVars))
				} else if child.Text != nil {
					childIndent := strings.Repeat("  ", depth+1)
					textContent := g.genExpoTextContent(child.Text)
					// If inside a non-Text element, wrap text in <Text>
					if tag != "Text" {
						out.WriteString(fmt.Sprintf("%s<Text>%s</Text>\n", childIndent, textContent))
					} else {
						out.WriteString(fmt.Sprintf("%s%s\n", childIndent, textContent))
					}
				}
			}
			out.WriteString(fmt.Sprintf("%s</%s>\n", indent, tag))
		}
	}

	// Close iterator
	if el.Iterator != nil {
		depth--
		indent = strings.Repeat("  ", depth)
		out.WriteString(fmt.Sprintf("%s))}\n", indent))
	}

	// Close conditional
	if el.Condition != nil {
		depth--
		indent = strings.Repeat("  ", depth)
		out.WriteString(fmt.Sprintf("%s)}\n", indent))
	}

	return out.String()
}

// genExpoTextContent generates text content for JSX, handling interpolation.
func (g *Generator) genExpoTextContent(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.StringLiteral:
		// Check for interpolation {var}
		val := e.Value
		if strings.Contains(val, "{") {
			// Convert {var} to {var} JSX expression
			result := ""
			i := 0
			for i < len(val) {
				if val[i] == '{' {
					end := strings.Index(val[i:], "}")
					if end != -1 {
						exprStr := val[i+1 : i+end]
						result += "{" + exprStr + "}"
						i = i + end + 1
					} else {
						result += string(val[i])
						i++
					}
				} else {
					result += string(val[i])
					i++
				}
			}
			return result
		}
		return val
	default:
		return "{" + g.genExpr(expr) + "}"
	}
}

// genExpoStyles generates a StyleSheet.create() block.
func (g *Generator) genExpoStyles(s *ast.NativeStyleBlock) string {
	var out strings.Builder
	out.WriteString("const styles = StyleSheet.create({\n")
	for name, props := range s.Styles {
		out.WriteString(fmt.Sprintf("  %s: {\n", name))
		for _, prop := range props {
			out.WriteString(fmt.Sprintf("    %s: %s,\n", prop.Name, prop.Value))
		}
		out.WriteString("  },\n")
	}
	out.WriteString("});\n")
	return out.String()
}

// genExpoNavigation generates the React Navigation setup.
func (g *Generator) genExpoNavigation(nav *ast.NavigationBlock) string {
	var out strings.Builder

	navVar := "Stack"
	createFunc := "createNativeStackNavigator"
	switch nav.Type {
	case "tab":
		navVar = "Tab"
		createFunc = "createBottomTabNavigator"
	case "drawer":
		navVar = "Drawer"
		createFunc = "createDrawerNavigator"
	}

	out.WriteString(fmt.Sprintf("const %s = %s();\n\n", navVar, createFunc))
	out.WriteString("export default function App() {\n")
	out.WriteString("  return (\n")
	out.WriteString("    <NavigationContainer>\n")
	out.WriteString(fmt.Sprintf("      <%s.Navigator>\n", navVar))

	for _, screen := range nav.Screens {
		out.WriteString(fmt.Sprintf("        <%s.Screen name=\"%s\" component={%s} />\n", navVar, screen.Name, screen.Component))
	}

	out.WriteString(fmt.Sprintf("      </%s.Navigator>\n", navVar))
	out.WriteString("    </NavigationContainer>\n")
	out.WriteString("  );\n")
	out.WriteString("}\n")

	return out.String()
}

// genExpoFlatList generates a FlatList with renderItem and keyExtractor.
func (g *Generator) genExpoFlatList(el *ast.RenderElement, depth int, stateVars map[string]bool) string {
	indent := strings.Repeat("  ", depth)
	var out strings.Builder

	var propParts []string
	itemVar := "item"

	for key, val := range el.Props {
		if key == "data" {
			propParts = append(propParts, fmt.Sprintf("data={%s}", g.genExpr(val)))
		} else if key == "keyExtractor" || key == "key" {
			if ident, ok := val.(*ast.Identifier); ok {
				propParts = append(propParts, fmt.Sprintf("keyExtractor={(item) => item.%s}", ident.Name))
			} else {
				propParts = append(propParts, fmt.Sprintf("keyExtractor={(item) => %s}", g.genExpr(val)))
			}
		} else if key == "style" || key == "__nativeStyle" {
			if ident, ok := val.(*ast.Identifier); ok {
				propParts = append(propParts, fmt.Sprintf("style={styles.%s}", ident.Name))
			}
		} else if key != "on" {
			propParts = append(propParts, fmt.Sprintf("%s={%s}", key, g.genExpr(val)))
		}
	}

	// If there's an iterator, use its variable name
	if el.Iterator != nil {
		itemVar = el.Iterator.Variable
	}

	// Generate renderItem from children
	if len(el.Children) > 0 {
		var childJSX strings.Builder
		for _, child := range el.Children {
			if child.Element != nil {
				childJSX.WriteString(g.genExpoElement(child.Element, depth+2, stateVars))
			}
		}
		propParts = append(propParts, fmt.Sprintf("renderItem={({ item: %s }) => (\n%s%s)}", itemVar, childJSX.String(), strings.Repeat("  ", depth+1)))
	}

	// Add default keyExtractor if not specified
	hasKeyExtractor := false
	for _, p := range propParts {
		if strings.HasPrefix(p, "keyExtractor") {
			hasKeyExtractor = true
			break
		}
	}
	if !hasKeyExtractor {
		propParts = append(propParts, "keyExtractor={(item, index) => index.toString()}")
	}

	propsStr := ""
	if len(propParts) > 0 {
		propsStr = "\n"
		for _, p := range propParts {
			propsStr += indent + "  " + p + "\n"
		}
		propsStr += indent
	}

	out.WriteString(fmt.Sprintf("%s<FlatList%s/>\n", indent, propsStr))
	return out.String()
}

// mapRNTag maps Quill tag names to React Native component names.
func mapRNTag(tag string) string {
	switch tag {
	case "view":
		return "View"
	case "text":
		return "Text"
	case "scroll":
		return "ScrollView"
	case "image":
		return "Image"
	case "input":
		return "TextInput"
	case "button":
		return "TouchableOpacity"
	case "touchable":
		return "TouchableOpacity"
	case "flat", "flatlist":
		return "FlatList"
	case "safe", "safearea":
		return "SafeAreaView"
	case "pressable":
		return "Pressable"
	case "modal":
		return "Modal"
	case "switch":
		return "Switch"
	case "activity":
		return "ActivityIndicator"
	default:
		// Capitalize first letter for custom components
		if len(tag) > 0 {
			return strings.ToUpper(tag[:1]) + tag[1:]
		}
		return tag
	}
}

// collectRNComponents scans render elements to find which RN components are used.
func (g *Generator) collectRNComponents(elements []ast.RenderElement, rnComponents map[string]bool) {
	for _, el := range elements {
		mapped := mapRNTag(el.Tag)
		if isBuiltInRN(mapped) {
			rnComponents[mapped] = true
		}
		for _, child := range el.Children {
			if child.Element != nil {
				g.collectRNComponents([]ast.RenderElement{*child.Element}, rnComponents)
			}
		}
	}
}

// buildRNImports returns the sorted list of React Native imports needed.
func (g *Generator) buildRNImports(rnComponents map[string]bool) []string {
	// Always include StyleSheet if any component has native styles
	rnComponents["StyleSheet"] = true

	var imports []string
	for comp := range rnComponents {
		imports = append(imports, comp)
	}
	// Sort for deterministic output
	for i := 0; i < len(imports); i++ {
		for j := i + 1; j < len(imports); j++ {
			if imports[i] > imports[j] {
				imports[i], imports[j] = imports[j], imports[i]
			}
		}
	}
	return imports
}

// isBuiltInRN checks if a component name is a built-in React Native component.
func isBuiltInRN(name string) bool {
	builtins := map[string]bool{
		"View": true, "Text": true, "ScrollView": true, "Image": true,
		"TextInput": true, "TouchableOpacity": true, "FlatList": true,
		"SafeAreaView": true, "Pressable": true, "Modal": true,
		"Switch": true, "ActivityIndicator": true, "StyleSheet": true, "Alert": true,
	}
	return builtins[name]
}
