package stdlib

const Runtime = `
// Quill Standard Library
const __contains = (a, b) => { if (typeof a === 'string') return a.includes(b); if (Array.isArray(a)) return a.includes(b); return false; };
let __test_passed = 0;
let __test_failed = 0;
const read = (path) => require('fs').readFileSync(path, 'utf8');
const write = (path, content) => require('fs').writeFileSync(path, content);
const append_file = (path, content) => require('fs').appendFileSync(path, content);
const exists = (path) => require('fs').existsSync(path);
const length = (x) => x.length;
const join = (arr, sep) => arr.join(sep === undefined ? ', ' : sep);
const split = (str, sep) => str.split(sep);
const round = (n) => Math.round(n);
const floor = (n) => Math.floor(n);
const ceil = (n) => Math.ceil(n);
const abs = (n) => Math.abs(n);
const random = () => Math.random();
const randomInt = (a, b) => Math.floor(Math.random() * (b - a + 1)) + a;
const toNumber = (x) => Number(x);
const toText = (x) => String(x);
const keys = (obj) => Object.keys(obj);
const values = (obj) => Object.values(obj);
const typeOf = (x) => { if (Array.isArray(x)) return 'list'; if (x === null) return 'nothing'; return typeof x; };
const range = (start, end) => Array.from({length: end - start}, (_, i) => i + start);
const sort = (arr) => [...arr].sort((a, b) => a > b ? 1 : -1);
const reverse = (arr) => [...arr].reverse();
const unique = (arr) => [...new Set(arr)];
const sum = (arr) => arr.reduce((a, b) => a + b, 0);
const smallest = (...args) => Math.min(...args.flat());
const largest = (...args) => Math.max(...args.flat());
const trim = (s) => s.trim();
const upper = (s) => s.toUpperCase();
const lower = (s) => s.toLowerCase();
const replace_text = (s, old_text, new_text) => s.replaceAll(old_text, new_text);
const startsWith = (s, prefix) => s.startsWith(prefix);
const endsWith = (s, suffix) => s.endsWith(suffix);
const now = () => new Date().toISOString();
const today = () => new Date().toISOString().split('T')[0];
const wait = (ms) => { const end = Date.now() + ms; while (Date.now() < end) {} };
const parseJSON = (s) => JSON.parse(s);
const toJSON = (x) => JSON.stringify(x, null, 2);
const prompt = (msg) => { const rl = require('readline').createInterface({input: process.stdin, output: process.stdout}); return new Promise(r => rl.question(msg || '> ', a => { rl.close(); r(a); })); };
const exit = (code) => process.exit(code || 0);
const filter = (arr, fn) => arr.filter(fn);
const map_list = (arr, fn) => arr.map(fn);
const find = (arr, fn) => arr.find(fn);
const every = (arr, fn) => arr.every(fn);
const some = (arr, fn) => arr.some(fn);
const reduce = (arr, fn, init) => init !== undefined ? arr.reduce(fn, init) : arr.reduce(fn);
const flat = (arr) => arr.flat();
const includes = (arr, item) => arr.includes(item);
const indexOf = (arr, item) => arr.indexOf(item);
const slice = (arr, start, end) => end !== undefined ? arr.slice(start, end) : arr.slice(start);
const push = (arr, ...items) => { arr.push(...items); return arr; };
const pop = (arr) => arr.pop();
const concat = (a, b) => [...a, ...b];
const zip = (a, b) => a.map((x, i) => [x, b[i]]);
const countWhere = (arr, fn) => arr.filter(fn).length;
const groupBy = (arr, fn) => arr.reduce((acc, item) => { const key = fn(item); (acc[key] = acc[key] || []).push(item); return acc; }, {});
const fetchURL = async (url, options) => { const resp = await fetch(url, options); const text = await resp.text(); try { return JSON.parse(text); } catch { return text; } };
const fetchJSON = async (url) => { const resp = await fetch(url); return resp.json(); };
const postJSON = async (url, body) => { const resp = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); return resp.json(); };
const createServer = () => { const http = require('http'); const routes = {}; const srv = { get: (path, handler) => { routes['GET ' + path] = handler; return srv; }, post: (path, handler) => { routes['POST ' + path] = handler; return srv; }, put: (path, handler) => { routes['PUT ' + path] = handler; return srv; }, delete_route: (path, handler) => { routes['DELETE ' + path] = handler; return srv; }, listen: (port, cb) => { const server = http.createServer((req, res) => { const url = req.url.split('?')[0]; const key = req.method + ' ' + url; const handler = routes[key]; if (handler) { try { const result = typeof handler === 'function' ? handler(req, res) : handler; if (!res.headersSent) { const body = typeof result === 'string' ? result : JSON.stringify(result); res.writeHead(200, { 'Content-Type': typeof result === 'string' ? 'text/html' : 'application/json' }); res.end(body); } } catch(e) { res.writeHead(500); res.end('Internal Server Error'); } } else { res.writeHead(404); res.end('Not Found'); } }); server.listen(port, () => { if (cb) cb(); }); return server; } }; return srv; };
const listFiles = (dir) => require('fs').readdirSync(dir);
const listFilesDeep = (dir) => { const fs = require('fs'); const path = require('path'); const results = []; const walk = (d) => { for (const f of fs.readdirSync(d)) { const full = path.join(d, f); if (fs.statSync(full).isDirectory()) walk(full); else results.push(full); } }; walk(dir); return results; };
const fileInfo = (p) => { const s = require('fs').statSync(p); return { size: s.size, modified: s.mtime.toISOString(), created: s.birthtime.toISOString(), isFile: s.isFile(), isDir: s.isDirectory() }; };
const deleteFile = (p) => require('fs').unlinkSync(p);
const copyFile = (src, dest) => require('fs').copyFileSync(src, dest);
const moveFile = (src, dest) => require('fs').renameSync(src, dest);
const makeDir = (p) => require('fs').mkdirSync(p, { recursive: true });
const watchFiles = (p, callback) => { require('fs').watch(p, { recursive: true }, (event, filename) => { callback(filename || p, event); }); };
const fileExists = (p) => require('fs').existsSync(p);
const readLines = (p) => require('fs').readFileSync(p, 'utf8').split('\n');
const writeLines = (p, lines) => require('fs').writeFileSync(p, lines.join('\n'));
const readJSON = (p) => JSON.parse(require('fs').readFileSync(p, 'utf8'));
const writeJSON = (p, data) => require('fs').writeFileSync(p, JSON.stringify(data, null, 2));
const currentDir = () => process.cwd();
const homePath = () => require('os').homedir();
const joinPath = (...parts) => require('path').join(...parts);
const fileName = (p) => require('path').basename(p);
const fileExtension = (p) => require('path').extname(p);
const parentDir = (p) => require('path').dirname(p);
`
