// Generated by Plain
const __contains = (a, b) => { if (typeof a === 'string') return a.includes(b); if (Array.isArray(a)) return a.includes(b); return false; };

let name = "World";
console.log(`Hello, ${name}!`);
let age = 25;
let price = 9.99;
let active = true;
let total = (price * 3);
console.log(`Total: ${total}`);
let colors = ["red", "green", "blue"];
console.log(colors);
for (const color of colors) {
  console.log(`Color: ${color}`);
}
if ((age > 18)) {
  console.log("You are an adult");
} else {
  console.log("You are young");
}
function add(a, b) {
  return (a + b);
}
let result = add(10, 20);
console.log(`10 + 20 = ${result}`);
function checkAge(years) {
  if ((years < 13)) {
    console.log("Child");
  } else if ((years < 18)) {
    console.log("Teenager");
  } else {
    console.log("Adult");
  }
}
checkAge(10);
checkAge(15);
checkAge(25);
let hasTicket = true;
let isVIP = false;
if ((hasTicket && (!isVIP))) {
  console.log("Regular entry");
}
let greeting = "Hello World";
if (__contains(greeting, "World")) {
  console.log("Found World!");
}
let count = 0;
while ((count < 5)) {
  console.log(`Count: ${count}`);
  count = (count + 1);
}
console.log("Done!");
