package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DeployConfig holds configuration for deploying a Quill app.
type DeployConfig struct {
	AppName   string
	Entry     string
	Port      int
	Env       string // "preview" or "production"
	OutputDir string
}

// Deployer handles packaging and deploying Quill applications.
type Deployer struct {
	config DeployConfig
}

// NewDeployer creates a new Deployer with the given config.
func NewDeployer(config DeployConfig) *Deployer {
	if config.Port == 0 {
		config.Port = 3000
	}
	if config.Env == "" {
		config.Env = "production"
	}
	if config.OutputDir == "" {
		config.OutputDir = "dist"
	}
	if config.AppName == "" {
		config.AppName = "quill-app"
	}
	if config.Entry == "" {
		config.Entry = "main.quill"
	}
	return &Deployer{config: config}
}

// PrepareBundle compiles all .quill files and bundles into a single directory
// with package.json, server.js, and static assets.
func (d *Deployer) PrepareBundle(compiledJS string) (string, error) {
	outDir := d.config.OutputDir

	// Create output directory
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return "", fmt.Errorf("could not create output directory: %w", err)
	}

	// Create public directory for static assets
	publicDir := filepath.Join(outDir, "public")
	if err := os.MkdirAll(publicDir, 0755); err != nil {
		return "", fmt.Errorf("could not create public directory: %w", err)
	}

	// Write server.js
	serverJS := d.generateServerJS(compiledJS)
	if err := os.WriteFile(filepath.Join(outDir, "server.js"), []byte(serverJS), 0644); err != nil {
		return "", fmt.Errorf("could not write server.js: %w", err)
	}

	// Write package.json
	packageJSON := d.GeneratePackageJSON()
	if err := os.WriteFile(filepath.Join(outDir, "package.json"), []byte(packageJSON), 0644); err != nil {
		return "", fmt.Errorf("could not write package.json: %w", err)
	}

	// Write Dockerfile
	dockerfile := d.GenerateDockerfile()
	if err := os.WriteFile(filepath.Join(outDir, "Dockerfile"), []byte(dockerfile), 0644); err != nil {
		return "", fmt.Errorf("could not write Dockerfile: %w", err)
	}

	// Copy static assets if public/ directory exists in source
	if entries, err := os.ReadDir("public"); err == nil {
		for _, entry := range entries {
			src := filepath.Join("public", entry.Name())
			dst := filepath.Join(publicDir, entry.Name())
			data, err := os.ReadFile(src)
			if err == nil {
				_ = os.WriteFile(dst, data, 0644)
			}
		}
	}

	return outDir, nil
}

func (d *Deployer) generateServerJS(compiledJS string) string {
	var out strings.Builder
	out.WriteString("// Auto-generated by Quill Deploy\n")
	out.WriteString(fmt.Sprintf("// Environment: %s\n", d.config.Env))
	out.WriteString(fmt.Sprintf("process.env.NODE_ENV = process.env.NODE_ENV || %q;\n\n", d.config.Env))
	out.WriteString(compiledJS)
	out.WriteString("\n")
	return out.String()
}

// GenerateDockerfile generates a Dockerfile for the app.
func (d *Deployer) GenerateDockerfile() string {
	var out strings.Builder
	out.WriteString("FROM node:20-alpine\n\n")
	out.WriteString("WORKDIR /app\n\n")
	out.WriteString("COPY package.json .\n")
	out.WriteString("RUN npm install --production\n\n")
	out.WriteString("COPY . .\n\n")
	out.WriteString(fmt.Sprintf("ENV NODE_ENV=%s\n", d.config.Env))
	out.WriteString(fmt.Sprintf("ENV PORT=%d\n\n", d.config.Port))
	out.WriteString(fmt.Sprintf("EXPOSE %d\n\n", d.config.Port))
	out.WriteString("CMD [\"npm\", \"start\"]\n")
	return out.String()
}

// GeneratePackageJSON generates package.json with dependencies.
func (d *Deployer) GeneratePackageJSON() string {
	var out strings.Builder
	out.WriteString("{\n")
	out.WriteString(fmt.Sprintf("  \"name\": %q,\n", d.config.AppName))
	out.WriteString("  \"version\": \"1.0.0\",\n")
	out.WriteString("  \"private\": true,\n")
	out.WriteString("  \"scripts\": {\n")
	out.WriteString(fmt.Sprintf("    \"start\": \"node server.js\",\n"))
	out.WriteString(fmt.Sprintf("    \"dev\": \"NODE_ENV=development node server.js\"\n"))
	out.WriteString("  },\n")
	out.WriteString("  \"dependencies\": {\n")
	out.WriteString("    \"better-sqlite3\": \"^9.0.0\"\n")
	out.WriteString("  }\n")
	out.WriteString("}\n")
	return out.String()
}

// Deploy generates deployment artifacts to the output directory.
func (d *Deployer) Deploy(compiledJS string) error {
	outDir, err := d.PrepareBundle(compiledJS)
	if err != nil {
		return err
	}

	fmt.Printf("Deployment bundle ready in %s/\n", outDir)
	fmt.Printf("Run: cd %s && npm install && npm start\n", outDir)
	fmt.Printf("Or: cd %s && docker build -t %s . && docker run -p %d:%d %s\n",
		outDir, d.config.AppName, d.config.Port, d.config.Port, d.config.AppName)

	return nil
}
