package tools

import (
	"fmt"
	"quill/ast"
	"strings"
)

// FullStackApp represents a parsed full-stack Quill application.
type FullStackApp struct {
	Server   *ServerBlock
	Database *DatabaseBlock
	Auth     *AuthBlock
	Frontend []ast.Statement // component and mount statements
}

// ServerBlock represents a server: section in a full-stack .quill file.
type ServerBlock struct {
	Port   int
	Routes []RouteHandler
	Line   int
}

// RouteHandler represents a single route definition.
type RouteHandler struct {
	Method string // get, post, put, delete
	Path   string
	Body   []ast.Statement
	Line   int
}

// DatabaseBlock represents a database: section in a full-stack .quill file.
type DatabaseBlock struct {
	ConnectString string
	Models        []ModelDefinition
	Line          int
}

// ModelDefinition represents a model definition within a database block.
type ModelDefinition struct {
	Name   string
	Fields []ModelField
}

// ModelField represents a single field in a model.
type ModelField struct {
	Name string
	Type string
}

// AuthBlock represents an auth: section in a full-stack .quill file.
type AuthBlock struct {
	Secret string
	Routes []RouteHandler
	Line   int
}

// GenerateFullStack generates a complete Node.js server from a FullStackApp.
func GenerateFullStack(app *FullStackApp, frontendJS string) string {
	var out strings.Builder

	out.WriteString("// Auto-generated by Quill - Full-Stack App\n")
	out.WriteString("const http = require('http');\n\n")

	// Database setup
	if app.Database != nil {
		out.WriteString(generateDatabaseSetup(app.Database))
		out.WriteString("\n")
	}

	// Auth setup
	if app.Auth != nil {
		out.WriteString(generateAuthSetup(app.Auth))
		out.WriteString("\n")
	}

	// Collect all routes
	var allRoutes []RouteHandler
	if app.Server != nil {
		allRoutes = append(allRoutes, app.Server.Routes...)
	}
	if app.Auth != nil {
		allRoutes = append(allRoutes, app.Auth.Routes...)
	}

	// Generate server
	port := 3000
	if app.Server != nil && app.Server.Port > 0 {
		port = app.Server.Port
	}

	out.WriteString("const server = http.createServer(async (req, res) => {\n")
	out.WriteString("  const url = new URL(req.url, `http://${req.headers.host}`);\n")
	out.WriteString("  const method = req.method.toLowerCase();\n")
	out.WriteString("  const request = { body: null, params: {}, query: Object.fromEntries(url.searchParams) };\n\n")

	// Body parsing for POST/PUT
	out.WriteString("  if (method === 'post' || method === 'put') {\n")
	out.WriteString("    request.body = await new Promise(resolve => {\n")
	out.WriteString("      let body = '';\n")
	out.WriteString("      req.on('data', c => body += c);\n")
	out.WriteString("      req.on('end', () => {\n")
	out.WriteString("        try { resolve(JSON.parse(body)); }\n")
	out.WriteString("        catch(e) { resolve(body); }\n")
	out.WriteString("      });\n")
	out.WriteString("    });\n")
	out.WriteString("  }\n\n")

	// Route matching
	out.WriteString("  try {\n")
	for _, route := range allRoutes {
		out.WriteString(generateRouteHandler(route))
	}
	out.WriteString("\n")

	// Frontend serving
	if frontendJS != "" {
		out.WriteString("    // Serve frontend for non-API routes\n")
		out.WriteString("    if (url.pathname === '/' || !url.pathname.startsWith('/api')) {\n")
		out.WriteString("      res.writeHead(200, {'Content-Type': 'text/html'});\n")
		out.WriteString("      res.end(`<!DOCTYPE html>\n")
		out.WriteString("<html><head><title>Quill App</title></head>\n")
		out.WriteString("<body><div id=\"app\"></div>\n")
		out.WriteString(fmt.Sprintf("<script>%s</script>\n", escapeTemplateJS(frontendJS)))
		out.WriteString("</body></html>`);\n")
		out.WriteString("      return;\n")
		out.WriteString("    }\n\n")
	}

	out.WriteString("    res.writeHead(404, {'Content-Type': 'application/json'});\n")
	out.WriteString("    res.end(JSON.stringify({error: 'Not Found'}));\n")
	out.WriteString("  } catch(err) {\n")
	out.WriteString("    res.writeHead(500, {'Content-Type': 'application/json'});\n")
	out.WriteString("    res.end(JSON.stringify({error: err.message}));\n")
	out.WriteString("  }\n")
	out.WriteString("});\n\n")

	out.WriteString(fmt.Sprintf("server.listen(%d, () => {\n", port))
	out.WriteString(fmt.Sprintf("  console.log('Quill app running on http://localhost:%d');\n", port))
	out.WriteString("});\n")

	return out.String()
}

func generateDatabaseSetup(db *DatabaseBlock) string {
	var out strings.Builder

	out.WriteString("// Database setup\n")
	out.WriteString("const __db_store = {};\n")
	out.WriteString("const DB = {\n")
	out.WriteString("  _models: {},\n")
	out.WriteString("  _store: __db_store,\n")
	out.WriteString(fmt.Sprintf("  _connStr: %q,\n", db.ConnectString))

	// Model method
	out.WriteString("  model: function(name, schema) {\n")
	out.WriteString("    const tableName = name.toLowerCase() + 's';\n")
	out.WriteString("    if (!__db_store[tableName]) __db_store[tableName] = [];\n")
	out.WriteString("    const model = {\n")
	out.WriteString("      _name: name,\n")
	out.WriteString("      _tableName: tableName,\n")
	out.WriteString("      _schema: schema,\n")
	out.WriteString("      create: function(data) {\n")
	out.WriteString("        const row = { id: __db_store[tableName].length + 1, ...data };\n")
	out.WriteString("        __db_store[tableName].push(row);\n")
	out.WriteString("        return row;\n")
	out.WriteString("      },\n")
	out.WriteString("      find: function(query) {\n")
	out.WriteString("        if (!query || Object.keys(query).length === 0) return __db_store[tableName];\n")
	out.WriteString("        return __db_store[tableName].filter(row => {\n")
	out.WriteString("          return Object.keys(query).every(k => row[k] == query[k]);\n")
	out.WriteString("        });\n")
	out.WriteString("      },\n")
	out.WriteString("      findOne: function(query) {\n")
	out.WriteString("        return this.find(query)[0] || null;\n")
	out.WriteString("      },\n")
	out.WriteString("      update: function(query, data) {\n")
	out.WriteString("        const rows = this.find(query);\n")
	out.WriteString("        rows.forEach(r => Object.assign(r, data));\n")
	out.WriteString("        return { changes: rows.length };\n")
	out.WriteString("      },\n")
	out.WriteString("      delete: function(query) {\n")
	out.WriteString("        const before = __db_store[tableName].length;\n")
	out.WriteString("        __db_store[tableName] = __db_store[tableName].filter(row => {\n")
	out.WriteString("          return !Object.keys(query).every(k => row[k] == query[k]);\n")
	out.WriteString("        });\n")
	out.WriteString("        return { changes: before - __db_store[tableName].length };\n")
	out.WriteString("      }\n")
	out.WriteString("    };\n")
	out.WriteString("    DB._models[name] = model;\n")
	out.WriteString("    return model;\n")
	out.WriteString("  },\n")

	// migrate method
	out.WriteString("  migrate: function() { /* tables auto-created */ },\n")

	// find/create convenience methods that delegate to first model
	out.WriteString("  find: function(query) {\n")
	out.WriteString("    const firstModel = Object.values(DB._models)[0];\n")
	out.WriteString("    return firstModel ? firstModel.find(query) : [];\n")
	out.WriteString("  },\n")
	out.WriteString("  create: function(data) {\n")
	out.WriteString("    const firstModel = Object.values(DB._models)[0];\n")
	out.WriteString("    return firstModel ? firstModel.create(data) : null;\n")
	out.WriteString("  }\n")
	out.WriteString("};\n\n")

	// Define models
	for _, model := range db.Models {
		schema := make([]string, len(model.Fields))
		for i, f := range model.Fields {
			schema[i] = fmt.Sprintf("%s: %q", f.Name, f.Type)
		}
		out.WriteString(fmt.Sprintf("DB.model(%q, { %s });\n", model.Name, strings.Join(schema, ", ")))
	}
	out.WriteString("DB.migrate();\n")

	return out.String()
}

func generateAuthSetup(auth *AuthBlock) string {
	var out strings.Builder

	out.WriteString("// Auth setup\n")
	out.WriteString(fmt.Sprintf("const __auth_secret = %q;\n", auth.Secret))

	// Minimal Auth runtime for token creation/verification
	out.WriteString(`const Auth = {
  createToken: function(payload, secret, expiresIn) {
    const header = JSON.stringify({alg: "HS256", typ: "JWT"});
    const now = Math.floor(Date.now() / 1000);
    const body = JSON.stringify({...payload, iat: now, exp: now + (expiresIn || 3600)});
    const b64 = (s) => Buffer.from(s).toString('base64url');
    return b64(header) + '.' + b64(body) + '.sig';
  },
  verifyToken: function(token, secret) {
    try {
      const parts = token.split('.');
      const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString());
      const now = Math.floor(Date.now() / 1000);
      if (payload.exp && payload.exp < now) return { valid: false, error: "expired" };
      return { valid: true, payload };
    } catch(e) { return { valid: false, error: e.message }; }
  }
};
`)

	return out.String()
}

func generateRouteHandler(route RouteHandler) string {
	var out strings.Builder

	out.WriteString(fmt.Sprintf("    if (method === '%s' && url.pathname === '%s') {\n", route.Method, route.Path))

	// Generate body statements
	for _, stmt := range route.Body {
		out.WriteString("      ")
		out.WriteString(generateRouteStmt(stmt))
		out.WriteString("\n")
	}

	out.WriteString("      return;\n")
	out.WriteString("    }\n")

	return out.String()
}

func generateRouteStmt(stmt ast.Statement) string {
	switch s := stmt.(type) {
	case *ast.RespondStatement:
		statusCode := s.StatusCode
		if statusCode == 0 {
			statusCode = 200
		}
		return fmt.Sprintf("res.writeHead(%d, {'Content-Type': 'application/json'}); res.end(JSON.stringify(%s));", statusCode, generateSimpleExpr(s.Value))
	case *ast.AssignStatement:
		return fmt.Sprintf("const %s = %s;", s.Name, generateSimpleExpr(s.Value))
	case *ast.ExprStatement:
		return generateSimpleExpr(s.Expr) + ";"
	default:
		return "/* unsupported statement */"
	}
}

func generateSimpleExpr(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.StringLiteral:
		return fmt.Sprintf("%q", e.Value)
	case *ast.NumberLiteral:
		if e.Value == float64(int64(e.Value)) {
			return fmt.Sprintf("%d", int64(e.Value))
		}
		return fmt.Sprintf("%g", e.Value)
	case *ast.Identifier:
		return e.Name
	case *ast.DotExpr:
		return generateSimpleExpr(e.Object) + "." + e.Field
	case *ast.CallExpr:
		args := make([]string, len(e.Args))
		for i, a := range e.Args {
			args[i] = generateSimpleExpr(a)
		}
		return fmt.Sprintf("%s(%s)", generateSimpleExpr(e.Function), strings.Join(args, ", "))
	case *ast.ObjectLiteral:
		if len(e.Keys) == 0 {
			return "{}"
		}
		pairs := make([]string, len(e.Keys))
		for i, k := range e.Keys {
			pairs[i] = fmt.Sprintf("%s: %s", k, generateSimpleExpr(e.Values[i]))
		}
		return "{ " + strings.Join(pairs, ", ") + " }"
	case *ast.AwaitExpr:
		return "await " + generateSimpleExpr(e.Expr)
	case *ast.BoolLiteral:
		if e.Value {
			return "true"
		}
		return "false"
	case *ast.ListLiteral:
		elems := make([]string, len(e.Elements))
		for i, el := range e.Elements {
			elems[i] = generateSimpleExpr(el)
		}
		return "[" + strings.Join(elems, ", ") + "]"
	default:
		return "undefined"
	}
}

func escapeTemplateJS(js string) string {
	js = strings.ReplaceAll(js, "\\", "\\\\")
	js = strings.ReplaceAll(js, "`", "\\`")
	js = strings.ReplaceAll(js, "${", "\\${")
	return js
}
