package tools

import (
	"fmt"
	"strings"
)

// Generator handles template-based code generation for Quill apps.
type AppGenerator struct {
	templates map[string]string // template name -> template content
}

// AppTemplate represents a generated application scaffold.
type AppTemplate struct {
	Name        string
	Description string
	Files       []GeneratedFile
}

// GeneratedFile represents a single generated file.
type GeneratedFile struct {
	Path    string
	Content string
}

// NewAppGenerator creates a new Generator with built-in templates.
func NewAppGenerator() *AppGenerator {
	return &AppGenerator{
		templates: make(map[string]string),
	}
}

// ParsePrompt extracts template type and parameters from natural language.
func ParsePrompt(prompt string) (string, string) {
	lower := strings.ToLower(prompt)

	// Check for CRUD pattern first: "crud <model>"
	if strings.Contains(lower, "crud") {
		// Extract model name
		parts := strings.Fields(lower)
		for i, p := range parts {
			if p == "crud" && i+1 < len(parts) {
				return "crud", parts[i+1]
			}
		}
		return "crud", "item"
	}

	// Match keywords to templates (ordered for deterministic matching)
	type templateMatch struct {
		name  string
		words []string
	}
	templates := []templateMatch{
		{"blog", []string{"blog", "post", "article", "writing"}},
		{"chat", []string{"chat", "realtime", "websocket", "messaging"}},
		{"dashboard", []string{"dashboard", "admin", "panel", "management"}},
		{"auth", []string{"auth", "login", "signup", "authentication", "session"}},
		{"api", []string{"api", "rest", "endpoint", "backend"}},
	}

	for _, tmpl := range templates {
		for _, word := range tmpl.words {
			if strings.Contains(lower, word) {
				return tmpl.name, ""
			}
		}
	}

	return "api", "" // default to API template
}

// Generate generates an app template based on the prompt.
func (g *AppGenerator) Generate(prompt string) AppTemplate {
	templateType, param := ParsePrompt(prompt)

	switch templateType {
	case "blog":
		return GenerateBlog()
	case "api":
		return GenerateAPI()
	case "chat":
		return GenerateChat()
	case "crud":
		return GenerateCRUD(param)
	case "auth":
		return GenerateAuth()
	case "dashboard":
		return GenerateDashboard()
	default:
		return GenerateAPI()
	}
}

// GenerateBlog generates a blog app scaffold.
func GenerateBlog() AppTemplate {
	return AppTemplate{
		Name:        "blog",
		Description: "A blog with auth, comments, and markdown support",
		Files: []GeneratedFile{
			{
				Path: "app.quill",
				Content: `-- Blog Application
-- Generated by Quill

server:
    port 3000

database:
    connect "sqlite://blog.db"

    model Post:
        title is string
        content is text
        author is string
        created_at is datetime

    model Comment:
        post_id is integer
        body is text
        author is string
        created_at is datetime

auth:
    secret "change-me-in-production"

    route post "/api/login":
        user is DB.find({email: request.body.email})
        token is Auth.createToken({id: user.id, email: user.email}, "change-me-in-production")
        respond {token: token}

route get "/api/posts":
    posts is DB._models.Post.find({})
    respond posts

route post "/api/posts":
    post is DB._models.Post.create(request.body)
    respond post status 201

route get "/api/posts/:id/comments":
    comments is DB._models.Comment.find({post_id: request.query.post_id})
    respond comments

route post "/api/posts/:id/comments":
    comment is DB._models.Comment.create(request.body)
    respond comment status 201
`,
			},
			{
				Path: "seeds/seed.quill",
				Content: `-- Seed data for blog
say "Seeding blog data..."

DB._models.Post.create({title: "Hello World", content: "Welcome to my blog!", author: "admin", created_at: "2024-01-01"})
DB._models.Post.create({title: "Second Post", content: "More content here.", author: "admin", created_at: "2024-01-02"})

say "Seeding complete!"
`,
			},
		},
	}
}

// GenerateAPI generates a REST API scaffold.
func GenerateAPI() AppTemplate {
	return AppTemplate{
		Name:        "api",
		Description: "A REST API with CRUD, auth middleware, and validation",
		Files: []GeneratedFile{
			{
				Path: "app.quill",
				Content: `-- REST API Application
-- Generated by Quill

server:
    port 3000

database:
    connect "sqlite://api.db"

    model Item:
        name is string
        description is text
        price is number
        created_at is datetime

auth:
    secret "change-me-in-production"

    route post "/api/login":
        token is Auth.createToken({role: "admin"}, "change-me-in-production")
        respond {token: token}

route get "/api/items":
    items is DB._models.Item.find({})
    respond items

route post "/api/items":
    item is DB._models.Item.create(request.body)
    respond item status 201

route get "/api/health":
    respond {status: "ok", uptime: process.uptime()}
`,
			},
		},
	}
}

// GenerateChat generates a WebSocket chat app scaffold.
func GenerateChat() AppTemplate {
	return AppTemplate{
		Name:        "chat",
		Description: "A WebSocket chat app with rooms and message history",
		Files: []GeneratedFile{
			{
				Path: "app.quill",
				Content: `-- Chat Application
-- Generated by Quill

server:
    port 3000

database:
    connect "sqlite://chat.db"

    model Message:
        room is string
        sender is string
        content is text
        created_at is datetime

    model Room:
        name is string
        created_at is datetime

route get "/api/rooms":
    rooms is DB._models.Room.find({})
    respond rooms

route post "/api/rooms":
    room is DB._models.Room.create(request.body)
    respond room status 201

route get "/api/messages":
    messages is DB._models.Message.find({room: request.query.room})
    respond messages

route post "/api/messages":
    message is DB._models.Message.create(request.body)
    respond message status 201
`,
			},
		},
	}
}

// GenerateCRUD generates CRUD routes and model definition for a given model name.
func GenerateCRUD(model string) AppTemplate {
	if model == "" {
		model = "item"
	}
	modelCap := strings.ToUpper(model[:1]) + model[1:]
	modelPlural := strings.ToLower(model) + "s"

	return AppTemplate{
		Name:        "crud-" + model,
		Description: fmt.Sprintf("CRUD routes for %s", modelCap),
		Files: []GeneratedFile{
			{
				Path: "app.quill",
				Content: fmt.Sprintf(`-- CRUD Application for %s
-- Generated by Quill

server:
    port 3000

database:
    connect "sqlite://app.db"

    model %s:
        name is string
        description is text
        created_at is datetime

route get "/api/%s":
    items is DB._models.%s.find({})
    respond items

route post "/api/%s":
    item is DB._models.%s.create(request.body)
    respond item status 201

route get "/api/%s/:id":
    item is DB._models.%s.findOne({id: request.query.id})
    respond item

route post "/api/%s/:id":
    result is DB._models.%s.update({id: request.query.id}, request.body)
    respond result

route post "/api/%s/:id/delete":
    result is DB._models.%s.delete({id: request.query.id})
    respond result
`, modelCap, modelCap,
					modelPlural, modelCap,
					modelPlural, modelCap,
					modelPlural, modelCap,
					modelPlural, modelCap,
					modelPlural, modelCap),
			},
		},
	}
}

// GenerateAuth generates authentication setup scaffold.
func GenerateAuth() AppTemplate {
	return AppTemplate{
		Name:        "auth",
		Description: "Login/signup/logout routes with JWT and session management",
		Files: []GeneratedFile{
			{
				Path: "app.quill",
				Content: `-- Auth Application
-- Generated by Quill

server:
    port 3000

database:
    connect "sqlite://auth.db"

    model User:
        email is string
        password is string
        name is string
        created_at is datetime

auth:
    secret "change-me-in-production"

    route post "/api/signup":
        user is DB._models.User.create(request.body)
        token is Auth.createToken({id: user.id, email: user.email}, "change-me-in-production")
        respond {user: user, token: token} status 201

    route post "/api/login":
        user is DB._models.User.findOne({email: request.body.email})
        token is Auth.createToken({id: user.id, email: user.email}, "change-me-in-production")
        respond {token: token}

    route get "/api/me":
        respond {message: "Protected route - implement token verification"}

route post "/api/logout":
    respond {message: "Logged out"}
`,
			},
		},
	}
}

// GenerateDashboard generates an admin dashboard scaffold.
func GenerateDashboard() AppTemplate {
	return AppTemplate{
		Name:        "dashboard",
		Description: "Admin panel with listing, editing, and stats",
		Files: []GeneratedFile{
			{
				Path: "app.quill",
				Content: `-- Dashboard Application
-- Generated by Quill

server:
    port 3000

database:
    connect "sqlite://dashboard.db"

    model User:
        email is string
        name is string
        role is string
        created_at is datetime

    model Activity:
        user_id is integer
        action is string
        details is text
        created_at is datetime

auth:
    secret "change-me-in-production"

    route post "/api/admin/login":
        token is Auth.createToken({role: "admin"}, "change-me-in-production")
        respond {token: token}

route get "/api/admin/users":
    users is DB._models.User.find({})
    respond users

route get "/api/admin/stats":
    users is DB._models.User.find({})
    activities is DB._models.Activity.find({})
    respond {userCount: users.length, activityCount: activities.length}

route get "/api/admin/activity":
    activities is DB._models.Activity.find({})
    respond activities
`,
			},
		},
	}
}
